### ISSUE TITLE
Only Clash works

### ISSUE THREAD

**Issue by lastwall** [hiddify/hiddify-config#1]
Hi, It seems on auto installation only clash fully works even with CDN inside IRAN works smooth
But other shadowsocks, vmess and etc not working at all any help regarding this?
and how can we debug this

**Comment by hiddify** [comment]
FakeTLS cannot be supported by CDN. So, if your server IP is in deep analysis range (e.g., the servers in hetzner and ovh), you cannot connect to shadowsocks+faketls and telegram.

I have changed the name of config in the second approach so you should be able to see the name of config with second approach. Would you please let me know which one works?

**Comment by hiddify** [comment]
Please let us know more about your issue
