### ISSUE TITLE
دامین فرانتینگ

### ISSUE THREAD

**Issue by amirmhs58** [hiddify/hiddify-config#100]
سلام
1-
در ورژن جدید دامین فرانتینگ کار نمیکنه اصلا" !!!
لطفا بفرمایید چگونه رفع این مشکل کنیم ؟یا اگر باگ سیستم است کی برطرف میشه !؟
2-در مورد قابلیتی داخل پنل ادمین > پراکسی ها > V2Ray configurations هست که متوجه نشدم با فعالسازی یا غیرفعالسازی آن چه اتفاقی می افتد.

**Comment by robin98** [comment]
این رو مطالعه کنید ببینید براتون مفید هست یا خیر:
https://github.com/hiddify/hiddify-config/issues/96
