### ISSUE TITLE
ایرانسل

### ISSUE THREAD

**Issue by hajalireza97** [hiddify/hiddify-config#101]
دوستان راهی واسه نت ایرانسل هست؟

**Comment by botgame96** [comment]
سلام بله هست ولی باید روی حالت CDN دامین هاتو تنظیم کنی و ببریشون رو حالت proxy

**Comment by hajalireza97** [comment]
سلام میشه بیشتر توضیح بدین؟
Cdn رو تغییر میدم ولی باز نمیشه

**Comment by robin98** [comment]
در یوتیوب در این زمینه راهکارهایی هست از جمله کانال آقای باشسیز:
https://www.youtube.com/@MortezaBashsiz

**Comment by Ehsan3500** [comment]
for irancell there are 2 workaround 
1 using cloudflare workers+utls+ http1 and ws  in vmess protocol  : check isegarao account in twitter for details
2 using cloudflare clear ips with bashsiz cf scanner  check bashsiz twitter and youtube account

**Comment by bikhabi** [comment]
من تمامی راه ها رو رفتم و سی دی ان ها رو تنظیم کردم و تنظیمات خود پنل رو هم همینطور
متایفانه پنل جدید هیچکدوم از اکانت هاش به ایرانسل و همراه اول وصل نمیشه اما مثلا در زیتل فوق العاده است

**Comment by Ehsan3500** [comment]
این رو هم تست کن برای من جواب داد 

Vmess. Cdn proxy on 443 ws tls utls:chrome alpn:http1.1 allow insecure: false

**Comment by robin98** [comment]
ایرانسل روی بسیاری از آی پی های کلادفلیر اختلال ایجاد کرده در حالی که پینگ و ... دارید اما اتصال امکانپذیر نیست (نمی دانم شاید هم بعضی رنج های کلادفلیر دوره ای این خاصیت را پیدا می کند و این اتفاق از سمت آنها هم ممکن است روی داده باشد)

**Comment by oxnetzz22** [comment]
درود اگر ایرانسل براتون جواب نمیده تیک فایروال رو بردارید مشکل حل میشه

**Comment by lumanjre** [comment]
دوستان ویکی را بخونید مطالب مفیدی اونجا هست.

**Comment by diehard2007** [comment]
سلام 

> درود اگر ایرانسل براتون جواب نمیده تیک فایروال رو بردارید مشکل حل میشه

سلام وخسته نباشید تیک فایروال رو از کجا برداریم پنل من سنایی هست . من مجبور شدم تونل برعکس بزنم ایرانسل روش جواب نمی ده چه کار کنم
