### ISSUE TITLE
 پسورد root

### ISSUE THREAD

**Issue by amirmhs58** [hiddify/hiddify-config#102]
سلام

در ورژن دیتاسنتر اوراکل پسورد یوزر root را چگونه بدست بیاریم ؟نمیتونم وصل بشم به محیط سیستم عامل.کلافه شدم از بس بالاپایین کردم.ممنون میشم راهنمایی کنید.

متشکر

**Comment by hiddify** [comment]
در هنگام نصب پابلیک کی خود را وارد کنید

**Comment by amirmhs58** [comment]
بله وصل میشم با public key ولی یوزر و پسورد میخواد.نه یوزر root نه یوزر ubuntu وارد نمیشه !!!میشه راهنمایی کنید.

**Comment by hiddify** [comment]
اگه درست وارد شده باشه بعد از نصب در صفحه تنظیمات private key را نشون نمیده اگه هم نشون بده با پرایوت کی و یوزر اوبونتو میتونید وصل بشید
