### ISSUE TITLE
لیمیت یوزر

### ISSUE THREAD

**Issue by SHUBLEx** [hiddify/hiddify-config#109]
لطفا لیمیت یوزر رو اد کنید چون واقعا بدرد میخوره 
بعد یه چیز دیگه ، اینکه امکان این هست که دو نسخه از پنل کاربری داده بشه؟ یکی مدرن تر و سنگین تر ، یکی قدیمی تر و با دیزاین بد ولی سبک تر ، بعد کاربر هر کدومو خواست استفاده کنه

**Comment by hiddify** [comment]
دوست عزیز نگران سنگینی پنل نباشید
سعی شده اصن سنگین نباشه
لیمیت یوزر داره دیگه

**Comment by SHUBLEx** [comment]
ببخشید لیمیت یوزر تو کدوم بخشه؟

**Comment by sh4msi** [comment]
این سوال بنده هم هست
تقریبا همه جای پنل رو چک کردم ولی قسمتی برا فعال کردن تنظیمات محدودیت تعداد کاربر روی یک کانکشن خاص ندیدم
