### ISSUE TITLE
Please support SSR

### ISSUE THREAD

**Issue by ea1234567** [hiddify/hiddify-config#11]
Please support SSR 

Multi user preferred

**Comment by hiddify** [comment]
Would you please add the script?

**Comment by ea1234567** [comment]
> Would you please add the script?

I don't understand what you mean, can you explain more?

**Comment by hiddify** [comment]
Can you please add install script for SSR?

**Comment by amihos** [comment]
There is a script here
https://github.com/ToyoDAdoubi/doubi#ssrmush

**Comment by hiddify** [comment]
please add as pull request.

**Comment by lymanjre** [comment]
Close the issue cuz we support it now

**Comment by mrgeex** [comment]
I think ShadowSocksR (SSR) is different than ShadowSocks2022 or faketls (which is currently supported by Hiddify Manager). Since I didn't find SSR settings in Hiddify Manager. It's not supported by Hiddify App either.

Here's an example of SSR config:
    {
      "type": "shadowsocksr",
      "tag": "韩国2 VIP1 网址nnbin.com",
      "server": "****",
      "server_port": 105,
      "method": "aes-256-cfb",
      "password": "****",
      "obfs": "http_simple",
      "obfs_param": "54232608743.microsoft.com",
      "protocol": "auth_aes128_sha1",
      "protocol_param": "608743:vdgGvV",
      "network": "tcp"
    },
