### ISSUE TITLE
انتخاب نام دلخواه

### ISSUE THREAD

**Issue by ahaddiba** [hiddify/hiddify-config#110]
سلام امکانش هست برای کانکشن ها خودمون اسم انتخاب کنیم ؟

**Comment by ahaddiba** [comment]
مشکلی که وجود داره اسم دامین رو اسم کانکشن ها میاد و این باعث شناسایی سریع سرور میشه

**Comment by ahaddiba** [comment]
بله این روش رو اطلاع دارم ! اما بنظرم اگر داخل پنل این امکان فراهم باشه بصورت پیش فرض بنظرم بسیار امکان خوبی خواهد بود

**Comment by hiddify** [comment]
آخه اساسا این اسم را کسی جز مصرف کننده نمیبینه که باعث شناسایی بشه
