### ISSUE TITLE
vmess

### ISSUE THREAD

**Issue by aag0116** [hiddify/hiddify-config#12]
vmess dont connect after Update

**Comment by kianograph** [comment]
yep, we have problem with connecting to vmess connection on iphone too!
any update?

**Comment by aag0116** [comment]
no thanks

**Comment by hiddify** [comment]
Thanks for  reporting the bug
Fixed in new update https://github.com/hiddify/hiddify-config/commit/0d329357baede44e86b8ec233c42b0500480487d
