### ISSUE TITLE
Failed to start ss-server

### ISSUE THREAD

**Issue by parsatavafi** [hiddify/hiddify-config#126]
سلام در سرویس های من سرویس ss-server فعال نمیشه. من از status سرویس شات گرفتم ممنون میشم دوستان نظر بدند :
![Capture](https://user-images.githubusercontent.com/124770095/218347588-67f4d504-0514-4942-b631-4234295bda2a.JPG)

**Comment by parsatavafi** [comment]
عزیزان هیچ کس به این مشکل نخورده تا الان؟

**Comment by hiddify** [comment]
دستورشو دستی اجرا کنید ببینید چه خطایی میده

**Comment by parsatavafi** [comment]
ممکنه اگر این مشکل فقط برای من هست جایی در تنظیمات رو اشتباه کرده باشم؟

**Comment by hiddify** [comment]
ss-server
فقط برای حالت faketls استفاده میشه که تقریبا ازش استفاده نمیکنیم

**Comment by parsatavafi** [comment]
> ss-server فقط برای حالت faketls استفاده میشه که تقریبا ازش استفاده نمیکنیم

@hiddify  خیلی ممنونم. پس میشه کلا disable اش کرد درسته؟
