### ISSUE TITLE
مشکل بلاک شدن آی پی

### ISSUE THREAD

**Issue by Zed-Max-Wolf** [hiddify/hiddify-config#131]
سلام
در طول 10 روز 2 بار آی پی سرور با اینکه طبق آموزش به دامنه وصلش کردم فیلتر شده 
آیا راهی وجود داره که شناسایی آی پی رو سختر یا غیر ممکن کنم تا آی پی جدید فیلتر نشه؟
فقط اگر وجود داره لطفاً آموزش دهید 
با تشکر

**Comment by hiddify** [comment]
به زودی روی نرم افزارها utls فعال میشه که تقریبا شناسایی سرور را غیر ممکن میکنه

**Comment by lumanjre** [comment]
این قابلیت راه اندازی شده و نباید مشکلی باشه. غیر از اینکه آیپی سرور در لیست زرد باشه که باید از مطالب یکی استفاده کنید برای پیدا کردن آیپی درست و تمیز.
