### ISSUE TITLE
400 Bad Request: Invalid Proxy Path مشکل ارور 

### ISSUE THREAD

**Issue by alinoori77** [hiddify/hiddify-config#137]
سلام
بعد از نصب کامل اسکریپ و ورود به پنل زمانی که دومین رو ست می کنم . submit  رو می زنم پیغام اعمال تغییرات بالای صفحه می یاد که زیرش هم نوشته حدودا 2 دقیقه طول می کشه بعد از زدن اون دکمه پیغام 
Oops! Something went wrong.
400 Bad Request: Invalid Proxy Path
رو میده 
ممنون می شم راهنمایی کنید

**Comment by miladj3** [comment]
منم زیاد این مشکلو میبینم و برمیخورم بخصوص وقتی تغییری دارم و apply changes میزنم

**Comment by miladj3** [comment]
admin/actions/reinstall?complete_install=False&domain_changed=True

**Comment by akv79** [comment]
تمام کامندهای دسته actions مثل apply config و reinstall فقط تو دامین دایرکت عمل میکنن و تو دامین cdn خطای بالا رو میدن

**Comment by alinoori77** [comment]
اره دیروز این ارور رو نمی داد امروز داره می ده
با وجود این خطا وی پی ان کار می کنه یا نه باید صبر کنیم درست بشه ؟

**Comment by just1random** [comment]
You can use Actions -> Apply Config from the menu until this gets fixed.

**Comment by hiddify** [comment]
رفع شده مشکل

**Comment by abolfaz315** [comment]
برای رفع مشکل باید چیکار ‌کرد

**Comment by miladj3** [comment]
اپدیت کنید
