### ISSUE TITLE
مشکل در از دسترس خارج شدن سرور وب سرویس

### ISSUE THREAD

**Issue by miladj3** [hiddify/hiddify-config#142]
یک مشکلی که هست اینه و دایم هر چند دقیقه یکبار بهش برمیخورم، مشکل از دسترس خارج شدن وب سرویس به طور موقت هستش که هم پنل ادمین و هم پنل کاربر اینجوری میشه
![ddddddd2-07-25](https://user-images.githubusercontent.com/16199445/218827750-9aba86c7-65c9-4292-9eff-2a71a50e0119.jpg)

**Comment by SadeghPM** [comment]
روی cloudflare هم همین اتفاق میفته

**Comment by parsaahaniii** [comment]
با کامند dig مطمئن بشید که اون دامین/ساب دامین فیلتر نشده باشه
من هم همین مشکل رو داشتم و مشکل فیلتر شدن ساب دامین بود یا همون ریزالو نشدن دی ان اسش در ایران
مثلا:
`dig @8.8.8.8 google.com`

**Comment by parsatavafi** [comment]
> با کامند dig مطمئن بشید که اون دامین/ساب دامین فیلتر نشده باشه من هم همین مشکل رو داشتم و مشکل فیلتر شدن ساب دامین بود یا همون ریزالو نشدن دی ان اسش در ایران مثلا: `dig @8.8.8.8 google.com`

دوست من @parsaahaniii؛ یکی از بزرگترین مشکلات من رو شما میتونید حل کنید! من به طور معمول برای چک کردن این که آی پی و یا ساب دامین فیلتر شده کاری که می کنم اینه که :

> با اپراتورهای مختلف (ایرانسل، همراه اول، رایتل، ADSL مخابرات و سایر اپراتورهایی که در دسترسم هست {و این خودش یه مشکله چون خیلی از اپراتورها رو نمیتونم چک کنم که فیلتر هست یا خیر! فیلترینگ ظاهرا اپراتور به اپراتور مختلفه} کامپیوتر رو متصل می کنم و از Commander ویندوز شروع می کنم به پینگ گرفتن IP و همچنین SubDomain ... خیلی مشکلات زیادی داره این روش

این دستوری که شما فرمودید :

- باید روی VPS اجرا بشه یا سمت کاربر؟
- میتونه اپراتورهای مختلف رو چک کنه؟
- ممکنه لطف کنید در مورد دستور یه مقدار توضیح بدید؟ چه چیزی باید داخلش تغییر کنه یا همین جوری توی کنسول نوشته بشه؟

**Comment by pouya8228** [comment]
خطای 504 مربوط به ارتباط DNS سرور با سرور شماست ، احتمال میدم که از آروان دارید استفاده میکنید ، میتونم بگم توی 2 الی 3 ماه اخیر هر وقت از آروان استفاده کردم این برام پیش اومده . از کلود فلر استفاده کنید .

**Comment by miladj3** [comment]
من لز آروان استفاده میکنم و حدس میزنم که به همین خاطر باشه. تست میکنم روی clloudflare ببینم نتبیجه چی میشه. البته اینجوریه که مثلا ایرانسل همون موقع درسته اما همراه اول این اررورو میده

**Comment by lumanjre** [comment]
update to latest version. it is fixed
