### ISSUE TITLE
تنظیمات دامین فرانتینگ در صفحه کاربر نمایش داده نمیشه

### ISSUE THREAD

**Issue by R30na** [hiddify/hiddify-config#150]
سلام بعد از فعال کردن تنظیمات دامین فرانتینگ در صفحه پروکسی این تنظیمات در صفحه کاربر نمایش داده نمیشه

**Comment by hiddify** [comment]
الان اتوماتیک با توجه به سیستم عامل کاربر کانفیگ مربوطه را باز میکنه،  بهتر
نیست اینجوری؟

**Comment by robin98** [comment]
راستش به شخصه نظر من روی این مدل زیاد مثبت نیست چونکه حتی باعث گیج شدن خود من هم شده چه برسه به کاربران.
الان به نظر در حالت عادی کانفیگ های Fake TLS توی لیست نمیاد، با همه یوزر ایجنت ها هم تست کردم، فقط و فقط وقتی که انتهای آدرس بزنیم multi وارد صفحه کانفیگ ها میشه. همچنین همه کانفیگ ها روی تمام سیستم عامل ها قابل استفاده هستن (مگر اون لینک کلش یا ساب اسکرایب اول جدول)
همچنین توجه کنید ممکنه ادمین، چندین دامین مختلف روی سرور ست بکنه به آدرس های مختلفی از شبکه CDN، اما الان اگه لینک مالتی رو به یوزر بدیم ممکنه تعداد کانفیگ های تکراری خیلی زیاد بشن و باعث سردرگمی یوزر بشه.
