### ISSUE TITLE
Relay domain proxy

### ISSUE THREAD

**Issue by Mobinoo1383** [hiddify/hiddify-config#155]
Hi @hiddify I would like to first thank you for this good,easy,simple and effective project of yours
Secondly I set up two domains on my panel one cdn and one direct then I imported it to stash and it worked all fine 
But then I added two other subdomains of the same previous two domains again one cdn and one direct then I entered the script you published for proxies and then pointed two different and new domains to the proxy server ip's and set it to dns only 
(By the way I use cloudflare)
Then I applied configs and made a new user afterwards I imported both lite and normal .yml's to stash and I got this error![image](https://user-images.githubusercontent.com/124462330/219005478-d9fe5c36-b274-4239-aee3-6dd755a124b2.png)
I then first deleted two subdomains one cdn and one direct 
What remained was one cdn domain one direct domain and two relay domains I figured it would be okay ,then I made another user and again imported the config to stash but I received the same error

**Comment by just1random** [comment]
I got this error multiple times on Clash for android. I think it is because the clash core can't download the connection entirely. Try saving the connection a few times, and it will work.

**Comment by Mobinoo1383** [comment]
Thanks @just1random ill try it out in a sec

**Comment by Mobinoo1383** [comment]
I tried downloading and saving it couple of times but it didn't work 
I'll eventually get it fixed tho

**Comment by hiddify** [comment]
ممنون از گزارش دقیقتون مشکل رفع شد
