### ISSUE TITLE
عوض کردن path

### ISSUE THREAD

**Issue by Hoseingn** [hiddify/hiddify-config#159]
سوال اول اینکه چرا بک اپ رو نمیتونیم دوباره رو پنل جدید بیاریمو ارور 404 میده؟
دومین سوال چطور میشه path رو عوض کرد؟

**Comment by Fl2ankenStein** [comment]
رو پنل میاد ولی باید پنل رو یه بار به اصطلاح reinstall بزنی تا درست کار کنه

**Comment by hiddify** [comment]
مشکل رفع شد به محض وارد کردن اطلاعات لینک جدید که با path  تغییر یافته است اعمال میشه و نمایش میده

**Comment by mhg777** [comment]
الان حتی پنل بالا نمیاد که بخام reinstall  بزنم که
