### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by MSotoudeh** [hiddify/hiddify-config#16]
I do it according to tutorial but finally it web page show a error 502 , bad gateway.
what's wrong?

**Comment by hiddify** [comment]
Which tutorial?

Do you have any other webserver or program in your server?

**Comment by MSotoudeh** [comment]
user guide that wrote in code section.

No I just setup it and over a fresh Ubuntu 20.04

Jan 6, 2023 10:41:13 AM Hiddify ***@***.***>:

**Comment by MSotoudeh** [comment]
> Which tutorial?
> 
> Do you have any other webserver or program in your server?

راهنمای نصب پیشرفته.

https://github.com/hiddify/hiddify-config/wiki/%D8%B1%D8%A7%D9%87%D9%86%D9%85%D8%A7%DB%8C-%D9%86%D8%B5%D8%A8-%D9%BE%DB%8C%D8%B4%D8%B1%D9%81%D8%AA%D9%87

**Comment by hiddify** [comment]
would you please give the `bash status.sh` output?

**Comment by Hosseinbadr** [comment]
i have this problem too and this is my bash status.sh output
bash: status.sh: No such file or directory

**Comment by parsaahaniii** [comment]
I have same issue, and I don`t have problem to see admin panel with IP.
Is related to nginx service status?

My statuses:
hiddify-admin                  active
gost                           inactive
hiddify_monitoring_web         active
ss-faketls                     active
ss-v2ray                       active
mtproxy                        active
trojan-go                      active
v2ray                          active
netdata                        inactive
nginx                          failed
xray                           active

**Comment by parsaahaniii** [comment]
> i have this problem too and this is my bash status.sh output bash: status.sh: No such file or directory

first to must go to /opt/ directory

**Comment by manizand** [comment]
Same problem here on newly configured server

**Comment by hiddify** [comment]
would you please give me the output of `systemctl status nginx`

**Comment by hiddify** [comment]
> > i have this problem too and this is my bash status.sh output bash: status.sh: No such file or directory
> 
> first you must go to /opt/ directory
you should go to 
`cd /opt/hiddify-config`

**Comment by hiddify** [comment]
I think it has been fixed in new version
