### ISSUE TITLE
مشکل دامین فرانتینگ

### ISSUE THREAD

**Issue by arman2012** [hiddify/hiddify-config#165]
**Describe the bug**
بعد از آپدیت دیروز در پنل کاربری کانفیگای دامین فرانتینگ هیچکدوم نمیاد یعنی کلا دو تا کانفیگش نیست

**Comment by hiddify** [comment]
امکانش هست لینک ادمین را ایمیل کنید hiddify@gmail.com

**Comment by arman2012** [comment]
بله ایمیل شد خدمتتون

**Comment by arman2012** [comment]
بله ایمیل شد خدمتتون

**Comment by parsatavafi** [comment]
بله من هم تائید می کنم این مورد رو زمانی که همه ی پروتکل ها و اپشن ها رو هم فعال می کنم، نهایتا 8-9 تا کانفیگ (مبنا رو لینک ساب میزارم) دارم

**Comment by arman2012** [comment]
هایدیفای جان به دادمون برس

**Comment by hiddify** [comment]
مشکل فقط دامین فرانتینگ هست؟

**Comment by arman2012** [comment]
من تونستم درستش کنم ولی نمیدونم چرا اینجوریه
وقتی تو قسمت دامین یه دامنه با fake درست میکنیم درست میشه قبلا نبود فقط دو گزینه دایرکت و cdn بود
الان فقط موقعی میتونیم از این قابلیت استفاده کنیم که دامینه fake اضافه کنیم

**Comment by elrazez** [comment]
من هم این مشکل رو دارم. کلا خیلی unstable شده این اپدیتای اخیر و همش مشکلات عجیب پیش میاد. تا دو سه روز پیش هم اینجوری نبود.

**Comment by elrazez** [comment]
بعد از اد کردن یه ساب دومین جداگانه و انتخاب کتگوری fake توی دامین‌ها به جای cdn یا direct مشکل حل میشه ولی بازم توی تنظیمات کلش نمیاد. بقیه جاها ولی میاد.

**Comment by hiddify** [comment]
متوجه شدیم دامین فرانتینگ روی مود HTTPS توسط کلود فلر بسته شده و امکان اینکار وجود نداره باید حذفش کنیم این بخشو

**Comment by elrazez** [comment]
> متوجه شدیم دامین فرانتینگ روی مود HTTPS توسط کلود فلر بسته شده و امکان اینکار وجود نداره باید حذفش کنیم این بخشو

اصلا کلودفلر دیگه سرعتی نداره برای ایران. روی ابرآروان داریم همه این کارها رو میکنیم که جواب میده فعلا. اصولا فقط fake sni روی سی دی ان ابراروان داره پینگ خوب میده و بقیه کانفیگا شکنجه هست سرعت و پینگشون.
