### ISSUE TITLE
Empty Admin links section

### ISSUE THREAD

**Issue by raminrez** [hiddify/hiddify-config#166]
When i added a new domain and hit the "Apply Configs", available admin links are empty for me. (Screenshot is provided)

<img width="1494" alt="Screenshot 2023-02-16 at 2 49 47 PM" src="https://user-images.githubusercontent.com/7345325/219351856-ac25d946-679f-4166-949d-70da72f99ef7.png">

**Comment by hiddify** [comment]
can you please send me ssh to email hiddify@gmail.com

**Comment by hiddify** [comment]
حل شده
