### ISSUE TITLE
تنظمات V2Ray

### ISSUE THREAD

**Issue by arman2012** [hiddify/hiddify-config#168]
سلام تو بخش تنظیمات پنل قسمتی هست به نام تنظمات V2Ray این قسمت برای چی هست؟ و چه کاری میکنه؟

**Comment by hiddify** [comment]
ترجمه بدی بوده 
enable v2ray
یه پروتکل دیگه هست که پیشنهاد نمیشه چون اکانتینگ را ساپورت نمیکنه در حال حاضر
اصلاح شد تو پنل
