### ISSUE TITLE
Insecure configuration and option to disable logging

### ISSUE THREAD

**Issue by nimagp** [hiddify/hiddify-config#17]
The only option of authentication for admin panel is ADMIN_SECRET, which is enforced via nginx URL filtering. Please notice that when using a CDN, provider is a literal MITM. Decrypting user side data and encrypting it to destination server. It can access headers(hence paths and URLs). and cookies. For the same reason using a password based method is not a very good decision and at least should be limited to one domain (**That is not under the control of CDN**)
Nginx by default may use weaker TLS ciphers. Most of devices now support TLSv1.3, so limiting TLS to TLSv1.2 and TLSv1.3 should not be a problem (Chiphers should be limited too).
Some people may don't need the logging and monitoring option. (Or using them is not safe). An option to completely disable logging is a needed feature in these cases.
Also a separation of subdomains to only route the CDN compatible methods through CDN is really appreciated 😅
Thanks

**Comment by hiddify** [comment]
Thanks for your great suggestions.

I agree with you that CDN is an unsafe solution. By the way, if someone is really interested in that, can use https://ip/admin_secret 
additional way can be use of secondary domain for non CDN usage, but it would be more complicated, no? I can add such an option for advanced users.

for logging, it is currently disabled. by the way, there is an option `ENABLE_MONITORING=false` to disable monitoring.


For TLS option, we are currently using xray as core not nginx to improve the performance, and we have already use tls1.2 as min version (https://github.com/hiddify/hiddify-config/blob/a13509ee4c5a6b260fe42b95a4b7ca7de170673a/xray/xtls-sni-config.json.template#L123)

We will to remove some nginx configs soon after making sure everything is working well :)

**Comment by hiddify** [comment]
We have added NO_CDN_DOMAIN (temporarily)  and disable monitoring by default.

We are looking forward for more suggestions :-)

**Comment by nimagp** [comment]
Thanks :)
Wouldn't setting NO_CDN_DOMAIN as default be better?
Even a freedns domain is compatible with SSL. If a user wants to use a CDN there can be an additional nginx(or xray) rule to allow access from another domain to compatible protocols (A little note on VLESS : It's unencrypted and not safe to use when TLS implementation is not trusted)
