### ISSUE TITLE
HTTPS Error

### ISSUE THREAD

**Issue by AlirezaJanbabaei** [hiddify/hiddify-config#170]
در اوبونتو hiddify رو نصب کردم و روی آروان ست کردم ولی وقتی با https میخوام وارد پنل بشم ارور زیر رو می‌گیرم.
بنظرم مشکل از این است که ssl در آروان از let's encrypt هست ولی با دستور نصب شما zerossl نصب می‌شه.
ممنون می‌شم راهنمایی کنید

This site can’t provide a secure connection ******* uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by navidnadery** [comment]
https://developers.cloudflare.com/ssl/troubleshooting/version-cipher-mismatch/#certificate-activation

اول اینکه اگر از CDN استفاده می کنید حتما ssl اش رو full بزنید و دوم اینکه از یک لول سابدامنه استفاده کنید.
