### ISSUE TITLE
SSL_ERROR_NO_CYPHER_OVERLAP

### ISSUE THREAD

**Issue by victorhodi** [hiddify/hiddify-config#174]
سلام
بعد از نصب این پیام ها رو میده
اما وقتی ادرس رو توی مرورگر باز میکنم خطای
SSL_ERROR_NO_CYPHER_OVERLAP
میده. تو تنظیمات مرورگر ورژن tls رو پایین اوردن ولی مشکل حل نشد

netdata                        active                         
ss-faketls                     active                         
ss-v2ray                       activating                     
hiddify-panel                  active                         
hiddify-sniproxy               active                         
hiddify-xray                   active                         
nginx                          failed                         
---------------------Finished!------------------------
===========================================================
Finished! Thank you for helping Iranians to skip filternet.
Please open the following link in the browser for client setup

Permanent Admin link: 
   http://ip///admin/ 

Secure Admin links: 

---------------------Finished!------------------------

**Comment by victorhodi** [comment]
مثل این که خطا از اینجاست:


systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-02-17 02:25:48 +0330; 2s ago
       Docs: man:nginx(8)
    Process: 29278 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Feb 17 02:25:48 myserver.local systemd[1]: Starting A high performance web server and a reverse proxy server...
Feb 17 02:25:48 myserver.local nginx[29278]: nginx: [emerg] invalid number of arguments in "proxy_set_header" directive in /opt/hiddify-config/ngi>
Feb 17 02:25:48 myserver.local nginx[29278]: nginx: configuration file /etc/nginx/nginx.conf test failed
Feb 17 02:25:48 myserver.local systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Feb 17 02:25:48 myserver.local systemd[1]: nginx.service: Failed with result 'exit-code'.
Feb 17 02:25:48 myserver.local systemd[1]: Failed to start A high performance web server and a reverse proxy server.

**Comment by hiddify** [comment]
پنل نصب نشده
ssh miferesti be hiddify@gmail.com
