### ISSUE TITLE
Keep crashing in click on Domain menu | critical bug

### ISSUE THREAD

**Issue by robin98** [hiddify/hiddify-config#175]
Tonight I was trying to add some domains as a CDN and another domain as the relay, then I delete the domains from cloudflare before deleting them in hiddify's panel first, now I notice that there is no way to entering domain menu again and every time I click on it, the whole script keep crashing and restart.

1. Add a domain as CDN and add another domain as relay
2. for some reason, remove that domains (that still in use in domain menu in hiddify)
3. after that, you'll realize that you can't enter the domain menu again

**Comment by hiddify** [comment]
please send admin link to hiddify@gmail.com to check it

**Comment by robin98** [comment]
It's done , so nothing left to check right now. After hours of trying, I was able to re-register that deleted domains again and since everything back to normal (a point that all my domains are active and reachable) then I was be able to re-enter to `Domains` menu delete those domains and everything is alright now.

I believe every time that admin click on the `Domains` button, somehow hiddify manage to validate current state of all domains and in case of failure, it'll stuck in such restart loop.
