### ISSUE TITLE
عدم حذف کامل هدیفای

### ISSUE THREAD

**Issue by sh4msi** [hiddify/hiddify-config#178]
سلام
[بعد اینکه پنل به خودی خود از کار افتاد! و ارور 504 داد](https://github.com/hiddify/hiddify-config/issues/172#issuecomment-1434194680)
احتمال دادم این از تنظیمات قبلی من به وجود اومده و خواستم پنل رو حذف و دوباره نصب کنم
که به ترتیب دستورات زیر رو اجرا کردم
`sudo bash /opt/hiddify-config/uninstall.sh`

`bash <(curl https://gist.githubusercontent.com/hiddify/63836c9a158eca29bad6c941610028cf/raw/3259b9a731761cc6c39c52469d7c17f903d2f32f/relay.sh) `

ولی متاسفانه بعد نصب چیزی که در خروجی نهایی بهم نشون میده ادرس ادمین بر حسب دامین هایی که به پنل اضافه کرد بودم هست و این مشخص میکنه تنظیمات قبلی من دوباره اعمال شدن

که همچنان پنل بالا نمیاد و 504 میده

**Comment by hiddify** [comment]
یه اپدیت بکنید اگه مشکل وجود داره همچنان ssh را بهم ایمیل کنید hiddify@gmail.com

**Comment by sh4msi** [comment]
بله، فعال بود
