### ISSUE TITLE
Possible DNS Leak

### ISSUE THREAD

**Issue by just1random** [hiddify/hiddify-config#18]
Doing a simple DNS Leak test on https://www.dnsleaktest.com/ or https://www.expressvpn.com/dns-leak-test shows possible DNS leaks, which is very concerning.

**Comment by hiddify** [comment]
Do you have any suggestion?

would you please let me know that this issue is exist also in route all domains?

**Comment by amihos** [comment]
I also faced this. I used the route all domain links and still see dnsleaks!

**Comment by amihos** [comment]
Update: I believe this is related to the client you use and not to server-side configuration. I just tested one of the servers with V2rayNg android client instead of clash or Hiddify and I did not see dnsleak.

**Comment by hiddify** [comment]
I have fixed the problem
in clash profiles and also in new version of HiddifyProxyAndroid

**Comment by amihos** [comment]
So what's needed to be done? Update server + update client?

**Comment by hiddify** [comment]
yes

**Comment by just1random** [comment]
I can confirm dns leakage is fixed (I checked it on every protocols)
