### ISSUE TITLE
Add proxy_path as an option to setup script

### ISSUE THREAD

**Issue by just1random** [hiddify/hiddify-config#183]
We can change admin path and users path on the panel. But there's no way to change `proxy_path` in the panel. Adding an option to provide `proxy_path` to installer (setup script) is essential because we don't want a different connection URL when we install Hiddify on a fresh server.

Something like:
`...(rest of setup script) --path=PATH_PROVIDED_BY_USER`

**Comment by hiddify** [comment]
متوجه هستم از نکته شما، میتونید کانفیگ را ریستور کنید و proxy_path هم تغییر کنه
ولی ایده خوبیه در مجموع

**Comment by hiddify** [comment]
کانفیگش اضافه شد به محیط ادمین
