### ISSUE TITLE
دامنه رو درحالت proxied یا cdn

### ISSUE THREAD

**Issue by parhamphd** [hiddify/hiddify-config#186]

**Comment by parhamphd** [comment]
برای اینکار با ایپی پنل هم میشه انجام داد
یا باید vps جدید بگیرم برای اینکار؟
و اگر جدید باید بگیرم هسته پنل چطور نصب میشه روش؟

**Comment by robin98** [comment]
منظورتون رو درست متوجه نشدم ولی به نظرم مبحث زیر از تب discussions شاید مفید باشه:
https://github.com/hiddify/hiddify-config/discussions/129#discussioncomment-4996908
