### ISSUE TITLE
Dns leak

### ISSUE THREAD

**Issue by Sky13944** [hiddify/hiddify-config#188]
![IMG_۲۰۲۳۰۲۱۹_۰۹۴۴۴۹](https://user-images.githubusercontent.com/119528914/219932388-aa673927-508a-49eb-b613-61b5ac7866e9.jpg)
سلام. من داشتم نشتی dns رو چک می کردم که این مشکل رو که تو عکس هست دیدم. لطفا بررسی کنید. قبلاً روی همین سرور v2ray داشتم اما مشکل نشتی dns وجود نداشت

**Comment by robin98** [comment]
فکر نمی کنم به پروتکل xray یا حتی توسعه دهندگان هایدیفای مربوط باشه. طبق تجربیات من، پیشفرض از DNS خود سرور استفاده میشه.
در اینجا حالا چند احتمال هست:

1. مرورگر یا سیستم عامل در لایه نرم افزار درخواست های DNS رو به عهده گرفته
2. کلاینتی که ازش استفاده می کنید عامل این قضیه هست
3. روی سرور تنظیماتی اعمال شده که ترافیک DNS کل سیستم عامل سرور رو به resolver های خاصی ارسال کنه
4. هایدیفای یا هسته xray داره اینکارو انجام میده که کمترین احتمال هست

از گزینه های بالا به ترتیب مطمئن بشید.
امن ترین و قابل اتکا ترین تست اون هستش که روی ویندوز سالم با v2rayN تونل رو برقرار کنید، مرورگر رو با افزونه switchy omega بندازید روی پراکسی 127.0.0.1:10808 که v2rayN براتون ایجاد کرده، و در آخر همین تست dnsleak رو مجدد انجام بدید.

اگر تفاوتی نکرد، می تونید تحلیل کننده های سمت سرور رو برای اطمینان بیشتر، از مسیر:
`/etc/resolv.conf`

یا از مسیر زیر: (ثابت حتی پس از ریبوت، پشتیبانی از DoT)
`/etc/systemd/resolved.conf`

تغییر بدید به هر resolver دلخواه عمومی یا خصوصی.

**Comment by hiddify** [comment]
اگه از کلاینت کلش استفاده میکنید این مشکل را دارید
ولی از کلاینت هیدیفای و v2ray نباید مشکلی باشه
