### ISSUE TITLE
User import configs button

### ISSUE THREAD

**Issue by Mobinoo1383** [hiddify/hiddify-config#191]
**Describe the bug**
Some of the configs are not imported when using the install button in user page 
I have one relay server domain setup and one cdn domain 
![image](https://user-images.githubusercontent.com/124462330/219963092-9bbd67c7-f129-44bd-a5fe-a87b1379f018.jpeg) but using this buttons only the cdn domain configurations get imported 
Although when I copy and paste the clash urls instead it imports both
![image](https://user-images.githubusercontent.com/124462330/219963317-0c692018-3213-4411-981c-95dd0d8b113f.jpeg)
I use stash btw
**To Reproduce**

**Expected behavior**
I expected all my configs to get imported 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 16
 - Browser opera gx
 - Version 

**Additional context**
Add any other context about the problem here

**Comment by hiddify** [comment]
This is the link that is end with /multi?

**Comment by hiddify** [comment]
fixed
