### ISSUE TITLE
تاریخ ریست ترافیک

### ISSUE THREAD

**Issue by akv79** [hiddify/hiddify-config#192]
سلام خسته نباشید
لطفا تو بخش مدیریت کاربران یه بخش تعیین تاریخ ریست حجم رو هم اضافه کنید.
الان تاریخ ریست حجم بر مبنای تاریخ ساخت یوزر محاسبه میشه
در صورتی که اگه فرضا یه یوزر اکانتش رو بیست روز بعد از تاریخ انقضا اکانت تمدید کنه کماکان حجمش سر همون سررسید قبلی ریست میشه و قابل تنظیم نیست تا همزمان با تاریخ انقضای اکانت ریست بشه

**Comment by arman2012** [comment]
تیک ماهیانه رو بزن

**Comment by akv79** [comment]
تیک ماهانه رو که زدم
گفتم که مشکلی که هست سر رسید ماهانش بر اساس تاریخ ساخت اون اکانت حساب میشه
اینجوری فرض کن که اکانت من یک ماهست و روز یکم ماه ساخته شده این ماه هیچ مشکلی وجود نداره ولی ماه بعد من دهم ماه اکانتم رو تمدید میکنم مشکلی که هست اینه که با اینکه تاریخ انقضای اکانت من میشه دهم ماه بعد ولی هنوز حجم اکانت همون یکم ماه ریست میشه

**Comment by hiddify** [comment]
خوب تاریخ ریست قبلی را عوض کن
30 روز بعد از تاریخ ریست قبلی، ریست میشه

**Comment by hiddify** [comment]
اپشنشو اضافه میکنیم

**Comment by hiddify** [comment]
done
