### ISSUE TITLE
Other TLS ports don't work except 443 پورتهای تی ال اس غیر از ۴۴۳ هیچ کدوم وصل نمیشه

### ISSUE THREAD

**Issue by R30na** [hiddify/hiddify-config#193]
i have added other ports to TLS settings separated by comma. But none of them works except 443. 
من پورتهای دیگه ای توی تنظیمات تی ال اس وارد کردم ولی هیچ کدوم غیر از ۴۴۳ کار نمیکنن.

**Comment by robin98** [comment]
تصور می کنم توسعه این بخش تکمیل نشده.
در حال حاضر برای تعریف پورت هایی بجز 443، ترفندی که باید بزنید این هست که اول پورت های دلخواه، آخر سر 443 رو بنویسید.
اما انجام این کار منجر به هیچ عکس العمل خاصی نمیشه و سرویس همچنان فقط روی 443 باقی میمونه.
من خودم دستی و از توی کنسول SSH با ابزار ufw فایروال پورت هارو کنترل می کنم و تیک فایروال خود هایدیفای رو غیرفعال کردم.

اگه فنی تر باشید و  کار با reverse proxy و تغییر تنظیمات nginx رو بلد باشید شاید بتونید دستی این پورت هارو پیاده سازی کنید. من چون شخصا اصرار و عجله ای برای استفاده از پورت های بجز 443 نداشتم در نتیجه هنوز دنبالش نرفتم ولی اگه شما نیاز دارید راه حلش سه چیزه:

1. منتظر بمونید هایدیفای این ساپورت رو اضافه کنه
2. در مورد reverse proxy و پیاده سازیش توی nginx تحقیق کنید و بعدش فایل سرویس nginx که همراه با هایدیفای نصب شده رو خودتون دستی کانفیگ کنید
3. اگه از CDN شرکت CF استفاده می کنید، احتمال داره از طریق قوانینی که از قسمت `Rules > Origin Rules` قابل تعریفه به این خواسته برسید؛ یعنی از نظر تئوری که از اونجا هم باید قابل انجام باشه. همچنین با کمک این قسمت میشه از هر پورت دلخواه دیگه ای(بعلاوه اون 13 پورت پشفرض خود CF) برای ارتباط با Origin Server یا همون سرور اصلی استفاده کرد، البته در اکانت free تعداد rule هایی که میشه تعریف کرد محدوده

**Comment by robin98** [comment]
تا اونجایی که من متوجه شدم، هر دفعه که سرویس میاد بالا، از اون فایلی که در انتهاش `.template` داره یه کپی جدید میسازه. در اصل شما اول برید مقادیر داخل فایل template رو تغییر بدید و بعدش یبار ریستارت کنید تا نمونه جدید با مقادیر شما ساخته بشه و هر دفعه هم که سرور ریستارت میشه همین تنظیمات ثابت میمونه.
هر چند در کل فراموش نکنید قبل از تغییرش از فایل یه کپی به عنوان بکاپ بسازید که بعدا بتونید ریستورش کنید.

**Comment by Fl2ankenStein** [comment]
@R30na عزیز 
بی زحمت این issue رو reopen کن تا از پنل هم رسیدگی شه
