### ISSUE TITLE
تی ال اس کلود فلر و پروتکل تی سی پی

### ISSUE THREAD

**Issue by Obeid1375** [hiddify/hiddify-config#195]
داخل کلود فلر باید حالت tls رو روی چی قرار بدیم ؟
کانفیگ های تی سی پی چرا وصل نمیشن و ارور tls handshake و eof میدن ؟

**Comment by robin98** [comment]
روی full یا full strict
شبکه CDN از ارتباط مستقیم tcp پشتیبانی نمی کنه
در نتیجه فقط آپشن های ws یا grpc قابلیت استفاده از پشت cdn رو دارند و برای tcp باید از ارتباط مستقیم با آی پی اصلی خود سرور یا direct استفاده بشه

**Comment by Obeid1375** [comment]
> روی full یا full strict شبکه CDN از ارتباط مستقیم tcp پشتیبانی نمی کنه در نتیجه فقط آپشن های ws یا grpc قابلیت استفاده از پشت cdn رو دارند و برای tcp باید از ارتباط مستقیم با آی پی اصلی خود سرور یا direct استفاده بشه

نه اینو میدونم که با cdn نمیشه tcp وصل شد اما دایرکت باید بشه که نمبشه. فقط xtls دایرکت با tcp وصل میشه. 

کلا اینا دوتا سوال از هم جدا بود😁

**Comment by robin98** [comment]
آره متوجه شدم، منم اون full و ... رو از داخل تنظیمات خود CF بهتون گفتم.
در مورد اتصال direct هم احتمال داره یا آی پی به شیوه ای توسط فیلترینگ محدود یا بلاک شده باشه یا پروتکل هارو اختلال انداختن و خیلی احتمال های دیگه.
برای من که مشکلی نداشت روی اتصال direct هر چند بازم اتصال از راه CDN رو ترجیح میدم چون از اتصال دایرکت کیفیت بهتری داره به شرطی که آی پی سالم بتونید گیر بیارید.
اگه بازم فکر می کنید مشکل اتصال direct از سمت خودتونه میتونید سرور رو ریست کنید و روی os خام و جدید دوباره کانفیگ کنید. فایروال خود پنل هم غیرفعال کنید و با ابزار ufw پورت های مورد نیاز رو توی خود سرور باز کنید که مثلا میشه 443/tcp و 80/tcp و 22/tcp و پورت های دیگری که خودتون نیاز دارید.

**Comment by Obeid1375** [comment]
> 

با یه پنل دیگه تست کردم tcp کار میکنه. من فقط مشکلم tcp هستش با بقیه مشکلی ندارم.فک کنم مشکل از zerossl باشه.

**Comment by hiddify** [comment]
بای دیفالت شد letsencrypt ولی رو قدیمیها اجرا نمیشه روی دامنه های جدید فقط
