### ISSUE TITLE
Issues connecting with MCI مشکل اتصال در همراه اول 

### ISSUE THREAD

**Issue by R30na** [hiddify/hiddify-config#197]
من دوتا سرور دارم یکی پنل XUI و یکی هایدیفای. دقیقا با تنظیمات مشابه vless+grps+tls و پورت یکسان
توی هایدیفای همراه اول وصل نمیشه و توی XUI هم ایرانسل وصل نمیشه. 
به نظرتون دلیلش چی میتونه باشه؟

**Comment by robin98** [comment]
پشت CDN هستن یا مستقیم وصل می شید؟ به نظر من این مشکل به محدود شدن آی پی بر می گرده و به نظر میرسه مشکل شما هم همین باشه. راه حلش استفاده از آی پی سالم CDN برای وصل شدن از اپراتورهای داخل ایرانه، یا استفاده از تونل و relay ایران.

**Comment by hiddify** [comment]
شما روی همون سروری که میگید هیدیفای کانکت نمیشه، x-ui نصب کنید و لینکی که کار میکنه را برای ما بفرستید (البته با مخفی کردن آی پی) 
اگر چنین جیزی باشه موضوع را راحت میشه حل کرد

**Comment by Fl2ankenStein** [comment]
@R30na
 همراه اول با تغییر آدرس  رفع میشه

**Comment by dfjavan** [comment]
سلام قبل از هرچیز تشکر فراوان، مال من نصب شد و با ایرانسل و نت مخابرات به خوبی کار می کنه ولی با شاتل و همراه اول نه. ضمن اینکه تو شاتل و همراه ای پی سرورم رو بلاک کردن ولی پینگ دارم، می خام ببینم راهی داره مثل v2ray که به cdn متصل می کردیم و به codepen.io لینک می دادیم ، ایا هایدفای این قابلیت رو داره؟؟

**Comment by rahmatzadmohammad** [comment]
دوست عزیز مشکل همراه اول هنوز برطرف نشده چکار باید انجام داد

**Comment by botgame96** [comment]
برای اینکه همراه اول کار کنه براتون باید یک تانل از یک سرور ایرانی که آی پی کثیف نباشه بزنید به سرور اصلیتون و بعدش در قسمت پنل دامینی که می خواید وارد کنید از بات باشسیز استفاده کنید در اونجا بات به شما یک سری آی پی میده که برای کلاد فلر هست حتما از لیستی که می بینید آی پی که جلوش نوشته MCI رو انتخاب کنید مشکل همراه اولتون حل میشه :) موفق و پیروز باشید

**Comment by hiddify** [comment]
> من دوتا سرور دارم یکی پنل XUI و یکی هایدیفای. دقیقا با تنظیمات مشابه vless+grps+tls و پورت یکسان توی هایدیفای همراه اول وصل نمیشه و توی XUI هم ایرانسل وصل نمیشه. به نظرتون دلیلش چی میتونه باشه؟

لینک تنظیمات هر دو رپ میفرستید چک کنیم ببینیم تفاوت چیه؟

**Comment by Fl2ankenStein** [comment]
vless://[uid]@[domain]:8443?type=tcp&security=xtls&flow=xtls-rprx-direct#[config_name]
in config hame az ye server x-ui ke  ba hamaye operatorha va os ha bekhubi kar mikone 
hich chiz khasi nadare x-ui ba file cert va key man fek konam noone ip ro rangesh fargh mikone

**Comment by dfjavan** [comment]
سلام هرچی ای پ تمیز هم که پیدا کنیم چند روز بعد از نصب نرم افزار ، اون ای پی رو بلاک می کنن، نت مخابرات خوب بود که اونم مثل شاتل همه رو داره می بنده 😕😕😕

**Comment by hiddify** [comment]
میتونه مشکل از فینگرپرینت باشه؟ مال ما fp داره تو لینک

**Comment by Fl2ankenStein** [comment]
ip clean haro khaheshan ba domain vared konid na mostaghim

**Comment by dfjavan** [comment]
@Fl2ankenStein  داداش گلم از روز اولی که راه انداختم رو  کلوفلر ساب دامین بستم ولی باز هم شاتل و همراه اول بعد از سه چهار روز می بندن
اگه راه حلی داریدبفرمایید
ممنون

**Comment by Fl2ankenStein** [comment]
@dfjavan 10ta ip ro (khode IPihaye tamirz ro manzurame)hamashun ro faghat ba yedune subdomain add konid in amal ro ye bar tik porxy test konid nashod agar bedune proxy

**Comment by samankh4** [comment]
> fp

میشه یکم راجب این ip سالما توضیح بدین

**Comment by MONDAYAsia** [comment]
> پشت CDN هستن یا مستقیم وصل می شید؟ به نظر من این مشکل به محدود شدن آی پی بر می گرده و به نظر میرسه مشکل شما هم همین باشه. راه حلش استفاده از آی پی سالم CDN برای وصل شدن از اپراتورهای داخل ایرانه، یا استفاده از تونل و relay ایران.



> شما روی همون سروری که میگید هیدیفای کانکت نمیشه، x-ui نصب کنید و لینکی که کار میکنه را برای ما بفرستید (البته با مخفی کردن آی پی) اگر چنین جیزی باشه موضوع را راحت میشه حل کرد

میشه به منم بگید CDN چی هستش
