### ISSUE TITLE
عدم کارکرد grpc

### ISSUE THREAD

**Issue by sh4msi** [hiddify/hiddify-config#198]
سلام
من نمیتونم از طریق grpc وصل شدم 
ایا باید تنظیمات خاصی رو پنل یا سرور یا .. انجام شه؟

**Comment by robin98** [comment]
اگه سرور پشت cdn هست و میخوایید با وجود cdn  ارتباط برقرار بشه، باید در تنظیمات کلادفلر بخش Network، گزینه grpc هم فعال باشه.

**Comment by sh4msi** [comment]
> اگه سرور پشت cdn هست و میخوایید با وجود cdn ارتباط برقرار بشه، باید در تنظیمات کلادفلر بخش Network، گزینه grpc هم فعال باشه.

بله سرور پشت cdn قرار داره و در کلادفلر grpc فعال هست ولی هیچ ارتباطی برقرار نمیشه

**Comment by hatinati2** [comment]
سلام 
برای کار کردن grpc  از نرم افزار Matsuri در آندروید استفاده کنید

**Comment by hiddify** [comment]
از چه برنامه ای وصل نمیشه؟ از همه اوپراتورها این شکلیه؟

**Comment by sh4msi** [comment]
با اپ v2ray در اندروید و ویندوز
با اپ clash در ویندوز
با مبین نت و ایرانسل تست کردم ادرس های که از cdn کلودفیلر رد میشن هیچ کدوم جواب برنمیگردونن

**Comment by hiddify** [comment]
ای پی تمیز استفاده کردید؟ مثل ای پی های باشیز؟

**Comment by raminrez** [comment]
داخل پنل کلادفلر٬ مدیریت دامنه٬ network. حتما قابلیتش رو فعال کن

<img width="1393" alt="Screenshot 2023-02-23 at 2 50 01 AM" src="https://user-images.githubusercontent.com/7345325/220785817-7074ea98-9ba6-4dd1-83fc-32fe652e16d3.png">

**Comment by raminrez** [comment]
بازم ممکنه مشکل از آی‌پی باشه که انتخاب کردی
من با یکسری از آي‌پی ها این مشکلات رو دارم

**Comment by raminrez** [comment]
از این مورد اطلاع ندارم
ولی این دامین رو بزار بجای آیپی (اون جایی که آی‌پی تمیز میدی) ببین برات جواب میده.
cf.sudoer.net
ip.isegaro.click

**Comment by sh4msi** [comment]
در کلادفلر grpc فعال هست و ip ها هم از اسکریپت مرتضی گرفته میشن و تمیز هستن
و چون حدودا از 10-11 دامین و ip کلودفلر استفاده میکنم که مدام هم دارم بروزشون میکنم پس احتمالا بخاطر این موضوع نباشه
و از طرفی هم این رو میدونم که یه ارتباطی به کلادفلر داره چون من دامین دیگه ی دارم که داره همروش استفاده میکنه که برا اون جواب میده
ولی خوب نباید سرویس های داخلی خیلی دل بست هر لحظه احتمال داره ..


------

> از این مورد اطلاع ندارم ولی این دامین رو بزار بجای آیپی (اون جایی که آی‌پی تمیز میدی) ببین برات جواب میده. cf.sudoer.net ip.isegaro.click

هر دو مورد رو تست کردم و جواب ندادن 
![image](https://user-images.githubusercontent.com/6229984/220800868-1f12b0c0-4e34-4f38-addd-59ce519ce3da.png)

**Comment by sh4msi** [comment]
ایا راهکاری برای این موضوع وجود دارد؟
