### ISSUE TITLE
Bulk users

### ISSUE THREAD

**Issue by Mobinoo1383** [hiddify/hiddify-config#200]
سلام 
چطور میتونم تعداد زیادی یوزر رو یک جا بسازم

**Comment by arman2012** [comment]
نمیتونی

**Comment by hiddify** [comment]
میتونی یه نمونه فایل کانفیگ بکاپ بگیری
بعدی با فرمتی که داره یوزر ادد کنی و ریستور را بزنی

**Comment by Mobinoo1383** [comment]
ممنونم 
میشه یکم دقیق تر و پله به پله توضیح بدی؟
