### ISSUE TITLE
دامین فرانتینگ

### ISSUE THREAD

**Issue by arman2012** [hiddify/hiddify-config#203]
سلام و درود 
دامین فرانتینگ دیگه اون عملکرد سابقش رو داخل کلودفلیر نداره قبول ولی خواهشا حذفش نکنید چون داخل ابر آروان خوب داره جواب میده حداقل اینه که دیر تر فیلتر میشه خیلی 
من از وقتی با این روش کانفیگ میدم دو ماهه دامین عوض نکردم

**Comment by hiddify** [comment]
حذف نشد ولی توضیحات اضافه شد تو کلودفلر جواب نمی‌دهد
