### ISSUE TITLE
غیب شدن دکمه همه از پنل کاربران

### ISSUE THREAD

**Issue by onyxtm** [hiddify/hiddify-config#204]
آقا خسته نباشید، من میخوام کاربرانم از طریق پنل بتونن به همه کانفیگ های relay, cdn و ... دسترسی داشته باشن ولی تو این آپدیت آخر این آپشنو غیر فعال کردید مثل اینکه!

**Comment by hiddify** [comment]
الان توی منوی دامنه میتونید تعریف کنید لینک های هر دامنه به چه دامنه هایی دسترسی داشته باشن
