### ISSUE TITLE
قطع شدن کانکشن هایی که ۱ ماه کار میکرد

### ISSUE THREAD

**Issue by parsaahaniii** [hiddify/hiddify-config#206]
سلام
ممنونم از زحماتتون
کانشکن های CDN من ۱ ماهی بدون هیچ مشکلی روی اپراتور های مختلف داشت کار میکرد اما از دیروز عصر بدون هیچ تغییر و آپدیتی از سمت من همه کانکشن های CDN ام قطع شده و کلاینت ها ارور tls handshake داره اما پراکسی تلگرام هنوز بدون مشکل کار میکنه.
میخواستم ببینم راهی هست که بشه مطمئن شد دامین من یا آیپی من فیلتر شده یا بلک لیست شده یا یه همچین چیزی؟
چون پراکسی تلگرام با آیپی هست و مشکلی نداره میشه مطمئن بود که آیپی سرور مشکلی نداره؟
آیا آپدیت کردن به ورژن جدید کمکی میکنه؟(ورژن من مربوط به ۱ ماه پیش هست)
اطلاعات بیشتر: وقتی با برازر به آدرس ساب‌دامینی میرم که باهاش وی پی ان داشتم، ارور ۵۰۴ آروان میگیرم

**Comment by hiddify** [comment]
احتمالا ای پی cdn مشکل داره
از فورس ای پی استفاده کنید
