### ISSUE TITLE
اکسز نداشتن تعداد خوبی از پاپ‌سایت های آروان به سرور

### ISSUE THREAD

**Issue by parsaahaniii** [hiddify/hiddify-config#212]
سلام خسته نباشید.
من آپدیت کردم و مثل بعضی از یوزر های دیگه از آروان ۵۰۴ یا ۵۰۲ میگیرم و بعد از صحبت با پشتیبانی بهم گفتن که تعداد خوبی از رنج آیپی های آروان به سرورم دسترسی نداره.
میخواستم ببینم در اسکریپت رنج آیپی های آروان white list میشه؟
چه جوری میتونم از وایت لیست شدنشون روی سرورم مطمئن بشم؟

**Comment by parsaahaniii** [comment]
البته طبق مشورتی که با یکی از دوستان داشتم مشکل احتمالا ارتباط CDN آروان با سرور من از سمت زیرساخت هست.

**Comment by hiddify** [comment]
پس حل شد
