### ISSUE TITLE
Server doesn't work after update

### ISSUE THREAD

**Issue by alexivanelli** [hiddify/hiddify-config#22]
Hi @hiddify,

First I want to thank you for this great project. This really helps people.

After I updated hiddify this morning, almost all protocols got shut down + I cannot access the admin and user panel through domain name, but they are accessible by IP address. I even tried fresh install in a new server with a new domain but It didn't help and got the same problem again.

**Comment by parsaahaniii** [comment]
Same.
Last night I I had this experience.
After some commits I have certification error.
Maybe this [commit](https://github.com/hiddify/hiddify-config/commit/4af588ebd9ed9f8d3dcba337c9bd5f0f9aa31374) fix that.

**Comment by aag0116** [comment]
Same.

**Comment by hiddify** [comment]
sorry for the issue.
I forgot to commit one files.
This is why it was working in my server not yours

Fixed
