### ISSUE TITLE
سرعت بسیار کم  سرور ایران

### ISSUE THREAD

**Issue by sh4msi** [hiddify/hiddify-config#220]
سلام

از طریق هم روش و آروان و در چند دیتا سنتر مختلف سرویس ایجاد کردم و بصورت relay به پنل اضافه کردم ولی متاسفانه سرعت  به شدت کم هست
ایا نکته خاصی وجود داره که من رعایت نمیکنم؟ 
آیا مسئاله از طرف پنل هست یا سرویس دهنده ای ایران یا .. ؟

(این موضوع از همون لحظه اول به همین شکل هست)

**Comment by robin98** [comment]
سلام.
فکر می کنم از طرف ارائه دهنده ایران محدودیت پهنای باند گذاشته باشند و از سمت شما یا توسعه دهندگان هیدیفای کار زیادی ساخته نیست.
مگر  اینکه شانسی یک ارائه دهنده خاص پیدا بشه که این محدودیت رو کمتر داشته باشه.
یکی از ایده هایی که الان دارم و از بقیه بیشتر عملی به نظر میرسه، استفاده از یک سرور رابط دیگه در مناطق دبی، ترکیه یا دیگر کشورهای همسایه ... قبل از پاس دادن نهایی به سمت سرور خارجتون هست.

**Comment by lumanjre** [comment]
اگر از تنظیمات سرور خود مطمین هستین مشکل از سرور ایران میتونه باشه
