### ISSUE TITLE
اجازه دادن به کاربران برای مشاهده باقی relay ها

### ISSUE THREAD

**Issue by DanielNoohi** [hiddify/hiddify-config#221]
بزارید کاربر ها بتونن باقی relay های خودشون رو هم ببینن تو پنلشون که وقتی یکی از کار افتاد اتوماتیک ریلی های جدید که توسط ادمین بهشون اختصاص داده شده رو اتوماتیک ببینن

**Comment by hiddify** [comment]
اینجوری هست الان
کافیه توی تنظیمات دامنه بزنید کدوم ریلی دیده بشه
