### ISSUE TITLE
عدم امکان حذف کاربرو یا بروزرسانی کارکرد کاربر

### ISSUE THREAD

**Issue by R30na** [hiddify/hiddify-config#224]
![image](https://user-images.githubusercontent.com/13730082/221365512-276861a5-9504-48c7-a306-67680787e96a.png)

**Comment by arman2012** [comment]
تایید میشه بعد دو سه بار تست مجدد و ریلود درست میشه ولی خب هست

**Comment by hiddify** [comment]
به نظرم پنل شما روی نسخه v6 هست نباید اتومات به این نسخه آپدیت میشدید

git checkout main
را بزنید
