### ISSUE TITLE
مشکل پروتکل های TCP روی حالت direct

### ISSUE THREAD

**Issue by Obeid1375** [hiddify/hiddify-config#227]
سلام و خسته نبایشد. متاسفانه پروتکل های TCP جواب نمیدن و این ارور رو میدن.

2023/02/25 20:17:50 [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to decode response header > proxy/vless/encoding: failed to read response version > EOF
2023/02/25 20:17:50 Url test failed: Get "http://cp.cloudflare.com/": io: read/write on closed pipe
[[VLESS] tls_tcp_direct_vless_de.gldvp.fun] test error: Get "http://cp.cloudflare.com/": io: read/write on closed pipe

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا
