### ISSUE TITLE
نصب در شبکه NAT

### ISSUE THREAD

**Issue by ali-sorury** [hiddify/hiddify-config#231]
1. وقتی توی شبکه ای **NAT** هست نصب میشه Public ip  شبکه رو به عنوان **Permanent Admin link** میشناسه و با **Local ip**  نمیشه بهش وصل شد 
2. آیا قابلیت Uninstall داره ؟
3. در کل خیلی خوبه ممنون ازتون ولی مشکل های بالا اگه حل بشه خیلی خوبه

**Comment by hiddify** [comment]
به جای اون ای پی لوکال بذارید
بله
