### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ahaddiba** [hiddify/hiddify-config#232]
سلام من زدم پنل آپدیت شه داره ارور Internal server Error میده چی کار کنم ؟

**Comment by amin30000** [comment]
اقا من هم الان آپدیت روزدم دچار همین ارور شدم

**Comment by amin30000** [comment]
کد اپدیت دستی رو کسی نداره به صورت دستی آپدیت کنم ببینم درست میشه ؟

**Comment by amirict** [comment]
درود بر همگی
interal server error 
چکار کنیم ؟؟؟؟

**Comment by hiddify** [comment]
لطفا از bash
bash update.sh
را بزنید
باید حل شده باشه

**Comment by ahaddiba** [comment]
یعنی ssh بزنم بنویسم bash update.sh ?

**Comment by amirict** [comment]
bash: update.sh: No such file or directory

**Comment by amin30000** [comment]
> لطفا از bash bash update.sh را بزنید باید حل شده باشه

درست نشد

**Comment by amirict** [comment]
cd /opt/hiddify-config
sudo bash update.sh

با این روش آپدیت دستی بکنید. درست شد.

**Comment by amin30000** [comment]
> cd /opt/hiddify-config
> sudo bash update.sh

داداش دمت گرم دنبال همین کد بودم 
مال من هم درست شد
