### ISSUE TITLE
کار نکردن با نت ایرانسل

### ISSUE THREAD

**Issue by MehranAhmadi0** [hiddify/hiddify-config#241]
سلام و خسته نباشید
هایدیفای واقعا عالیه ولی متاسفانه از وقتی آپدیت شده فقط با نت رایتل برام کار میکنه و ایرانسل و همراه اول و وای فای اصلا کار نمیکنه و نمیدونم مشکلش چیه
روی چند تا سرور دیگه هم امتحان کردم با چند تا دامنه مختلف که با کلودفلر ثبتشون میکردم ولی بازم جواب نداد.
لطفا راهنماییم کنین
ممنون
راستی سرورم رو از هتزنر میگیرم

**Comment by MehranAhmadi0** [comment]
البته همون کانفینگ به محظ وصل شدن به نت رایتل خیلی عالی و با سرعت وحشتناکی کار میکنه
اما متاسفانه فقط با رایتل اینجوریه

**Comment by danamjb** [comment]
ایرانسل مشکلی نداره، از دامین فرانتینگ استفاده کنید نه مستقیم.

**Comment by MehranAhmadi0** [comment]
نه برا من بجز رایتل هیچکدوم کار نمیکنه
دامین فرانتینگ از کجا پیداکنم؟

**Comment by lumanjre** [comment]
دوست عزیز از CDN استفاده کن  و آیپی های تمیز کلادفلر پیدا کن
