### ISSUE TITLE
وصل نشدن نت همراه

### ISSUE THREAD

**Issue by Mani9011** [hiddify/hiddify-config#246]
سلام ببخشید من برام یه مشکلی پیش اومده اینکه کاربرام بهم زنگ میزنن میگن دیگه وصل نمیشه وی پی ان رو نت همراهشون

**Comment by ahaddiba** [comment]
همراه اول روی WS هیچ مشکلی نداره ! من هر روز دارم استفاده میکنم ! CDN_WS

**Comment by ahaddiba** [comment]
دامین فرانتینگ ! 
vless://692f497e-9d8a-464d-95a1-e58af5f4d35b@codepen.io:443?security=tls&sni=DOMAIN&type=ws&path=/96WcstDSApE0dH0tZMfakck/vlessws&host=DOMAIN&encryption=none&fp=chrome&headerType=None#tls_WS_CDN_DOMAIN

**Comment by hiddify** [comment]
یکی از بچه ها میگفت utls را گذاشته روی android حل شده 
یکی دیگه میگفت utls را حذف کرده حل شده

چک کنید ببینید این حل میکنه واسه شما؟

**Comment by lumanjre** [comment]
[اینا را بخونید](https://github.com/hiddify/hiddify-config/wiki/%DA%86%DA%AF%D9%88%D9%86%DA%AF%DB%8C-%DB%8C%D8%A7%D9%81%D8%AA%D9%86-%D8%A2%DB%8C%D9%BE%DB%8C-%D8%AA%D9%85%DB%8C%D8%B2-%DA%A9%D9%84%D8%A7%D8%AF%D9%81%D9%84%D8%B1)
