### ISSUE TITLE
برای همراه اول کار نمیکنه 

### ISSUE THREAD

**Issue by ho3ein-yazdan** [hiddify/hiddify-config#251]
واقعا دمتون گرئم خیلی زحمت کشیدید و بسیار عالیه 
فقط برای همراه اول وصل نمیشه 
من خودم با کانکشن grpc برای همراه اول با استفاده میکردم با پورت های کلودفلر و در کلودفلر هم تیک پروکسی خاموش بود و در کانفینگ در قسمت ادرس ادرس یک سری سایت ها مانند :
 researchgate.net
fitanalytics.com
developers.criteo.com
ilovepdf.com
را جایگزین دامنه میکردم و در قسمت sni هم ساب دامنه خودم رو وارد میکردم و روی همراه اول وصل میشد ولی چند روز پیش دیگه این روش برای هماره اول کار نکرد و یا سرعتش خیلی کم شد نمیدونم شاید این سایت ها رو هم ای پی هاش فیلتر شده و شناسایی شده و باید سایت های دیگه جایگزین کرد که وصل باشن ولی من هر ای پی که به کلودفر وصل هستن رو زدم برای همراه اول جواب نداد توی این چند روز گذشته ولی تا هفته قبل با همون روش grpc اوکی بود 
تیک پروکسی هم روشن کردم فایده نداشت 
 اگر امکان داره برای همراه اول هم درست کنید این پنل رو با این کار هایی که من قبلا انجام دادم شاید بشه چون شما حرفه ای تر هستید حتما می تونید یک راه حل پیدا کنید برای این موضوع ممنون میشم پاسخ بدید
 با تشکر از همه زحمت هایی که کشیدید برای این پنل واقعا عالیه

**Comment by ahaddiba** [comment]
سلام من روی WS توی همراه اول هیچ مشکلی ندارم ! هم تروجان هم vless

**Comment by ho3ein-yazdan** [comment]
> سلام من روی WS توی همراه اول هیچ مشکلی ندارم ! هم تروجان هم vless

از همین پنل استفاده می کنی یا x-ui با چه پورت هایی وصل میشی که روی همراه اول جواب میده ؟

**Comment by ahaddiba** [comment]
> 
از همین پنل پورت ۴۴۳ ! اصلا رو همراه اول من مشکل ندارم

**Comment by ho3ein-yazdan** [comment]
> > 
> 
> از همین پنل پورت ۴۴۳ ! اصلا رو همراه اول من مشکل ندارم

https://hn.yazdan.tk/RFgPHu3Lrih/e39e5382-eeca-4f21-a8e8-77b871113aaf/new
برای مثال این لینک یک کاربر 
توی بخش تمام کانفینگ ها هر کدوم رو میزنم برای همراه اول کار نمیکنه 
ایرانسل و رایتل و ... وصله و مشکلی نداره 
همراه اول وصل نمیشه

**Comment by ahaddiba** [comment]
> > > 
> > 
> > 
> > از همین پنل پورت ۴۴۳ ! اصلا رو همراه اول من مشکل ندارم
> 
> https://hn.yazdan.tk/RFgPHu3Lrih/e39e5382-eeca-4f21-a8e8-77b871113aaf/new برای مثال این لینک یک کاربر توی بخش تمام کانفینگ ها هر کدوم رو میزنم برای همراه اول کار نمیکنه ایرانسل و رایتل و ... وصله و مشکلی نداره همراه اول وصل نمیشه

داداش گلم ! بذار روی cdn و بعد با ردامین فرانتینگ بزن codepen.io ! اینا که شما دادی همش direct !

**Comment by ho3ein-yazdan** [comment]
> codepen.io
میخوام در قسمت Domain بخش حالت cdn  رو انتخاب کنم ولی یک خطا میده که : در حالت CDN، IP=ip server man باید با  ip=hamon ip ro inja ham neveshte شما متفاوت باشد.
برای رفع این خطا چه کار کنم ؟
