### ISSUE TITLE
شما روی همون سروری که میگید هیدیفای کانکت نمیشه، x-ui نصب کنید و لینکی که کار میکنه را برای ما بفرستید (البته با مخفی کردن آی پی)

### ISSUE THREAD

**Issue by ho3ein-yazdan** [hiddify/hiddify-config#252]
شما روی همون سروری که میگید هیدیفای کانکت نمیشه، x-ui نصب کنید و لینکی که کار میکنه را برای ما بفرستید (البته با مخفی کردن آی پی) 
اگر چنین جیزی باشه موضوع را راحت میشه حل کرد

_Originally posted by @hiddify in https://github.com/hiddify/hiddify-config/issues/197#issuecomment-1440463168_
همزمان این پنل و x-ui رو روی یک سرور نصب کنیم مشکلی پیش نمیاد ؟

**Comment by ho3ein-yazdan** [comment]
> ```
>           شما روی همون سروری که میگید هیدیفای کانکت نمیشه، x-ui نصب کنید و لینکی که کار میکنه را برای ما بفرستید (البته با مخفی کردن آی پی) 
> ```
> 
> اگر چنین جیزی باشه موضوع را راحت میشه حل کرد
> 
> _Originally posted by @hiddify in [#197 (comment)](https://github.com/hiddify/hiddify-config/issues/197#issuecomment-1440463168)_ همزمان این پنل و x-ui رو روی یک سرور نصب کنیم مشکلی پیش نمیاد ؟

https://hn.yazdan.tk/RFgPHu3Lrih/e39e5382-eeca-4f21-a8e8-77b871113aaf/new
این پنل کاربر که کانکشن هایی که در بخش تمام کانفینگ ها هست هیچ کدوم روی همراه اول کار نمیکنه

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا
