### ISSUE TITLE
جلوگیری از آپدیت خودکار

### ISSUE THREAD

**Issue by mozilla-firefox** [hiddify/hiddify-config#254]
سلام
من آپدیت خودکار رو روی سرورم غیرفعال کرده بودم، بعد از اینکه آپدیت جدید آمد نمیدونم چرا خودکار آپدیت شد
البته یبار تنظیمات رو تغییر دادم و Apply زدم، شاید بخاطر اون بوده
ولی در هر صورت مطمئن هستم روی Update System نزدم
لطفا بررسی کنید اگر Apply کردن تنظیمات جدید باعث میشه پنل هم آپدیت بشه، تغییرش بدید
با تشکر

**Comment by hiddify** [comment]
اگه سنترال پنل را ببینید سعی شده به این شکل نباشه😉
تستاش اوکی بشه روی‌پنل اضافه میشه

On Tuesday, February 28, 2023,
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by hiddify** [comment]
انجام شد
