### ISSUE TITLE
کار نکردن پراکسی تلگرام روی ایرانسل

### ISSUE THREAD

**Issue by mahdipsd** [hiddify/hiddify-config#255]
سلام
پراکسی تلگرام رو همراه اول خوبه ولی رو ایرانسل کار نمی کنه

**Comment by lymanjre** [comment]
دوستان پروکسی تلگرام روی پروتکل MTProto کار میکنه که متاسفانه ضعف هایی داره. تا زمانیکه تلگرام آپدیت نکنه به Socks5 عملا ممکنه جاهایی این جواب نده
