### ISSUE TITLE
TypeError: 'ip' is an invalid keyword argument for Child

### ISSUE THREAD

**Issue by ramindoroozeh** [hiddify/hiddify-config#259]
TypeError: 'ip' is an invalid keyword argument for Child
@ Line 16 environment:
  =d

GITHUB_USER=hiddify
GITHUB_REPOSITORY=hiddify-config
GITHUB_BRANCH_OR_TAG=main
FIRST_SETUP=
DB_VERSION=
TELEGRAM_USER_SECRET=
BASE_PROXY_PATH=
TELEGRAM_LIB=
ADMIN_SECRET=
ENABLE_V2RAY=
ENABLE_SS=
SS_FAKE_TLS_DOMAIN=
DECOY_DOMAIN=
SHARED_SECRET=
ENABLE_TELEGRAM=
TELEGRAM_FAKE_TLS_DOMAIN=
TELEGRAM_AD_TAG=
ENABLE_SHADOW_TLS=
SHADOWTLS_FAKEDOMAIN=
FAKE_CDN_DOMAIN=
ENABLE_SSR=
SSR_FAKEDOMAIN=
ENABLE_VMESS=
ENABLE_MONITORING=false
ENABLE_FIREWALL=
ENABLE_NETDATA=
ENABLE_HTTP_PROXY=
ALLOW_ALL_SNI_TO_USE_PROXY=
ENABLE_AUTO_UPDATE=
ENABLE_TROJAN_GO=false
ENABLE_SPEED_TEST=
BLOCK_IR_SITES=
ONLY_IPV4=
SERVER_IP=
SERVER_IPv6=
MAIN_DOMAIN=
USER_SECRET=
ERROR!!!! There is an error in the installation of python panel. Exit....

**Comment by hiddify** [comment]
fixed
