### ISSUE TITLE
Arvan block my ip!

### ISSUE THREAD

**Issue by imanbahmani** [hiddify/hiddify-config#26]
Unfortunately, until we install the script, everything fails!

What service site is the best solution to use a domain(for cdn and servername)?
Because Arvancloud seems to understand immediately, especially when you turn on the CDN!
I am very confused and I need help

**Comment by hiddify** [comment]
ArvanCloud can see the content of the site since it terminates the SSL.
Maybe this is the reason. Therefore, maybe the best option is to enable no_cdn_domain config for user page.

**Comment by hiddify** [comment]
use fakeCDN method ;)
