### ISSUE TITLE
از دسترس خارج شدن پنل

### ISSUE THREAD

**Issue by ahaddiba** [hiddify/hiddify-config#261]
سلام 
من یه دامنه تو پنلم عوض کردم دیگه با لینک ادمین به پنلم دسترسی ندارم ! حتی با IP سیستم رو ریست هم کردم ! sudo /opt/hiddify-config/install.sh این رو هم زدم اینم لاگش : 
GITHUB_USER=hiddify
GITHUB_REPOSITORY=hiddify-config
GITHUB_BRANCH_OR_TAG=main
FIRST_SETUP=
DB_VERSION=
TELEGRAM_USER_SECRET=
BASE_PROXY_PATH=
TELEGRAM_LIB=
ADMIN_SECRET=
ENABLE_V2RAY=
ENABLE_SS=
SS_FAKE_TLS_DOMAIN=
DECOY_DOMAIN=
SHARED_SECRET=
ENABLE_TELEGRAM=
TELEGRAM_FAKE_TLS_DOMAIN=
TELEGRAM_AD_TAG=
ENABLE_SHADOW_TLS=
SHADOWTLS_FAKEDOMAIN=
FAKE_CDN_DOMAIN=
ENABLE_SSR=
SSR_FAKEDOMAIN=
ENABLE_VMESS=
ENABLE_MONITORING=false
ENABLE_FIREWALL=
ENABLE_NETDATA=
ENABLE_HTTP_PROXY=
ALLOW_ALL_SNI_TO_USE_PROXY=
ENABLE_AUTO_UPDATE=
ENABLE_TROJAN_GO=false
ENABLE_SPEED_TEST=
BLOCK_IR_SITES=
ONLY_IPV4=
SERVER_IP=my ip
SERVER_IPv6=2a01:4f9:c011:7b6b::1
MAIN_DOMAIN=
USER_SECRET=
ERROR!!!! There is an error in the installation of python panel. Exit....

خواهشا کمک !!!

**Comment by botgame96** [comment]
کلا پنلها پریدش :)

**Comment by botgame96** [comment]
نصب هم نمیشه کرد دیگه با دستورات کلا از دسترس خارج شده همه چیز

**Comment by parsatavafi** [comment]
با استفاده از دستورات زیر از وضعیت سرویس هاتون و اکتیو بودن Nginx مطمئن بشید. ممکنه خطا روی nginx داشته باشید :
```
cd /opt/hiddify-config
bash status.sh
```
اگر خطا داشتید قبل از هرکاری مجدد پنلتون رو اپدیت کنید و بعد فایل های لاگ رو بررسی کنید. ممکنه روی نسخه قدیمی باشید:
```
bash update.sh
```

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا
