### ISSUE TITLE
باز نشدن بعضی سایت‌های خارجی

### ISSUE THREAD

**Issue by raminsafaei** [hiddify/hiddify-config#262]
**Describe the bug**
بعضی از سایت‌های خارجی که هیچ ارتباطی به ایران ندارن روی کانفیگ‌های هایدیفای در کلش و سایر برنامه‌ها مثل v2rayN باز نمیشن. دقیق‌تر تست نکردم اما مشکل از ایپی سرور، کلادفلر و… نیست، با کانفیگ‌های x-ui این سایت‌ها بدون مشکل باز میشن. اینجا اما هیچ رسپانسی از ادرس مقصد به کلاینت نمیرسه که فکر میکنم مشکل از بلاک‌لیست و geoip در سمت سرور باشه
نمونه‌ای از این سایت‌ها:
https://mirror.xyz/
https://hairtamin.com/
https://medium.com/ (تصاویر لود نمیشن)
https://scirex.me/

**Comment by NikanMirH** [comment]
سایت و اپ تیک تاک هم وصل نمیشه و عجیبه واقعا!!
فرقی هم نمیکنه که با هایدیفای باشه یا نه
