### ISSUE TITLE
محل ذخیره سازی یوزرها در سرور

### ISSUE THREAD

**Issue by rezak222** [hiddify/hiddify-config#264]
سلام . من یه مشکلی پیش اومده بود واسم که به اشتباه از داخل پنل زدم آپدیت شه و بعد دیگه پنل بالا نیومد و ارور 502 Bad Gateway میده . لطفا راهنمایی کنید که فایل یوزرها کجا ذخیره میشه که از تو سرور سیوش کنم و دوباره پنل رو نصب کنم . ممنون

**Comment by parsatavafi** [comment]
من راجع به محل قرارگیری یوزرها چیزی نمیدونم اما گفتم شاید این که بدونید با نصب مجدد پنل از SSH اطلاعات کاربراتون (و سایر اطلاعات) دست نمیخوره و میتونید مجدد به پنل دسترسی پیدا کنید بتونه بهتون کمک کنه. دستورات زیر رو روی سرور اجرا کنید :

```
cd /opt/hiddify-config
bash install.sh
```
سپس دوباره تست کنید و ببینید مشکل Bad Gateway حل شده یا خیر ...

**Comment by hiddify** [comment]
محل قرارگیری فایل دیتابیس
`/opt/hiddify-config/hiddify-panel/hiddifypanel.db`

هست
