### ISSUE TITLE
Oracle Cloud Terraform version

### ISSUE THREAD

**Issue by behnamz1368** [hiddify/hiddify-config#265]
برای نصب پکیج در Oracle Cloud در مرحله اول در قسمت Terraform version این ارور وجود داره:
0.11.x is no longer supported.

در نهایت هم بعد از مرحله آخر و کلیک روی Create با پیام Internal error occurred مواجه میشم.

ممنون میشم راهنمایی بفرمایید.

**Comment by parsatavafi** [comment]
من فکر می کنم شما از روش [نصب در اوراکل کلود (چهار سرور رایگان)](https://github.com/hiddify/hiddify-config/wiki/Oracle-%D9%86%D8%B5%D8%A8-%D8%AE%DB%8C%D9%84%DB%8C-%D8%AE%DB%8C%D9%84%DB%8C-%D8%B3%D8%B1%DB%8C%D8%B9-%D8%AF%D8%B1-%D8%A7%D9%88%D8%B1%D8%A7%DA%A9%D9%84-%DA%A9%D9%84%D9%88%D8%AF) استفاده می کنید و احتمالا با توجه به تغییرات گسترده ای که توسعه دهنده روی Hiddify دارند هر روز میدهند این تغییرات روی اون روش اعمال نشده باشه ... فکر می کنم اگر به جای استفاده از روش نصب خیلی سریع (همون cloud init) یک VPS اوبونتو 22 به صورت ساده بسازید و از طریق اموزش [نصب سریع روی سرور اوبنتو](https://github.com/hiddify/hiddify-config/wiki/%D9%86%D8%B5%D8%A8-%D8%B3%D8%B1%DB%8C%D8%B9-%D8%AF%D8%B1-%D8%A7%D9%88%D8%A8%D9%88%D9%86%D8%AA%D9%88) مراحل نصب رو انجام بدید فکر می کنم مشکلتون حل بشه

**Comment by lymanjre** [comment]
از نصب ابونتو استفاده کنید
