### ISSUE TITLE
حالا باید دامنه را تنظیم کنیم. بر روی این لینک کلیک کنید تا نصب را نهایی

### ISSUE THREAD

**Issue by asd1asd00000** [hiddify/hiddify-config#266]
لینک برای تنظیم دامنه کار نمیکنه

حالا باید دامنه را تنظیم کنیم. بر روی [این لینک](https://github.com/hiddify/hiddify-config/wiki/%D8%B1%D8%A7%D9%87%D9%86%D9%85%D8%A7%DB%8C-%D8%AA%D9%86%D8%B8%DB%8C%D9%85-%D8%AF%D8%A7%D9%85%D9%86%D9%87-%D9%88-%D9%86%D9%87%D8%A7%DB%8C%DB%8C-%DA%A9%D8%B1%D8%AF%D9%86-%D9%86%D8%B5%D8%A8) کلیک کنید تا نصب را نهایی

**Comment by asd1asd00000** [comment]
عزیز لینک بالا تا چند هفته پیش به ثبت دامنه رایگان میرسید الان به صفحه نصب هایدیفای بر میگرده

**Comment by hiddify** [comment]
رفع شد
