### ISSUE TITLE
Relay ناامن

### ISSUE THREAD

**Issue by DanielNoohi** [hiddify/hiddify-config#268]
با فرض اینکه روش relay رو انتخاب کردیم قائدتا هر چی تعداد ریلی ها بیشتر باشه به نفع ماست جایگزین بیشتر داریم و شاید هر سروری داشته باشیم یه relay هایدیفای روش بالا بیاریم اما اگر سرور relay ناامن باشه چی، آیا میتونه اون relay ناامن باعث مشکل بشه؟ مثلا روی ریلی روی لینوکس کسی که روت داره میتونه دستور مخربی اجرا کنه که باقی سرور ها یا سرور اصلی رو از کار بندازه یا یوزر ها یا اطلاعاتشون رو پاک بکنه؟

**Comment by parsatavafi** [comment]
تا جایی که من میدونم Relay فقط نقش تونل رو داره و به جز IP سرور مبدا (که میشه IP سرور Hiddify) شما به اطلاعات دیگه ای نیاز نداره و دسترسی root یا کاربر دیگه ای نمیخواد. به همین خاطر فکر نمی کنم نا امن باشه. در زمان تونل کردن سرورهای خودم روی [هم روش](https://hamravesh.com) تنها چیزی که بهش دادم تنها یک IP سرور بوده و اطلاعات دیگه ای از من نخواست ... **البته نظر قطعی رو توسعه دهنده باید اعلام کنند.**

**Comment by hiddify** [comment]
> تا جایی که من میدونم Relay فقط نقش تونل رو داره و به جز IP سرور مبدا (که میشه IP سرور Hiddify) شما به اطلاعات دیگه ای نیاز نداره و دسترسی root یا کاربر دیگه ای نمیخواد. به همین خاطر فکر نمی کنم نا امن باشه. در زمان تونل کردن سرورهای خودم روی [هم روش](https://hamravesh.com) تنها چیزی که بهش دادم تنها یک IP سرور بوده و اطلاعات دیگه ای از من نخواست ... **البته نظر قطعی رو توسعه دهنده باید اعلام کنند.**

توضیحات بسیار کاملی بود سپاس
