### ISSUE TITLE
روشی برای وصل شدن روی همراه اول

### ISSUE THREAD

**Issue by ho3ein-yazdan** [hiddify/hiddify-config#269]
سلام کسی روشی برای وصل شدن روی همراه اول سراغ داره من هر کاری کردم نشد

**Comment by hiddify** [comment]
مقدار utls رو  عوض کردید جواب داد؟

**Comment by arman2012** [comment]
من خیلی راجب این موضوع تحقیق کردم. همراه اول ، مخابرات و شاتل با همدیگه سرور ها رو از مبدا روی پورت tcp اختلال میندازن و شما نمیفهمید فکر میکنید چون پینگ میده کار میکنه در صورتی که اختلاله و فقط روی ایرانسل کار میکنه.  
شما باید حتما بگردید آی پی اصلیتون تمیز باشه اگه هم از تکنیک کلود فلیر و آیپی تمیز استفاده میکنید باید آی پی پیدا کنید که با همراه کار کنه

**Comment by botgame96** [comment]
من روی همراه اول وصلم و اوکیه تنها راهش تانلینگ هستش برای همراه اول و پیدا کردن یک سرور ایرانی که آی پی کثیف نداشته باشه بعدشم بندازید پشت CDN تمام . بوس به کله همتون :)

**Comment by ho3ein-yazdan** [comment]
> من روی همراه اول وصلم و اوکیه تنها راهش تانلینگ هستش برای همراه اول و پیدا کردن یک سرور ایرانی که آی پی کثیف نداشته باشه بعدشم بندازید پشت CDN تمام . بوس به کله همتون :)

سرور ایرانی برای تونل زدن از کجا پیدا کنیم؟

**Comment by ahaddiba** [comment]
من روی همراه اول وصلم بدون تانل ! هم تروجان هم VLESS !

**Comment by ghermez** [comment]
آی پی های مرتضی رو یکی یکی چک کنید، اونی که کار میکنه بردارین
اون آی پی رو بذارین تو پنل هایدیفای: تنظیمات دامنه ها>>ساب دومینی پشت cdn >>اجبار به استفاده‌ از هاست در کانفیگ‌ CDN
