### ISSUE TITLE
HTTP2 ALPN for trojan CDN seems to have problems with Arvancloud

### ISSUE THREAD

**Issue by smf8** [hiddify/hiddify-config#27]
Hi, Thank you for this awesome script. It seems using WebSockets alongside http/2 causes some problems in Arvan CDN. When using with Clash we'll get : 

```text
23-01-12 18:03:36[ warn ][TCP] dial P (match Match/) 127.0.0.1:61225 --> [destination]:443 error: [CDN_DOMAIN]:443 connect error: dial [CDN_DOMAIN]:443 error: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\x7f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"

```

by commenting alpn in [here](https://github.com/hiddify/hiddify-config/blob/main/clash/all.yml#L45) it works fine. 

Also as I checked x-ray configurations, Trojan over WS fallback is matched via **path** instead of [alpn](https://github.com/hiddify/hiddify-config/blob/main/xray/xtls-sni-config.json.template#L72). it's **trojan-TCP** which is detected with alpn=h2

It would be awesome to check and change clash configs if my assumption is correct.

**Comment by hiddify** [comment]
great thanks for your comment. i will take it into account in the new great version  v5 :-)

**Comment by hiddify** [comment]
ورژن جدید برای آزمایش منتشر شد
نحوه نصب:
```
cd /opt/
git clone https://github.com/hiddify/hiddify-config
cd hiddify-config
git checkout v5
bash install.sh
```
امکانات جدید:
- بهبود بسیار زیاد پرفورمنس
- حذف پروتوکل های قدیمی (یوزرهای قدیمی همچنان امکان اتصال دارند) 
- امکان افزودن چندین دامنه (کافی است در فایل کانفیگ دامنه ها را با ; جدا کنید)
نمونه یک دامنه قابل قبول:   MAIN_DOMAIN=sub1.domain.com;sub2.domain2.com
امکان داشتن چند کاربر برای همه پروتوکل ها: USER_SECRET=uuid1;uuid2 
به زودی امکان مشاهده حجم مصرفی کاربر فراهم میشود
- اورگانیز کردن فایل کانفیگ برای توسعه راحت تر
- افزودن سابسکریبشن لینک که شامل همه کانفیگ ها هست برای دوستانی که میخواهند پروفایل سفارشی ایجاد کنند
- و...



امیدوارم مشکل حل شده باشه

**Comment by smf8** [comment]
awesome! Thank you. I'll test it as soon as possible.

**Comment by farriiig** [comment]
> ورژن جدید برای آزمایش منتشر شد نحوه نصب:
> 
> ```
> cd /opt/
> git clone https://github.com/hiddify/hiddify-config
> cd hiddify-config
> git checkout v5
> bash install.sh
> ```
> 
> امکانات جدید:
> 
> * بهبود بسیار زیاد پرفورمنس
> * حذف پروتوکل های قدیمی (یوزرهای قدیمی همچنان امکان اتصال دارند)
> * امکان افزودن چندین دامنه (کافی است در فایل کانفیگ دامنه ها را با ; جدا کنید)
>   نمونه یک دامنه قابل قبول:   MAIN_DOMAIN=sub1.domain.com;sub2.domain2.com
>   امکان داشتن چند کاربر برای همه پروتوکل ها: USER_SECRET=uuid1;uuid2
>   به زودی امکان مشاهده حجم مصرفی کاربر فراهم میشود
> * اورگانیز کردن فایل کانفیگ برای توسعه راحت تر
> * افزودن سابسکریبشن لینک که شامل همه کانفیگ ها هست برای دوستانی که میخواهند پروفایل سفارشی ایجاد کنند
> * و...
> 
> امیدوارم مشکل حل شده باشه

یک سری مشکل ایجاد شد برای من
1- پروکسی تلگرام تئو حالت Running مونده.
2پل مدریت از کار افتاده
