### ISSUE TITLE
subscription links & sub links base64

### ISSUE THREAD

**Issue by malikshi** [hiddify/hiddify-config#271]
link sub & link sub base64 aren't working for some protocol. here the list.

- tls tcp direct vless
- tls tcp direct trojan
- tls tcp direct vmess
- http tcp direct vmess
- tls grpc direct vmess

what's the error

- tls/http tcp direct missing option head type http and the path.
- tls grpc direct missing gRPC servicename.

Tested in V2rayNG, V2flyNG, Matsuri. i think other xray/v2ray client would be same?

thanks you for your hard work

**Comment by lymanjre** [comment]
Hey. Please update the panel.it should be solved. Thanks for informing us. Regards
