### ISSUE TITLE
قابلیت جابجا کردن کاربران در قسمت کاربران

### ISSUE THREAD

**Issue by NikanMirH** [hiddify/hiddify-config#273]
سلام 
کاش میشد جای کاربر هارو عوض کرد، مثلا من اکانت تست که میسازم میمونه صفحه اول و اکانت های اصلی میره تو صفحه دوم که جالب نیست، قابلیت بالا پایین کردن کاربران و پین کردن و... رو اضافه کنید لطفا

**Comment by hiddify** [comment]
ممنون از پیشنهادتون پیاده سازی این موضوع زمان بر هست خیلی راحت امکان جستجو وجود دارد
