### ISSUE TITLE
جدا کردن ترافیک بین ایران و خارج

### ISSUE THREAD

**Issue by ramindoroozeh** [hiddify/hiddify-config#277]
سلام من هر کاری میکنم که سایت های ایرانی از هیدیفای رد نشه کار نمیکنه

**Comment by botgame96** [comment]
از چه ورژن ابونتو برای سرورت استفاده کردی و اینکه قبل نصب آپدیت کردی ابونتو رو ؟ من روی ورژن 22.04 اول استفاده کردم دیدم جواب نگرفتم چون دقیقا همین مشکل رو داشتم اما بعد اینکه به ورژن 20.04 تغییر دادم فیکس شد و اینکه آخرین آپدیت رو زده بودم از تو پنل :)

**Comment by ramindoroozeh** [comment]
پس ورژن تغییر بدم!؟

**Comment by botgame96** [comment]
> پس ورژن تغییر بدم!؟

برای منکه بعد از اینکارا  و اکتبو کردن تیک ( بلاک کردن سایت‌های ایرانی) بعد نصب از پنل دیگه  تو سایت ایرانی و app ایرانی نمیرفت

**Comment by hiddify** [comment]
از کانفیگ لایت وقتی استفاده میکنید خودش اتومات آی پی های ایران را اصن به سرور نمیفرسته

**Comment by ramindoroozeh** [comment]
عجیبه که اصلا سایت بانک ها رو باز نمیکه

**Comment by lumanjre** [comment]
کانفیگ بایت اوکیه استفاده کنید
