### ISSUE TITLE
عدم امکان تغییر پورتهای اتصال به سرور

### ISSUE THREAD

**Issue by diditra** [hiddify/hiddify-config#281]
درود

با وجود تغییر تنظیمات پنل، پورتهای http و tls روی کانفیگها تغییر نمی کنند.

![image](https://user-images.githubusercontent.com/117894450/222259600-04aa0dec-2f8d-4007-8d4b-efa2f711f193.png)

بعد از انجام این کار و Apply Config همچنان پورتهای کانکشنها فقط 443 و 80 هستند.

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
