### ISSUE TITLE
Support Hysteria and Naive

### ISSUE THREAD

**Issue by mozilla-firefox** [hiddify/hiddify-config#283]
سلام
دوتا از پروتکل هایی که بین چینی ها خیلی محبوب هست
https://github.com/klzgrad/naiveproxy
https://github.com/apernet/hysteria
اگه فرصت بود لطفا بررسی کنید و درصورت امکان ادش کنید به پنل
ممنون

**Comment by hiddify** [comment]
مشکل اساسی اینها اینه که بحث اکانتینگ رو نمیشه بهش وصل کرد
اگه این مشکل حل بشه حتما اضافه میشه

**Comment by sherzadkhalandpour** [comment]
> مشکل اساسی اینها اینه که بحث اکانتینگ رو نمیشه بهش وصل کرد
> اگه این مشکل حل بشه حتما اضافه میشه

واقعا دمتون گرم که اینهمه وقت میزارید و بروز رسانی میکنید و نظراتو میخونید و جواب میدید
