### ISSUE TITLE
دوست عزیز این پنل یک نقطه ضعف بدداره اونم اینه که وقتی نصبش میکنی کلا دسترسی میگیره تو اوبونتو نمیزاره حتی دستور در sshوارد ککنیم همش صفحه پنل خودشو میاره 

### ISSUE THREAD

**Issue by armanem2** [hiddify/hiddify-config#288]
دوست عزیز این پنل یک نقطه ضعف بدداره اونم اینه که وقتی نصبش میکنی کلا دسترسی میگیره تو اوبونتو نمیزاره حتی دستور در sshوارد ککنیم همش صفحه پنل خودشو میاره  چگونه این مشکلو حل کنیم شاید بخوایم از لینوکس استفاده دیگه ام بکنیم

**Comment by hiddify** [comment]
عزیز گزینه disable هم داره دیگه غیرفعالش کن

**Comment by armanem2** [comment]
غیر فعالش کنم کل سرور از کار نمیافته ؟

**Comment by hiddify** [comment]
نه نوشتیم که غیرفعال کردن این دیالوگ

**Comment by armanem2** [comment]
ممنونم
