### ISSUE TITLE
Missing some settings options in panel

### ISSUE THREAD

**Issue by trytopassgfw** [hiddify/hiddify-config#289]
I can't find some of the setting options in the panel. options like Netdata or blocked Iran site or ...
are these settings deleted?

**Comment by hiddify** [comment]
no they are not removed. there was a temporary error. If you want you can restore only the settings from another panel to resolve this issue

**Comment by trytopassgfw** [comment]
What's your point from the "you can restore only the settings from another panel to resolve this issue" ?
which panel?
