### ISSUE TITLE
ارور 500 زمان مشاهده پنل کاربران در پنل مرکزی

### ISSUE THREAD

**Issue by parsatavafi** [hiddify/hiddify-config#290]
من بلاخره با وارد کردن ادرس ادمین پنل مرکزی در پنل های child موفق شدم متصل کنم سیستم رو. به همه جاش فکر کردید واقعا ... دمتون گرم
داخل کلاودفلر ساب دامین اضافه کردم (ابر هم روشن کردم CDN فعال شه اگه باید خاموش باشه ممنون میشم راهنمایی کنید) 
در هنگام ورود به پنل کاربرها این ارور رو بهم میده (پنل مرکزی > users) روی هر کدوم از user link ها میزنم این خطا رو نشون میده
![image](https://user-images.githubusercontent.com/124770095/222302148-4a9a0b60-30ca-422c-a4c5-81760f260a76.png)

**Comment by hiddify** [comment]
تکمیل نشده هنوز
