### ISSUE TITLE
None of the GRPC configs work on domains behind any CDN

### ISSUE THREAD

**Issue by diditra** [hiddify/hiddify-config#291]
**Describe the bug**
None of the GRPC configs work on domains behind any CDN. 

**To Reproduce**
I import the subscription link in v2rayNG, but none of the GRPC connections work on domains behind the CDN. I tried with both CloudFlare and Arvan. Other connection types (both http and tls) on the same domains work fine.
However GRPC on direct domains work!

**Comment by trytopassgfw** [comment]
You have to enable GRPC connection in your CDN.

**Comment by diditra** [comment]
@trytopassgfw Does ArvanCloud also support grpc?

**Comment by trytopassgfw** [comment]
I don't have any active domain on arvan, so I don't know if it has it or not, but I recommend using Cloud flare.

**Comment by diditra** [comment]
I couldn't find any settings on Arvan but I got Cloudflare working with grpc. Thanks!
