### ISSUE TITLE
فعال بودن لينك كابران پس از انقضا

### ISSUE THREAD

**Issue by aminzeidi** [hiddify/hiddify-config#293]
بعد از اينكه مهلت تعيين شده براي كاربر به اتمام ميرسه همچنان لينك هاي پروكسي براش فعاله و ميتونه استفاده كنه تنها راه حذف كامل كاربر از پنل هست اينطوري انگار اون تعيين انقضا فقط جهت اطلاع ادمين هست و بصورت اتومات غير فعال نميكنه پروكسي شو.

**Comment by hiddify** [comment]
یا حجم صفر
