### ISSUE TITLE
عدم نمایش لینک اتصال به پروکسی تلگرام

### ISSUE THREAD

**Issue by kaamyaab** [hiddify/hiddify-config#295]
با عرض سلام و خسته نباشید خدمت هایدیفای جان عزیز
به تازگی بعد از اپدیت خودکار پنل متوجه این موضوع شدم که در صفحه کاربران در قسمت پروکسی تلگرام هیچ دکمه و لینکی جهت اتصال به پروکسی وجود نداره! انگار که حذف یا پنهان شده باشه!

خواستم بدونم مشکل از کجاست؟؟ داخل تنظیمات رو هم چک کردم گزینه پروکسی فعال هست.

**Comment by mewchore** [comment]
من هم این مشکل را دارم. کسایی که قبلا استفاده کردن میدونن لینک پراکسی و سیکرتش چیه؟

**Comment by mewchore** [comment]
مشکل من این بود که فقط دامنه هایی که در حالت دایرکت متصل میشن پراکسی دارن تو حالت CDN نمیشه پروکسی تلگرام داشت.

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نباید داشته باشه
