### ISSUE TITLE
ایجاد دسترسی به سابسکرابیشن ها

### ISSUE THREAD

**Issue by Shahradazar** [hiddify/hiddify-config#296]
ارادت مندم
اگر این قابلیت ایجاد میشد که میتونستیم به سابسکریپشن ها دسترسی داشته باشیم که برای هر کاربر فقط یه تعداد کانکشن یا حتی اگر سرور جدا داریم لینک از سرور خودمون داخلش قرار بدیم خیلی عالییییی میشد

**Comment by lumanjre** [comment]
فک کنم جواب شما [اینجا ](https://github.com/hiddify/hiddify-config/discussions/332)باشه. با این روش و برید به نتیجه مدنظر میرسید.
