### ISSUE TITLE
problem with port 443

### ISSUE THREAD

**Issue by webloper01** [hiddify/hiddify-config#3]
port 443 is close in TelegramVM.
i can see all Inbound port rules and port 443 is in the list, but it's close when i use port check from other servers.
only port 22 in open.

**Comment by hiddify** [comment]
Are you sure?
I have tested this, and it works very well.
There is no restriction on port in azure, is there?

**Comment by webloper01** [comment]
No there isn't.
i used Azure connection troubleshooting and port 443 is allowed. 
But to connect to the VM it's closed.
 no need to open it in ubuntu?
 Actually i checked it and ubuntu firewall is disabled totally.
Should i check anything else?

**Comment by hiddify** [comment]
Maybe there is a problem in nginx service.
Would you please verify if it works?

**Comment by webloper01** [comment]
You're right, Nginx wasn't installed. 
I installed it but another problem is only port 80 is listening on Nginx. 
So I tried to listen port 443 but it needs Ssl Certificate. 

Actually i let it go and I used windows server to run Mtporo.

**Comment by hiddify** [comment]
I am working on it.
At this time i suggest using the new introduction.

azure is not working at this time.

**Comment by hiddify** [comment]
Please let me know if it is fixed now

**Comment by webloper01** [comment]
I checked your new introduction. It is very nice  and completely clear.
When i tried to install using "Easy setup", installation was complete but i couldn't enable V2ray Service.
So i used "Advance Setup" and i installed it very easily.

**Comment by webloper01** [comment]
Your guides for installation and also help page after installation is very perfect.
actually your job is amazing... :)

**Comment by hiddify** [comment]
:)
Please share and star this repo if you like it :)
