### ISSUE TITLE
clash link

### ISSUE THREAD

**Issue by Mosiu9** [hiddify/hiddify-config#300]
نمیدونم چرا ولی اول لینک سابسکریبشن های clash این میوفته ' clash://install-config?url= ' و اینکه وقتی اینو پاک میکنی و لینکو باز میکنی ارور 400 invalid proxy path میگیری . خیلی ممنون میشم فیکس کنید .

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
