### ISSUE TITLE
subdomain filtering

### ISSUE THREAD

**Issue by rezak222** [hiddify/hiddify-config#302]
سلام خدمت دوستان . لطفا یه راهنمایی بکنید برای جلوگیری از فیلتر شدن دامنه یا دیرتر فیلتر شدن . با 5تا کانکشن تو کمتر از یک  روز فیلتر میشم و دارم کلافه میشم

**Comment by hiddify** [comment]
https://github.com/hiddify/hiddify-config/discussions/303?converting=1#discussioncomment-5192224
