### ISSUE TITLE
ارائه چند سرور به کاربر

### ISSUE THREAD

**Issue by rnj79** [hiddify/hiddify-config#306]
میخواستم چند سرور برای کاربرام ارائه کنم . داخل لیست تمام کانفیگ ها از سرور های مختلف براشون کانفیگ باشه و از هر کدوم استفاده کردن از حجم کم بشه . 

راهنمایی میکنید از چه طریقی همچین چیزیو ارائه کنم .

آیا باید یک پنل مرکزی داشته باشم و چند پنل دیگه که وصل بشن به پنل مرکزی از بخش تنظیمات پیشرفته ؟
یا راه دیگه داره .

**Comment by ahaddiba** [comment]
این چیزی که شما میخواید به زودی منتشر میشه ! Parent Panel

**Comment by lymanjre** [comment]
به زودی با معرفی پنل مرکزی انجام میشه
