### ISSUE TITLE
تعیین تعداد اتصال و کاربر متصل و مسدود کردن درصورت اسفتاده چند کاربر

### ISSUE THREAD

**Issue by vahidabbasi77** [hiddify/hiddify-config#307]
با سلام
لطفا این امکان رو اضافه کنید که بشه مشخص کرد به هر اکانت چند کاربر میتونه متصل بشه و در صورت اتصال بیش از حد مجاز اکانت بلاک بشه تا لینک ها ایجاد شده پخش نشه در بین افراد

**Comment by hiddify** [comment]
https://github.com/hiddify/hiddify-config/discussions/238
