### ISSUE TITLE
New Version has many bug

### ISSUE THREAD

**Issue by AliGh1** [hiddify/hiddify-config#31]
Hi, The new version has so many problems that it doesn't even connect and the user panel is changed to /hash32/hash32

**Comment by just1random** [comment]
Since the script uses the main branch as the source of updates, every change made to the code "can" result in a bug and breaks the server because they are not well-tested by users. This problem was so common that I disabled the auto-update provided in the config file. I hope @hiddify uses a more robust updating system in the future.

**Comment by just1random** [comment]
BTW @AliGh1 you can use [my fork](https://github.com/just1random/hiddify-config) of the project from 4 days ago which is working almost fine on all protocols.

**Comment by hiddify** [comment]
Sorry for these issues.
I used [v5 branch](https://github.com/hiddify/hiddify-config/tree/v5) and after requesting tests from many users and they confirm no issue i merge it with main branch 




The url is changed to baseurl/usersecret for future multi user support.

to have backward compatibility i used usersecret as baseurl for old versions.

If you use new version in a bare vps you will see a shorter url.

By the way please let me know if everything is working and sorry for inconvenience

**Comment by AliGh1** [comment]
Very well, so I will test a few things and tell you the result

1. I clone the project and try to Manual installation
`root@something:/opt/hiddify-config# sh install.sh
we are going to install :)
install.sh: 11: Syntax error: "(" unexpected`

2. But that is not a problem, I will try the following command
`sudo bash -c "$(URL=https://raw.githubusercontent.com/hiddify/hiddify-config/main; curl -Lfo- $URL/config.env.default $URL/common/download_install.sh)"`

3. It worked, but the result has a typing problem (\t if front of links)
`or you can use the following links to continue setup:
\thttp://ip-address/4cc4f95694f894e195e9a78e3079f28a/config
\thttps://ip-address.sslip.io/4cc4f95694f894e195e9a78e3079f28a/config`

4. I go to the said page and change the secrets (Because I gave the user link to someone before) and the domain.
5. I don't see the CDN change settings, maybe it is not needed anymore?
6. I can no longer use the old dashboard user link (not a big deal)

However, in the end, everything seems to work, thank you very much
