### ISSUE TITLE
ذخیر vmess با اسم دلخواه یا اسم ایجاد شده اکانت در برنامه 

### ISSUE THREAD

**Issue by vahidabbasi77** [hiddify/hiddify-config#310]
با سلام لطفا این امکان رو ترتیب بدید که کانکشن vmess ساخته شده وقتی اسکان میشه یا وارد برنامه کاربر میشه یک اسم داره ،بشه اون اسم رو تعیین کرد بعد ارسال کرد و به طور پیش فرضم میتونه همون اسم اکانتش باشه

**Comment by lymanjre** [comment]
در قسمت ویرایش پروکسیها انجام بدین
