### ISSUE TITLE
عدم نمایش تاریخ ریست شدن حجم در پنل کاربر

### ISSUE THREAD

**Issue by robin98** [hiddify/hiddify-config#311]
از دیشب متوجه شدم داخل پنل یوزرها دیگه تاریخ صفر شدن حجم یوزرها و مدل محاسبه حجمشون (ماهیانه، هفتگی، روزانه) نمایش داده نمیشه.
نمیدونم این باگ‌ هست یا در نسخه جدید اینجوری شده.

**Comment by hiddify** [comment]
آپدیت را ببر روی نسخه develop بهم بگو هنوز این مشکل هست یا نه

**Comment by robin98** [comment]
@hiddify1 
خیر، متاسفانه تاثیری نداشت.
تمام حالت هایی که به ذهنم رسید رو هم تست کردم: ریستارت کردن، چک کردن از لینک های مختلف و ... .

احتمال می دم به این خاطر باشه که تعداد لینک هایی که به پنل اضافه کردم از یه تعدادی بیشتر شده و برای همین این اتفاق رخ داده و دیگه روزشمار ریست شدن حجم رو نشون نمیده.

**Comment by lumanjre** [comment]
آپدیت کنید حل شده. مرسی
