### ISSUE TITLE
Unable to assign some TLDs as domain

### ISSUE THREAD

**Issue by robin98** [hiddify/hiddify-config#313]
یک سری TLD های رایگان وجود دارن که میشه به عنوان جایگزین دامین های freenom ازشون استفاده کرد؛
از جمله اونها مثل gw.to یا xi.to یا ho.am هستن.

از اونجایی که freenom دیگه دامین نمیده، تنها جایگزین free برای دامنه گرفتن هستن.

دیروز یکی از این دامنه ها تهیه کردم و داخل CF اضافه اش کردم (اضافه کردنش کمی دردسر و ترفند داره ولی شدنیه)

وقتی این دامنه رو به Hiddify میدم و میره برای Apply شدن، پنل به مشکل خیلی بدی میخوره و دیگه بالا نمیاد (باید با لینک اضطراری بری داخلش و دامینی که بهش دادی رو حذف کنی)
احتمال میدم مشکل از دریافت ssl یا همچین چیزی باشه.

**Comment by hiddify** [comment]
میشه ssh بهم بدی hiddify@gmail.com؟

**Comment by robin98** [comment]
@hiddify 
تونستم احتمالات و ردپایی از چرایی مشکل پیدا کنم که نشون میده مشکل از پنل هایدیفای نیست.
من یک vps خام ایجاد کردم و با نصب certbot سعی کردم برای دامنه ساخته شده یدونه SSL بگیرم، اما...

> Obtaining a new certificate
> An unexpected error occurred:
> There were too many requests of a given type :: Error creating new order :: too many certificates already issued for "gw.to". Retry after 2023-03-05T01:00:00Z: see https://letsencrypt.org/docs/rate-limits/

چیزی که صریحا اسکریپت certbot میگه، دلالت از نوعی محدودیت برای ایجاد SSL روی `gw.to` هست.
البته تاریخ رفع محدودیت زیاد دور نیست ولی با توجه به استفاده بالا از این آدرس (به خصوص از الان که دامنه رایگان هم گیر نمیاد) احتمالا برای ساخت هر ساب دامین جدید این داستان هست....

برای اینکه هایدیفای این قضیه رو هندل کنه و ایرانی ها بتونن به عنوان جایگزین freenom از این سیستم استفاده کنن،
میشه برای این مدل از دامنه ها، از جای دیگه ای درخواست ssl داده بشه؟

**Comment by hiddify1** [comment]
سلام
مشکل از acme.sh بود دستکاریش کردیم که اگه همچین چیزی شد خارج بشه تا از zerossl سرتیفیکیت بگیره
نسخه جدید را ببینید

**Comment by robin98** [comment]
> سلام مشکل از acme.sh بود دستکاریش کردیم که اگه همچین چیزی شد خارج بشه تا از zerossl سرتیفیکیت بگیره نسخه جدید را ببینید

سلام مجدد، فکر می کنم با این دستکاری یه مشکلی هم پیش اومده باشه. الان من یه ساب دامین از مدل direct دادم ولی بر خلاف دفعات گذشته وقتی با این ساب دامین جدید میخوام وارد پنل بشم، مرورگر بهم اخطار SSL میده.
```
NET::ERR_CERT_COMMON_NAME_INVALID
```
