### ISSUE TITLE
آپدیت نشدن سابسکرایب و تغییر آدرس فایل سابسکرایب 

### ISSUE THREAD

**Issue by ghermez** [hiddify/hiddify-config#314]
سلام
متوجه شدم که فایل سابسکرایب با اینترنت همراه بدون فیلترشکن آپدیت نمیشه!
دومین و ساب دومین کاملا تازه و نو هستن! آی پی هم فیلتر نیست! ولی نمیدونم چرا با اینترنت همراه آپدیت نمیشه! نمیدونم کسی به این مشکل برخورده یا نه؟

آیا راهی هست که لینک دانلود سابسکرایب رو بدون تغییر به آدرس جدید فوروارد کرد؟

**Comment by robin98** [comment]
شما به راحتی میتونید به این آی پی خودتون SSH بزنید؟ و روی همون اینترنت نمی تونید لینک ساب رو دریافت کنید؟
با همون اینترنت همراه تست کنید ببینید میتونید SSH بزنید به سرور.
اگه جواب منفی بود یعنی اون IP روی اپراتور مربوطه مسدود هست. یا IP رو عوض کنید یا با relay ایران یک لینک ایجاد کنید https://github.com/hiddify/hiddify-config/discussions/129#discussioncomment-4996908

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
