### ISSUE TITLE
استفاده از آیپی شناور به جای آیپی اصلی

### ISSUE THREAD

**Issue by SilverAntonie** [hiddify/hiddify-config#317]
درود
من به دلیل فیلتر بودن آیپی سرورم از آیپی شناور استفاده میکنم و آیپی رو به سرورم متصل کردم. مشکلی که هست اینه که هنگام نصب هیدیفای روی سرور برنامه روی آیپی اصلی نصب میشه و به همین دلیل سه تا مشکل پیش میاد. اول اینکه وقتی دامنه رو به آیپی شناور که فیلتر نیست اشاره میدم هیدیفای اجازه سابمیت کردن نمیده و دوم اینکه اگر از آیپی اصلی استفاده کنم نمیتونم از طریق لینک ایمن یعنی با دامنه وارد پنل بشم. و مشکل سوم که از همه مهم تره اینه که اصلا نمیتونم کانفیگ ها رو با لینک سابسکریپشن وارد کنم. ممنون میشم راهنمایی بفرمایید

**Comment by hiddify** [comment]
به عنوان دامنه relay اضافه کنید
