### ISSUE TITLE
http tcp direct vmess

### ISSUE THREAD

**Issue by MILADALEF** [hiddify/hiddify-config#318]
داخل لینک سابسکزیپشن مخصوص اپ هایدیفای یک کانفیگ هست به اسم http tcp direct vmess که دارای https header هست و روی مخابرات عالی کار میکند ، ولی این کانفیگ در سابسکریپشن اصلی و لیست آل کانفیگ دارای هدر نیست ... لطفا این باگ رو برطرف کنید

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
