### ISSUE TITLE
امکان اضافه کردن آیپی تمیز CDN برای هر کابر

### ISSUE THREAD

**Issue by nima2010** [hiddify/hiddify-config#320]
من یه پیشنهاد دارم، چون که الان برای هر نفر ممکنه آیپی تمیز CDN متفاوت باشه، بشه تو قسمت پنل کاربران برای هر کاربر یه force ip cdn تعریف کرد و خروجی کانفیگ رو براش با توجه به آیپی که اضافه کردیم بده. چون الان من بهشون یاد دادم که برنامه اسکنر آیپی رو سمت خودشون اجرا کنن، ولی من باید دستی براشون کانفیگ ها رو ادیت کنم.

**Comment by lumanjre** [comment]
[این مطلب](https://github.com/hiddify/hiddify-config/discussions/332) را بخونید. جوابتون اونجاس
