### ISSUE TITLE
پایین بودن سرعت آپلود

### ISSUE THREAD

**Issue by MohMehrnia** [hiddify/hiddify-config#3204]
با سلام
سرعت آپلود سرویس بسیار بسیار پایین است، در صورتی که از پشت سرور سرعت آپلود بسیار بالا می باشد. دامنه روی مراد فلر تنظیم شده است، آیا تغییراتی برای افزایش سرعت آپلود لازم است؟

**Comment by hellomynameismoney** [comment]
سلام.سرورتون مشکل داره.

**Comment by hellomynameismoney** [comment]
معمولا سرورهایی که فیلتر میشن سرعت آپلودشون به شدت میاد پایین.

**Comment by MohMehrnia** [comment]
این مشکل فقط در واتس آپ هست، در تلگرام همچین مشکلی وجود ندارد
