### ISSUE TITLE
اضافه کردن ساکس 5 تلگرام

### ISSUE THREAD

**Issue by vahidabbasi77** [hiddify/hiddify-config#321]
با سلام به نظر میرسه پراکسی تلگرام عمومی و اکانتینگ رو پشتیبانی نمیکنه لطفا ساکس 5 (socks5) رو اضافه کنید که اکانتینگ رو هم پشتیبانی میکنه سرعت نسبتا خوبی هم داره برای تلگرام

**Comment by robin98** [comment]
ساکس فایو خیلی وقته توی ایران اختلال داره و بیشتر شهرها کار نمیده. اگه هم فعلا درست شده ارزش سرمایه گذاری نداره چونکه براحتی میشه دوباره از کار انداختش.

**Comment by hiddify1** [comment]
به نظرم نسخه nekogramx خیلی خوبه برای حل این مشکل
