### ISSUE TITLE
False-Positive Update Message پیام نیاز به آپدیت نادرست

### ISSUE THREAD

**Issue by fakoor** [hiddify/hiddify-config#3224]
**Describe the bug**
در پنل پیام نیاز به آپدیت نشان داده می‌شود
In the panel, a message shows that an update is needed.

⚠️ This version of Hiddify Panel is outdated. please update it from admin area.
⚠️ این نسخه هیدیفای قدیمی شده است. لطفا از پنل ادمین آن را به روزرسانی کنید

hiddify panel version current=7.2.0 latest=7.2.0
Current Config Version=10.1.3 -- Latest=10.1.3

**To Reproduce**
1. Have a panel updated to 7.2.0
2. Visit the main admin page

**Expected behavior**
وقتی نسخه‌ها یکی هستند پیام آپدیت نشان داده نشود
If the current and upstream version are the same, it is not expected to see the update requirement message

**Screenshots**
![image](https://github.com/hiddify/hiddify-config/assets/11645244/70b0f3c8-37e5-4e8a-b887-739fb36d8258)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
It is even shows that the update has been completed successfully, but after a while when you login to the dashboard at the next time, the update requirement message is displayed again.
به هرحال پس از اجرای آپدیت پیام موفقیت آمیز هم نشان داده می‌شود. ولی پس از مدتی که به داشبوردمراجعه کنیم دوباره پیام نیاز به آپدیت دیده می‌شود

**Comment by sadeghibehzad** [comment]
با عرض سلام
برای بنده هم از دیروز حداقل من اصلاع دارم که این پیام نشون داده میشه

**Comment by fakoor** [comment]
It was present in baseline version 7.x,  We are now on 8 and the issue is gone

**Comment by Mostafashb** [comment]
همین مشکل رو در نسخه 8 من دارم و آپدیتی هم نیامده

**Comment by isp85** [comment]
بنده همین مشکل رو با آخرین ورژن هم دارم
hiddify panel version current=8.8.2 latest=8.8.2
RELEASE: Current Config Version=10.5.50 -- Latest=10.5.50
باز هم وقتی میرم به داشبورد پیام میاد که بیا آپدیت کن
