### ISSUE TITLE
چطوری میتونم ipv6 رو ip پیشفرض قرار بدم؟

### ISSUE THREAD

**Issue by sh4msi** [hiddify/hiddify-config#323]
سلام
هادیفای رو روی 2 سرور از 2 دیتاسنتر مختلف نصب کردم که هر دو ipv6 دارند
در زمان کانکت شدن برای یکی v6 میندازه و برا یکی v4

کسی از دوستان تا حالا به این موضوع برخورد کرده؟
چطوری میتونم ip v6 رو ایپی پیشفرض قرار بدم؟

**Comment by hiddify1** [comment]
یعنی چی 
خوب دامنه AAAA تعریف کنید

**Comment by Fl2ankenStein** [comment]
fek konam manzureshun be surate direct has ke emkan pazir nis relay ya cdn
