### ISSUE TITLE
عدم وجود کانفیگ های مربوط به حالت دایرکت و دامین فرانتینگ 

### ISSUE THREAD

**Issue by sh4msi** [hiddify/hiddify-config#324]
سلام
در پنل کاربر کانفیگ های مربوط به direct و دامین فرانتینگ لود نمیشن
از طریق لینک اشتراک هم لود تست کردم

در نسخه استبل و توسعه چک کردم

**Comment by sh4msi** [comment]
جالب شد 
الان در یک پنل دیگه چک کردم اوکی بود و کانفیگ های direct لود میشد

-----
قبل اینکه متوجه این موضوع شم پنل رو به نسخه بتا اپدیت کردم و بعد از مشاهده این موضوع برگردوندم به نسخه استیبل
ایا میتونه ساید افکت های نسخه بتا باشه ؟

راهکار؟

**Comment by hiddify1** [comment]
ببینید باید حتما دامنه مربوط به دایرکت را اضافه کنید توی لیست دامنه های نمایشی
