### ISSUE TITLE
حذف دستی دامین

### ISSUE THREAD

**Issue by sh4msi** [hiddify/hiddify-config#326]
برای یکی از دامین های پارک در شده مشکلی پیش امده و ssl براش صادر نمیشه
و پنل کلا بالا نمیاد
در تلاش های که از طریق کامند لاین انجام دادن برای ریستارت و ران کردن سرویس های هایدیفای متوجه شدم که بخاطر عدم صدور ssl برای اون دامین خاص سرویس ها به مشکل میخورن و بخوبی ران نمیشن
این موضوع قبلا توسط دوست دیگه در این تایپیک به شکل دیگه ی مطرح شده ولی جواب براش مطرح نشده

https://github.com/hiddify/hiddify-config/issues/313#issuecomment-1454838571

**Comment by hiddify1** [comment]
سلام
مشکل از acme.sh بود دستکاریش کردیم که اگه همچین چیزی شد خارج بشه تا از zerossl سرتیفیکیت بگیره
نسخه جدید را ببینید
