### ISSUE TITLE
راهکار استاندارد برای حذف هادیفای

### ISSUE THREAD

**Issue by sh4msi** [hiddify/hiddify-config#327]
سلام
من میخواستم هادیفای رو بصورت کامل حذف و دوباره نصب کنم ولی با حذف اتفاق نمی افته

`
root@ubuntu:/opt/hiddify-config# sudo ./uninstall.sh 
Failed to kill unit netdata.service: Unit netdata.service not loaded.
Synchronizing state of netdata.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable netdata
Failed to kill unit clash-server.service: Unit clash-server.service not loaded.
Failed to disable unit: Unit file clash-server.service does not exist.
Failed to kill unit shadowtls.service: Unit shadowtls.service not loaded.
Failed to disable unit: Unit file shadowtls.service does not exist.
Failed to kill unit ss-faketls.service: Unit ss-faketls.service not loaded.
Failed to disable unit: Unit file ss-faketls.service does not exist.
Failed to kill unit ss-v2ray.service: Unit ss-v2ray.service not loaded.
Failed to disable unit: Unit file ss-v2ray.service does not exist.
Failed to kill unit hiddify-panel.service: Unit hiddify-panel.service not loaded.
Failed to disable unit: Unit file hiddify-panel.service does not exist.
Failed to kill unit hiddify-sniproxy.service: Unit hiddify-sniproxy.service not loaded.
Failed to disable unit: Unit file hiddify-sniproxy.service does not exist.
Failed to disable unit: Unit file hiddify-xray.service does not exist.
Failed to kill unit nginx.service: Unit nginx.service not loaded.
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable nginx
 * Reloading configuration files for periodic command scheduler cron
   ...done.
`

**Comment by hiddify1** [comment]
`./uninstall.sh purge`

**Comment by xzerooo** [comment]
ببخشید چرا من هر کاری میکنم این پنل هیدیفای حذف نمیشه میخوام حذفش کنم نمیزاره پنل های دیگه هم نصب کنم  لطفا سریع جواب بدید

**Comment by radshodam** [comment]
با این دستور میتونید حذفش کنید `sudo apt remove hiddify`   
  اگرهم با نام دیگری براتون نصب شده بود در اینجا ببینید با دستور` dpkg --list` تمام لیست نصبی هاتون میاد و با این دستور حذف میشه
 `sudo apt remove app_name`
