### ISSUE TITLE
v6 proxied clouldflar links down help F1

### ISSUE THREAD

**Issue by Fl2ankenStein** [hiddify/hiddify-config#329]
@hiddify1 ye mored jaleb baade zohr kollen connection hayi ke dashtam ipv6 az cloudflare proxy migereftam yeho az kar oftad faghat direct kar mikone . har kar kardam doros nashod pak kardam server dobare zadam ip haro avaz kardam subdomain haro avaz kardam asalan doros nemishe mishe ba ssh ye check koni bizahmat :*

**Comment by Fl2ankenStein** [comment]
panel faghat ba direct v4 miyad ba v6 proxy hichi

**Comment by hiddify1** [comment]
az cloudflare ipv4 miad?

**Comment by Fl2ankenStein** [comment]
are miyad

**Comment by Fl2ankenStein** [comment]
ba panel ham aslan kar nadashtam update shod chi shod yeho dagun shod

**Comment by Fl2ankenStein** [comment]
error 521e

**Comment by Fl2ankenStein** [comment]
dustan kasi ba in mored mavajed shode ke link panel ipv6 cdn moghe open kardam error 521 cloudflare bede?

**Comment by Fl2ankenStein** [comment]
@R30na bia inja 🗡️  :D

**Comment by mygit28** [comment]
سلام بله بعد از آپدیت به نسخه جدید ساب دامین هایی که با ipv6 آدرس دهی شدن در کلادفلر، از کار افتادن!

**Comment by Fl2ankenStein** [comment]
agha man hame chiyo koobidam az aval sakhtam goftam shayad az taghirate man bashe hatta cloudflare ham az aval sakhtam in moshkel server side va az panel has error 521 cloudflare

**Comment by Fl2ankenStein** [comment]
> az cloudflare ipv4 miad?
ip migire 
ye barresi mishe vakht kardid anjam bedid

**Comment by mygit28** [comment]
سلام مشخص نشد دلیل این مشکل چیه؟

**Comment by Fl2ankenStein** [comment]
> سلام مشخص نشد دلیل این مشکل چیه؟

baad update server va taghir TLS encryption mode be flexible hal shod mozu
