### ISSUE TITLE
ایراد لینک ساب در ورژن جدید

### ISSUE THREAD

**Issue by ahaddiba** [hiddify/hiddify-config#330]
سلام
در ورژن جدید ظاهرا فرمت لینک ساب عوض شده ! روی Fair VPN نسخه مک اررور میده در صورتی که قبلا به راحتی میاورد

**Comment by ahaddiba** [comment]
میدونم ! روی نسخه آیفون کار میکنه ! روی مک ایراد میگیره

**Comment by mygit28** [comment]
سلام این مشکل در آیفون 6 با نرم افزار fair vpn هم هست از بعد از آپدیت این مشکل به وجود اومده!

![photo_۲۰۲۳-۰۳-۰۶_۱۴-۲۵-۴۱](https://user-images.githubusercontent.com/119749536/223106066-8552bd2f-106f-4bc6-b120-a61b964061b5.jpg)

**Comment by ahaddiba** [comment]
اگر emoji بذاری توی اسم اینطوری میشه ! من emoji حذف کردم درست شد

**Comment by hiddify1** [comment]
❤️

**Comment by mygit28** [comment]
مشکلم حل شد ظاهرا علاوه بر ایموجی اسپیس هم نباید بزاریم تو اسم
