### ISSUE TITLE
مشکل در کانفیگ پنل ورژن قبلی

### ISSUE THREAD

**Issue by sherilynhonkan** [hiddify/hiddify-config#334]
فایل پنل ورژن قبلی رو داخل سرورم کپی کردم و با دستور bash install.sh تو دایرکتوری cd /opt/hiddify-config که بود زدم و پنل نصب شد. به مرحله ای رسیدم که لینک کانفیگ اولیه رو میده که باید آیپی رو وارد که میکنیم چنین پیغامی میده:
Please underestand that this link is temporary and will be disappeared after one hour. Please click [here]) to continue setup.

وقتی کلیک میکنم ارور زیر رو میده:
502 Bad Gateway
nginx/1.18.0 (Ubuntu)

لطفا کمکم میکنین مشکل کجاست و چرا مرحله کانفیگ اولیه نمیاد که بتونم ساب دامین رو بزنم و باقی تنظیمات رو انجام بدم؟

**Comment by sherilynhonkan** [comment]
از داخل ssh که bash status.sh میزنم این رو میاره و failed زده:

hiddify-admin                  failed                         
ss-faketls                     inactive                       
ssplugin-shadowtls             inactive                       
ss-v2ray                       inactive                       
hiddify-sniproxy               active                         
mtproxy                        active                         
hiddify-xray                   active                         
netdata                        active                         
nginx                          active

**Comment by hiddify1** [comment]
پنل ادمین خطا داده ببین حطاش چیه

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
