### ISSUE TITLE
مشکل و کرش  کردن هایدیفای بعد از آپدیت

### ISSUE THREAD

**Issue by NikanMirH** [hiddify/hiddify-config#335]
سلام 
بعد از اپدیتی که داده شد اپ هایدیفای یا کرش میکنه یا کار نمیکنه 
اما بجاش اپ کلش کار میکنه (ولی خب vless رو نمیاره)
میخواستم ببینم که مشکل کی حل میشه؟
یا اصلا میشه دوباره برگشت به ورژن 1.0.0.0؟
اگر خود هایدیفای آپدیت بشه یا مشکلش حل بشه خیلی عالیه 

مرسی از زحماتتون

**Comment by lymanjre** [comment]
در نسخه بعدی اپ مشک حل خواهد شد چون بیس اپ تغییر کرده
