### ISSUE TITLE
باگ داشتن و کرش کردن نرم افزار های هدیفای روی windows 11 و گوشی poco x4 pro

### ISSUE THREAD

**Issue by Obeid1375** [hiddify/hiddify-config#337]
برنامه هدیفای روی بقیه پلتفرم ها نمیدونم اما روی ویندوز ۱۱ و شیامی پوکو اصلا میزنی ران شه گیر میکنه.

![Screenshot_2023-03-06-20-35-00-137_com hiddify hiddifyproxy meta](https://user-images.githubusercontent.com/39822409/223182898-a4031c19-e3fd-4406-936f-75f3d486a326.jpg)

الان رانش کردم اصلا توی قسمت پروکسی ها نمیره.

برای ویندوز هم میزنم میره اما هیچ پروکسی نشون نمیده و دیگه گیر میکنه همونجا.

**Comment by hiddify1** [comment]
فکر کنم پروفایل ها باگ داشته پنل را ببر روی دوولپ ببین حل میشه

**Comment by NikanMirH** [comment]
منظور اینکه حالت بروزرسانی رو بذاریم رو توسعه؟

**Comment by hiddify1** [comment]
آره

**Comment by Obeid1375** [comment]
> فکر کنم پروفایل ها باگ داشته پنل را ببر روی دوولپ ببین حل میشه

فردا انجامش میدم.
حالت توسعه هم توی آپدیت جدید موقع بک آپ گرفتن زمان باقی مانده کاربرارو null میبره توی json و برای ریستور به مشکل بر میخوره.

**Comment by NikanMirH** [comment]
من پنل رو بردم رو دولوپ مود ولی بازم مشکل رفع نشد 🥲

**Comment by hiddify1** [comment]
> > فکر کنم پروفایل ها باگ داشته پنل را ببر روی دوولپ ببین حل میشه
> 
> فردا انجامش میدم. حالت توسعه هم توی آپدیت جدید موقع بک آپ گرفتن زمان باقی مانده کاربرارو null میبره توی json و برای ریستور به مشکل بر میخوره.

نسخه جدید ریلیز شد
دیگه expire date نداریم بلکه روز شروع داریم که بر اساس روز و حجم بسته تعیین میکنه که کی منقضی بشه
