### ISSUE TITLE
عدم عملکرد ر همراه اول

### ISSUE THREAD

**Issue by adlimohamadreza** [hiddify/hiddify-config#338]
با سلام و خسته نباشید
هایدیفای و... رو ایرانسل رایتل و اینترنت ابت کار میکنه و لی روی همراه اول اصلا پروفایل لود نمیشه!
باید چیکار کنم؟

**Comment by kaamyaab** [comment]
من بردم روی Cdn ابر اروان همراه اول وصل شد

**Comment by ahaddiba** [comment]
vless://UUID@discord.com:443?security=tls&sni=YOUT.DOMAIN.COM&type=ws&path=/TNJ2HpzsJj0jCwH7kxJiB0xlB03R/vlessws&host=YOU.DOMAIN.COM&encryption=none&fp=chrome&headerType=None#tls_WS_CDN_vless

من با vless + WS + CDN + TLS به راحتی دارم روی همراه اول استفاده میکنم !

**Comment by lumanjre** [comment]
دوستان تنها راه حل برای چنین مواقعی استفاده از cdn است. مطالب ویکی را بخونید

**Comment by mohammadrezakarimi78** [comment]
> من بردم روی Cdn ابر اروان همراه اول وصل شد

سلام وقتتون بخیر
من روی ابرآروان که بردم 502 میده 
میشه یکم راهنمایی کنین که به چه صورت اقدام کردین
