### ISSUE TITLE
user adress incorrect

### ISSUE THREAD

**Issue by aag0116** [hiddify/hiddify-config#34]
my user page is
https://xxxx/59e726d68ef64767cc77a7b7651b6e45/59e726d68ef64767cc77a7b7651b6e45/

pls fix it to
https://xxxx/59e726d68ef64767cc77a7b7651b6e45/

**Comment by hiddify** [comment]
Both address work
However, in the new version, we are going to add multi user
So just for backward compatibility we use this address. In a fresh installation, the address will be sth like 
`https://xxx/base_secret_with_random_length/uuid/`
