### ISSUE TITLE
User's panel QR code isn't valid anymore

### ISSUE THREAD

**Issue by robin98** [hiddify/hiddify-config#340]
### توصیف باگ

> در پنل سمت یوزر، یک باکس زرد رنگ وجود داره که کارش نشون دادن لینک صفحه جاری به فرمت qr code هست.
مقادیر این باکس همگی outdated هستن و به پنل غیرمعتبری لینک شدن.

### گام های بازآفرینی
**مراحل گام به گام برای برخوردن به مشکل:**

1. وارد پنل یکی از کاربران میشیم
2. از باکس کیو آر کد روی گزینه نمایش کیو آر کد می زنیم
3. در پنجره ای که باز میشه، مقادیر کپی/بازکردن/کیو آر کد هر سه رو چک می کنیم
4. متوجه می شیم هر 3 به پنل قدیمی لینک میشن و نه به پنلی که آخرش به مسیر `/new` ختم میشه

### رفتار مورد انتظار در حالت نرمال
مقادیر این قسمت باید داینامیک بر اساس صفحه valid تولید بشن یعنی صفحه ای که یوزر در حال حاضر اون رو با مرورگر داره می بینه

**Comment by hiddify1** [comment]
fixed
