### ISSUE TITLE
سابسکریپشن

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#349]
ی قابلیت هم اگر بشه اضافه کرد که بتونیم ی relay به ی‌ سرور خام داخل بزنیم و از اون فقط به عنوان سابسکریپشن url base استفاده کنیم خیلی خوب میشه من با سرور خودم تست کردم دیدم ایرانسل و شاتل راحت ساب اپدیت میشه ولی همراه اول اصلا ساب اپدیت نمیشه !

یعنی ی سرور خام داخلی بالا بیاریم و متصل بشه به سرور هایدیفای ما و ساب ها در اونجا سیو بشوند و خروجی لینک از اون باشه و راحت و سریع هر موقع بشه ساب هارو اپدیت کرد

**Comment by realartin** [comment]
خیلی بهتر بود میشد ساب رو کلا رو ی سرور مجزا بالا اورد

**Comment by ahaddiba** [comment]
شما میتونی یه ساب جدا درست کنی فقط برای sub link تو تنظیمات بزنی کانکشن های لینک های دیگه رو نشون بده مال خودش رو نشون نده ! اون میشه ساب لینک هیچ وقت هم فیلتر نمیشه ! دیگه نیازی به relay یا سرور مجزا نداری
