### ISSUE TITLE
Update configs

### ISSUE THREAD

**Issue by Mobinoo1383** [hiddify/hiddify-config#356]
**Describe the bug**
Decided to manually update and this happened
![image](https://user-images.githubusercontent.com/124462330/223574966-5b0cc411-ca1e-4cf1-bf5c-c5026bf17475.jpeg)
It's stuck on this error 
And it's not applying the configs 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hiddify1** [comment]
توی اخرین ورژن حل شده
