### ISSUE TITLE
Problem with cdn

### ISSUE THREAD

**Issue by aag0116** [hiddify/hiddify-config#36]
vless and trojan configurations do not work with cdn and only vmess is active, but there are no problems without cdn

**Comment by hiddify** [comment]
Fixed in new version.

CDNs do not support h2 alpn. we have removed it

**Comment by aag0116** [comment]
afterv last update less and trojan configurations do not work with cdn and only vmess is active

**Comment by hiddify** [comment]
In which configuration?
Clash, Hiddify, v2ray...?

**Comment by aag0116** [comment]
i check ios link

**Comment by aag0116** [comment]
Yeah. I checked and added shadow rocket they don't connect, only vmess connect after turning on cdn

**Comment by absoonoo** [comment]
Hello Dear @hiddify 
First ,thank you for your help!
And two please guide me ; Is it possible to use two domains with and without CDN?
My domain cloud in on ,and only work CDN vmess_ws and CDN trojan_ws is works fine but with increasing ping.
Merci

**Comment by hiddify** [comment]
You can edit config.env file and add multiple domain for MAIN_DOMAIN

e.g.,
`MAIN_DOMAIN=h.com;h2.h.com`

**Comment by aag0116** [comment]
Can this cdn problem be solved or am I just having a problem?

**Comment by hiddify** [comment]
سلام
لطفا به ورژن جدید به روز رسانی کنید و نتیجه را اعلام کنید
با سپاس
