### ISSUE TITLE
صفحه کاربران بالا نمیاد ارور ۵۰۰ میده

### ISSUE THREAD

**Issue by amirakrami852** [hiddify/hiddify-config#360]
سلام صفحه کاربران نمیاد بالا ارور میده 
![Uploading 314FB7E9-810C-4051-ADBA-D9905EA9FC4E.jpeg…]()

**Comment by lumanjre** [comment]
در آپدیت جدید فیکس شد

**Comment by wreza** [comment]
هنوز فیکس نشده

**Comment by dreamboxone** [comment]
بعد از نصب روی سرور هتزنر - اوبنتو ۲۲.۰۴  و تامل حدود ۲۰ دقیقه تا زمانی که لینک پانل ساخته بشه با خطای 502Bad Gateway روبرو شدم

**Comment by lumanjre** [comment]
روی سرور ssh بزن و آپدیت دولوپ را از منو انتخاب کن. اگر منو نمیاد این کارو بکن:


``` bash /opt/hiddify/hiddift-config/update.sh develope‍ ```

توی ترمینا با روت اینو اجرا کن بعد آپدیت تست کن. 

منظور من اینه با هر روش چه منو چه کامند چه وب نرم افزار را به نسخه دولوپ آپدیت کن مشکل حل میشه

**Comment by wreza** [comment]
بعد اپدیت به نسخه دولپ باز این ارور داره
![image](https://user-images.githubusercontent.com/34791907/223792174-b096ddbe-8f2e-46c2-9b32-7ccb19085d91.jpeg)

**Comment by wreza** [comment]
![image](https://user-images.githubusercontent.com/34791907/223792225-99ce860b-6d5b-43e3-8055-0aa5e2646fd0.jpeg)

**Comment by wreza** [comment]
رو هتزنر و اولونتو ۲۲.۰۴
