### ISSUE TITLE
نبود امکان تغییر دستی حجم مصرفی کاربر در آپدیت جدید

### ISSUE THREAD

**Issue by DanielNoohi** [hiddify/hiddify-config#361]
بنظر میاد تو آپدیت آخر پنل ۱.۵.۲ امکان تغییر دستی مصرف حجم کاربر حذف شده، آیا این درسته؟

**Comment by hiddify1** [comment]
بله حذف شده شلوغ کرده بود پنلو

**Comment by DanielNoohi** [comment]
نمیشه اینجور امکانات رو اپشن بیس کنید تا کسی خواست آن کنه کسی نخواست آف کنه؟

**Comment by DanielNoohi** [comment]
اون تیک که پایین گذاشتید رو زدم برای ریست کردن بعدش تیک حذف شد ولی ترافیک کاربر ریست نشده بود و دیگه اون دکمه کشویی هم حذف شده برای اون کاربر به خصوص فقط کنار روز های باقی مانده یه ستاره اضافه شده که احتمال میدم اون تموم بشه ریست میکنه، الان که میخوام دستی ریست کنم ترافیکش رو چیزی وجود نداره صفرش کنم در آن واحد
