### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by wreza** [hiddify/hiddify-config#365]
The server returned an invalid or incomplete response. سلام این ارور میاد بعد نصب نمیشه وارد پنل شد و ادامه داد رو Hetzner 
![image](https://user-images.githubusercontent.com/34791907/223715759-446b822f-aae5-4924-9c88-d82940d5e904.jpeg)

**Comment by wreza** [comment]
اپ دیت هم هست ولی باز این مشکل پابرجاست
![image](https://user-images.githubusercontent.com/34791907/223719383-39b84bd4-6a18-4c6e-a4dd-aad02ea7ecd0.png)

**Comment by Parsa82-tech** [comment]
منم همین مشکلو از دیروز دارم و چند بار uninstall/install کردم میزنه 
an important service hiddify-nginx is not working yet
checking again...
an important service hiddify-nginx is not working again
Installation Failed!

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
