### ISSUE TITLE
 برنامه v2rayng اندروید در حالت utls =chrome کار نمیکنه 

### ISSUE THREAD

**Issue by ehsan7m** [hiddify/hiddify-config#366]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by robin98** [comment]
بله منم تایید می کنم که تمام کلاینت هایی که من میشناسم مشکلی با وجود یا عدم وجود uTLS ندارن.
مطمئن بشید که نسخه اصلی و آپدیت v2rayNG رو دارید:

https://github.com/2dust/v2rayNG/releases/tag/1.7.38

**Comment by ehsan7m** [comment]
اضافه کردن حالت none یا هیچکدام به utls چون برنامه v2rayng اندروید در حالت utls =chrome کار نمیکنه باید داخل برنامه عوض کنیم و به حالت سفید بگذاریم لطفا این مشکل را حل کنید


عنوان رو اصلاح کردم ببخشید 
اما در مورد این مشکل باید بگم بله با آخرین نسخه ای که از v2ray در پلی استور هست کانفیگ ها وقتی utls =chromهست کار نمیکنن 
دستی utls رو حالت سفید میکنم کار میکنه احتمال داره گوشی با گوشی فرق کنه ولی این مشکل در بعضی ها هست که بهشون کانفیگ میدم بعد میگم utls رو تغییر بدین درست میشه

**Comment by lymanjre** [comment]
این موضوع با برنامه v2rayng هست
