### ISSUE TITLE
cloudflare api

### ISSUE THREAD

**Issue by khashayar5** [hiddify/hiddify-config#367]
ارتباط پنل از طریق ای پی ای به کلود فلر و داشتن یک سری دامنه در اسپول دامنه ها که در صورت بلاک شدن به دامنه بعدی اپدیت شود

**Comment by robin98** [comment]
آره اینم یه ایده قشنگ و خیلی جالبه که قبلتر اینجا هم در موردش بحث داشتیم https://github.com/hiddify/hiddify-config/issues/286
نمیدونم api کلادفلر تا چه اندازه دسترسی صادر میکنه ولی منطقا باید از پس این کار بر بیاد.
