### ISSUE TITLE
بخش کاربران 

### ISSUE THREAD

**Issue by amirakrami852** [hiddify/hiddify-config#368]
سلا اول تشکر میکنم بابت همه زحماتی که میکشید 
بعد یک پیشنهاد دارم 
در صورت امکان در بخش یوزر ها قسمتی رو اضافه کنید تا بتونیم دامین ی که میخایم یوزر کانفیگ هاش و ببینه تو پنل خودش قابل تغییر باشه به طور مثال شاید بخایم دامین دایرکت رو محدود کنیم به چند یوزر خاص و اینطوری انتخاب دست خودمونه 
ممنون

**Comment by lymanjre** [comment]
هم اکنون این قابلیت وجود داره
