### ISSUE TITLE
xray-core install script does not install prerelease version

### ISSUE THREAD

**Issue by wlfvpn** [hiddify/hiddify-config#369]
In `https://github.com/hiddify/hiddify-config/blob/main/xray/install.sh`
`bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install`
should be changed to
`bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --beta` to install prereleases like 1.7.5.

I'm not sure if you're using this script or not or if this was intentional but I'm sure you know it already and might have missed it.

**Comment by lymanjre** [comment]
Please check the latest update. Should be solved

**Comment by lymanjre** [comment]
Please check the latest update. Should be solved
