### ISSUE TITLE
ssl build problem and host

### ISSUE THREAD

**Issue by aag0116** [hiddify/hiddify-config#37]
SSL cannot be requested more than 5 times in seven days, and this causes us to have problems in the installation process.But this script solves this problem by adding a txt record and can receive ssl.
https://github.com/mack-a/v2ray-agent/blob/master/documents/en/README_EN.md
If this item is added, it would be great to get ssl from other methods during installation, because sometimes problems arise during installation and we have to install it several times.

**Comment by hiddify** [comment]
adding txt record is a bit more advanced method and is not supported by free subdomain

so we make it as general as possible

In addition let's encrypt limitations:
The main limit is Certificates per Registered Domain (50 per week). 

Renewals are treated specially: they don’t count against your Certificates per Registered Domain limit, but they are subject to a [Duplicate Certificate](https://letsencrypt.org/docs/duplicate-certificate-limit/) limit of 5 per week

There is a [Failed Validation](https://letsencrypt.org/docs/failed-validation-limit/) limit of 5 failures per account, per hostname, per hour.
