### ISSUE TITLE
Domain resolving issue leads to freezed panel

### ISSUE THREAD

**Issue by robin98** [hiddify/hiddify-config#372]
شرایطی را فرض کنید که یکی از دامنه یا ساب دامنه هایی که ادمین در بخش Domain تعریف کرده، به هر علتی در Resolve شدن آن مشکلی بوجود بیاد.
حالا این مشکل میتونه بخاطر نقص فنی NS های جایی باشه که دامنه ازش تهیه شده یا حذف شدن ناخواسته دامنه از روی کلادفلر، در هر صورت هر بار که ادمین میخواد وارد قسمت Domain بشه اگه سرور در resolve کردن یکی از دامین ها مشکل داشته باشه، پنل فریز میشه و بخش Domain به هیچ عنوان قابل دسترس نخواهد بود.

در صورتی که ادمین به هر شکلی قادر به بازیابی اون ساب دامین یا دامین نباشه، به نظر میرسه هیچ راهی برای ورود به بخش مدیریت دامنه های هیدیفای و حذف اون دامنه invalid وجود نداره!

**Comment by lumanjre** [comment]
با لینک دایرکت وارد بشین مشکلی نداره
