### ISSUE TITLE
دامین فرانتینگ

### ISSUE THREAD

**Issue by EmperorofWeb** [hiddify/hiddify-config#374]
سلام
با توجه به چیزی که از بحث ها توی گیت هاب گروه متوجه ‌شدم دامین فرانتینگ تو مود TLS قبلا برای کلادفر کار می‌کرده و الان نمی کنه، و با توجه به تست هایی که من کردم (حداقل با اپلیکیشن v2rayNG) تو حالت http اصلن مهم نیست address رو چی وارد میکنیم و در هر حال به host نگاه میکنه 

1. دلیل وجود بخش دامین فرانتینگ در حال حاضر و تو نسخه های جدید پنل چیه؟ 
2. آیا الان سرویسی (شبیه کلادفر) وجود داره که با این روش کار کنه؟ 
3.  اگه نه، آیا جای دیگه ای به غیر از CDN هست که این روش کاربرد داشته باشه؟ 
4.  مورد بعدی اینکه قبلا این بخش قرار بود با استفاده از کلادفر استفاده بشه ولی الان توی تمام کانفیگ هایی که از دامین فرانتینگ استفاده میکنه میاد و ساب دامین دایرکت رو جای host میذاره که عملا حتی اگه کلادفلر هم ساپورت می‌کرد این روش رو، منطقی نیست و باید دامین CDN با دامین فرانتنیگ استفاده بشه
5.  در نهایت تفاوت این قسمت با دامنه Fake که تو بخش دامنه ها تنظیم میشه چیه؟ بهتر نیست این بخش هم به دامنه ها اضافه بشه؟

**Comment by lymanjre** [comment]
دامین فرانتینگ در cdn غیرفعال شده
