### ISSUE TITLE
پیشنهاد برای پروژه

### ISSUE THREAD

**Issue by kaamyaab** [hiddify/hiddify-config#377]
با عرض سلام و وقت بخیر

اول از همه باید بگم دمتون گرم پروژه فوق العاده عالی شده و به خوبی کار میکنه.

پیشنهادی داشتم اگر ممکن بود اعمال بفرمایید.

لطفا در قسمت کاربران دکمه ای طراحی کنید که با کلیک برروی هر یوزر اکانت آن enable یا disable شود. 

مشابه پنل x-ui قابلیت فعال و غیر فعال کردن اکانت کاربر.

**Comment by lumanjre** [comment]
الان این امکان موجوده. حالت را disable کن
