### ISSUE TITLE
مشکل گرفتن سرتیفیکیت روی ساب جدید

### ISSUE THREAD

**Issue by rnj79** [hiddify/hiddify-config#379]
از بخش دامنه ها . ساب جدید اضاف کردم . هم روی حالت دایرکت و هم روی cdn . 

در هر دو حالت ssl نگرفته .

اگر امکان درخواست دستی هم وجود داشت برای زمانی که خودکار بعد از اضاف کردن سرتیفیکیت نمیگیره خوب بود . چون خیلی واجبه وقتی سابموون فیلتر بشه باید فوری اینو حل کنیم

**Comment by sh4msi** [comment]
منم همین مشکل رو دارم
بخاطر این موضوع 3 بار سرور جدید از لوکیشن های مختلف ساختم ولی ...

(ورژن: 16.8)

**Comment by rnj79** [comment]
> فکر کنم شکل این تایپیک #365 هم از همین موضوع حاصل میشه

من تست کردم روی حالت دایرکت به حای https   http زدم .  مشکل نگرفتن ssl هست . حالا توسعه دهنده عزیز اگر ببینه . حتما راه حلی داره . چون توی ورژن های قدیم این بخش مشکل نداشت

**Comment by rnj79** [comment]
**اعمال تغییرات زدم و مشکل ssl حل شد .**

**Comment by sh4msi** [comment]
> **اعمال تغییرات زدم و مشکل ssl حل شد .**

سوال: vpn روشن بود در زمان تست؟
چون من تست زدم باز مشکل پابرجا ست برام
