### ISSUE TITLE
ابر دراک سی دی ان

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#382]
ی مشکلی که هست پنل میاد دامنه هارو از ns checker cloud flare چک میکنه مثلا من ی دامنه با پسوند pw رو بردم تو ابر دراک سی دی ان ست کردم و اونجا و بقیه دی ان اس ها تایید شده ولی کلود فلر بنا به دلایلی ست نشده که این دامنه داخل ابر دراک ست هست !
و به همین دلیل پنل هیدیفای اجازه ثبت اون دامنه یا کار کردن با اون دامنه رو نمیده
لطفا دیفالت چک کردن دی ان اس رو از کلود فلر تغیر بدهید یا حداقل خاموش کنید ممنون

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
