### ISSUE TITLE
مشکل اس اس ال در دامین های جدید | ssl

### ISSUE THREAD

**Issue by sh4msi** [hiddify/hiddify-config#384]
سلام

در زمان اضافه کردن دامین جدید، SSL براش صادر نمیشه
و با فراخوانی ادرس با https پنل لود نمیشه ولی با http بخوبی لود میشه

**از دیروز روی 3 تا سرور مختلف با دامین های مخاف تست کردم**

**Comment by rnj79** [comment]
سلام . اعمال تغیرات بزن  عزیز مشکل حل میشه .

**Comment by sh4msi** [comment]
> سلام . اعمال تغیرات بزن عزیز مشکل حل میشه .

> برای اون سوال دیگت هم که پرسیده بودی . آره فیلترشکن روشن بود

خاموش کن و دوباره تست کن، احتمالا باز پنل برات بالا نمیاد (قبلا تستش کردم)

**Comment by rnj79** [comment]
> > سلام . اعمال تغیرات بزن عزیز مشکل حل میشه .
> 
> > برای اون سوال دیگت هم که پرسیده بودی . آره فیلترشکن روشن بود
> 
> خاموش کن و دوباره تست کن، احتمالا باز پنل برات بالا نمیاد (قبلا تستش کردم)

خب این دیگه ربطی به ssl نداره . مربوط به فیلتر بودنه . پنل ها xui منم بدون فیلتر شکن بالا نمیاد ولی کار میکنن

**Comment by sh4msi** [comment]
![image](https://user-images.githubusercontent.com/6229984/224020502-12d0cdc0-c4f1-4ee9-b9f9-7a0c9e64ea2c.png)

دامین و سروری که دارم تست میکنم دیروز تهیه شدن و هر دو تمیز هستن و تا حالا هیچ استفاده ازش نشده

**Comment by sh4msi** [comment]
به هر حال ممنون ازتلاشتون برای کمک 
باز اگه به نتیجه ی رسیدم در ادامه همین تایپیک مینویسم

**Comment by rnj79** [comment]
خب عزیز میگم که شما تست کن با آیپی سفید جواب میده . 

مهم اینه که داره جواب میده .

 این ربطی به ssl نداره ولی چون تا قبل اعمال تغییرات زدن برای من مشکل ssl میداد اما بعد دیک حل شد

**Comment by rnj79** [comment]
یک چیز دیگه رو محدود کردن احتمالا . پینگ میدن آیپی ها 

با یک روش گرفتن ssl برای آیپی سنگاپورم اوکی هست بدون فیلترشکن حتی . ولی با آیپی آلمان هتزنر باید با فیلترشکن وارد پنل بشم . 

تست پینگ . مبتدی ترین تست هست
تست tcp و ..... هم هست

**Comment by avtak** [comment]
> سلام
> 
> در زمان اضافه کردن دامین جدید، SSL براش صادر نمیشه و با فراخوانی ادرس با https پنل لود نمیشه ولی با http بخوبی لود میشه
> 
> **از دیروز روی 3 تا سرور مختلف با دامین های مخاف تست کردم**

برا منم نمیشد از طریق خوده وبسایت اعمال تغیرات میکردم. از خود ssh دوباره ری اینستال کن درست میشه.
