### ISSUE TITLE
504 Error on Arvan‌cloud / Secure Connection Failed on Cloudflare

### ISSUE THREAD

**Issue by elrazez** [hiddify/hiddify-config#387]
از دیشب کانفیگ‌ها رو با سرورهای مختلفی تست کردم و کلا لینک پنل و کانفیگ‌ها **روی بعضی اینترنتا مثل سابق کار می‌کنه** و روی بعضی اینترنت‌های دیگه، اگر روی کلادفلر باشیم ارور secure connection failed و اگر روی آروان باشیم ارور 504 می‌گیریم.

بنظرتون مشکل از چی می‌تونه باشه؟ آیا IP روی اون اینترنت‌ها بن شده که اینطوری می‌شه؟

**Comment by elrazez** [comment]
اوکی مشکل اینه که پورت ۴۴۳ رو بستن روی بعضی از اینترنت ها. با پورت ۸۰ کار می‌کنه.
وات د فاک؟!

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
