### ISSUE TITLE
CDN configs on clash are slow compared to xray and v2ray clients

### ISSUE THREAD

**Issue by Hadi-1624** [hiddify/hiddify-config#39]
Hi there
My issue possibly might be out of the scope of this project.
Using clash on windows, (clash core and clash meta core), my ping to my cdn configs are very high (1300MS) and my connection is very unstable.
Using nekoray and v2rayn on windows, (xray core and v2fly), My cdn configs work very well and have a good ping and i have a very stable connection.

Hidify is on ubuntu 22 LTS, I am using Arvan cloud.

**Comment by hiddify** [comment]
Would you please https://sshkit.com/subconverter/ to convert the config to clash and test again?

**Comment by Hadi-1624** [comment]
Hello, is there an alternative way of converting?
I prefer not to use  that, in case they store my proxy details
