### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by khashayar5** [hiddify/hiddify-config#391]
یکی از مواردی که خیلی به نظرم مهم امد وقتی می خواییم یک دامنه را به صورت مستقیم ادد کنیم (ای پی 4 دوم سرور را در کلود اضافه کردیم بدون پراکسی) پنل امکان شناسایی ای دوم را ندارد و همیشه مقیاسش ای پی اول سرور و ارور میده

**Comment by robin98** [comment]
وقتی اولی اضافه شد برو کارت شبکه اولی رو غیرفعال کن و یبار سرور ریبوت بزن بعدش منطقا فقط با ای پی دوم میاد بالا، حالا دوباره داخل پنل بشو و اینبار آی پی دوم رو کاراشو انجام بده. در نهایت دوباره کارت شبکه اول رو فعال کن.
البته بازم احتمال داره وقتی پنل ریستارت بشه دوباره با ای پی اول چک کنه و دامنه دومی رو نشناسه.
حالا همین ایده رو تست کن فعلا به نظرم.

**Comment by ALIRA1** [comment]
یه قابلیتی که به نظرم خیلی حیاتی هست اینه که هر شب قبل از آپدیت یه بکاپ از پنل گرفته بشه به صورت خودکار و به ایمیل کاربز ارسال بشه اینطوری دیگه حتی با آپدیت مشکل دار هم کاربر بکاپ رو داره 
در کل گزینه بکاپ خودکار خیلی لازمه برای سیستم

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
