### ISSUE TITLE
No Http Connections for "Fake" Configs

### ISSUE THREAD

**Issue by elrazez** [hiddify/hiddify-config#398]
There is no HTTP (80 port) Fake CDN connections even tho i turn http connections on and the http fake cdn proxy check-boxes are also marked; only 443 ones. please fix this.

fyi, almost nothing works anymore except vmess and vless on fake sni connections.

**Comment by lymanjre** [comment]
Yo know fake SNIs may not work on any networks or any situation. You need to try other proxies
