### ISSUE TITLE
installation Error :ERROR!!!! There is an error in the installation of python panel. Exit....

### ISSUE THREAD

**Issue by ishark2022** [hiddify/hiddify-config#402]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره

**Comment by ishark2022** [comment]
سلام لینک نصب دوباره خرابه ..ای بابا
