### ISSUE TITLE
دانلود و آپلود فایل

### ISSUE THREAD

**Issue by javidizadi** [hiddify/hiddify-config#403]
نظرم اینه که برای کسایی که سرور خریداری می کنند و تمایل دارند استفاده مفید تری از سرور داشته باشند قابلیتی به پنل اضافه بشه که بشه از طریق پروتکل هایی مثل rsync یا ftp یا http همراه با مسیر مبهم و احراز هویت فایل روی سرور ذخیره کرد و آن ها را دانلود کرد.

**Comment by lymanjre** [comment]
دوست عزیز این قابیت ربطی به کارکرد پروکسی سرور نداره و از حوزه فعایت ما خارجه
