### ISSUE TITLE
ERROR!!!! There is an error in the installation of python panel. Exit....

### ISSUE THREAD

**Issue by mqnew** [hiddify/hiddify-config#405]
مشکل در نصب سرور هزتزنر و دیجیتال اوشن

**Comment by sattar62** [comment]
همین مشکل در digitalocean.com
Ubuntu 22.04 and Ubuntu 20.04

**Comment by Mobinoo1383** [comment]
بنده هم این مشکل رو دارم

**Comment by ishark2022** [comment]
سلام .. منم مشکل داشتم نوشتم ولی متاسفانه ادمین بجای حل مشکل آنرا پاک میکند !!!

**Comment by GoldenOne1** [comment]
پس این مشکل کی بررسی میشه؟
