### ISSUE TITLE
مشکل در دامنه و اضافه کردن دامنه

### ISSUE THREAD

**Issue by Dariushg75** [hiddify/hiddify-config#407]
سلام.

در قسمت دامنه ها، تمام ساب دامنه های آی پی هاشون None شده ولی دارم روی همون ساب دامنه ها پینگ میگیرم و وصل میشم به وی پی ان ها.

و اینکه ساب دامنه هم نیمشه اضافه کردن با اینکه AA رکورد به آی پی سرور وصل هستش ارور میده.

![Screenshot 2023-03-10 164725](https://user-images.githubusercontent.com/44521775/224455230-9679d1a0-2a3e-4bd6-8e08-eb3cf20426dd.png)

**Comment by Dariushg75** [comment]
مشکل از دامنه های .xyz هستش،
قبلا درست بود اما پنل که آپدیت شده به مشکل خورده. لطفا فیکس کنید.
ممنون

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
