### ISSUE TITLE
عمل نکردن حالت disable برای کاربر

### ISSUE THREAD

**Issue by aminzeidi** [hiddify/hiddify-config#408]
چند تا مورد بود که من چندین بار چک کردم و دیدم اشکال وجود داره
1- وقتی محدودیت حجم برای کاربر تنظیم کردم اما با اتمام حجم لینکها همچنان برای کاربر فعال بودن و از پروکسی استفاده میکرد
2-  با اتمام مهلت زمانی باز هم لینکها برای کاربر فعال بودن
3- کاربر رو بصورت دستی رو حالت disable قرار دادم اما باز هم لینکهای پروکسی برای کاربر فعال بودن
4- تنها راه برای غیر فعال کردن حذف کاربر از پنل ادمین بود.

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
