### ISSUE TITLE
بکاپ گیری کامل از پنل

### ISSUE THREAD

**Issue by danyalfa79** [hiddify/hiddify-config#410]
با درود و احترام
لطفا امکان بکاپ گیری کامل از سرور (شامل سکرت ادمین و تمام مواردی که برای کپی کردن پنل روی سرور جدید نیاز هست) رو اضافه کنید که در صورت اتمام اشتراک سرورمون نیاز به تنظیمات مجدد نداشته باشیم و با همون فایل بکاپ بتونیم همه موارد رو ریستور کنیم

**Comment by hiddify1** [comment]
الان هست دیگه
