### ISSUE TITLE
بازن شدن دامنه بودن https

### ISSUE THREAD

**Issue by masoudshabani1992** [hiddify/hiddify-config#411]
سلام چرا دامنه های direct بدون https باز میشن ؟
چرا ssl فعال نمیشه ؟

**Comment by zoheirkabuli** [comment]
اره سوال منم هست

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره

**Comment by premier213** [comment]
مشکل داره با آخرین ورژن
