### ISSUE TITLE
ssl cdn irani

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#413]
درود اگر ابر روشن باشد اس اس ال سی دی ان داخلی مثل ابر دراک صادر نمی شود 
دکمه اعمال تغیرات در پنل تحت وب کار نمیکند (در کامند لاین کار میکند)
موقع اضافه کردن دامین جدید در بخش دامنه ها چک ایپی درست کار نمیکند و به جای ایپی سی دی ان را ریسالو کردن ایپی سرور اصلی را ریسالو میکند و ارور ایپی یکسان می دهد
خروجی در نهایت به جای اینکه @address دامین سرور اصلی باشد جایش با sni اشتباه می شود و باید دستی در بخش سی دی ان ایپی هارو عوض کرد

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
