### ISSUE TITLE
استفاده از هیدیفای و هاست وب سایت دیگری همزمان

### ISSUE THREAD

**Issue by Mysteryexe** [hiddify/hiddify-config#414]
با سلام من الان هیدیفای رو نصب کردم و کار میکنه ولی مشکلی که هست اینه که هاست apache من رو کامل قطع کرده و دامنه اصلیم ویکیپدیا رو میاره
میشه لطفا راهنمایی کنین؟

**Comment by hiddify1** [comment]
نوشتیم تداخل داره دیگه
