### ISSUE TITLE
Dokerized version

### ISSUE THREAD

**Issue by Heshmatkhah** [hiddify/hiddify-config#42]
Hi
Can you please provide a docker image for this package?
A sample docker-compose.yml also will be grate

**Comment by hiddify** [comment]
the problem is that there is a big dependencies between services. As the goal of docker is having micro-services, it will be problematic.

How ever we will prepare a version that can be run in Docker ;)

**Comment by hiddify** [comment]
Done!
But not in a correct way. it has just ported to be used in Docker.
Please test it and let us know

use `docker-compose up -d`
