### ISSUE TITLE
Error on low-quality server with clash-server component: 'This program can only be run on AMD64 processors with v3 microarchitecture support'

### ISSUE THREAD

**Issue by b3hr4d** [hiddify/hiddify-config#422]
Hi,

Thanks for the great project and your incredible work.

After installing the software on a low-quality server, I encountered an error with the clash-server component:

`This program can only be run on AMD64 processors with v3 microarchitecture support.`

After doing some research, I found a solution that involves checking the CPU for compatibility with the AVX2 instruction set. If it is not compatible, download a compatible version of the clash-server component.

Here is the solution I used:

```
pkg=$(dpkg --print-architecture)

version="v1.14.2"

filename="clash.meta-linux-$pkg-$version.gz"

if grep -q avx2 /proc/cpuinfo; then
    echo "CPU is compatible with AVX2"
else
    echo "CPU is not compatible with AVX2"
    filename="clash.meta-linux-$pkg-compatible-$version.gz"
fi

wget -c https://github.com/MetaCubeX/Clash.Meta/releases/download/$version/$filename

gunzip -f clash.meta-linux-*
mv clash.meta-linux-* clashmeta
chmod +x clashmeta

ln -sf $(pwd)/clash-server.service /etc/systemd/system/clash-server.service
```
This code checks the CPU for compatibility with the AVX2 instruction set, downloads a compatible version of the clash-server component if necessary, and creates a symbolic link for the clash-server service file.

I believe this solution would be helpful for other users who may encounter a similar issue on a low-quality server, and it would be great if this code could be added to the appropriate file to make it easier for other users to implement.

Thank you so much for your attention and participation.

Best regards.

**Comment by hiddify1** [comment]
thanks added ;)
