### ISSUE TITLE
حدف دسته جمعی کانفیگ ها 

### ISSUE THREAD

**Issue by sirvan1133** [hiddify/hiddify-config#427]
وقتی چند تا کانفیگ و انتخاب میکنی نمیتونی حذف کنی ، یعنی وقتی حذف و میزنی حذف نمکینه

**Comment by sajadzi** [comment]
حذف میشه ولی یکم طول میکشه سعی کن بیشتر از 10 تا با هم حذف نکنی

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره

**Comment by sajadzi** [comment]
بله درست شد
