### ISSUE TITLE
google chart

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#429]
![image](https://user-images.githubusercontent.com/52799129/224546768-3345f8ac-3e26-4c7e-acf6-c317fd4d375a.png)
![image](https://user-images.githubusercontent.com/52799129/224546789-9893718a-19e7-4026-a88b-2101a2b201bd.png)
 لود نمیشود ، همه چیز صفر نصب کردم و سرور تازه و خشک هست

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
