### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by just1random** [hiddify/hiddify-config#43]
Thank you!
This project is an excellent contribution towards freedom and should not be unnoticed.
I made this issue to say "thank you" for your efforts. I hope this motivates you (even a little bit) to continue helping thousands (and hopefully millions of people).

_- From myself and many more using hiddify to access the free internet._

**Comment by Hadi-1624** [comment]
I would also like to show my appreciation for the project as well.
The more people use it, more people will have access to the free internet and there will be more properly configured  servers, less chanse of servers being detected or  users data being stolen.

**Comment by hiddify** [comment]
Thank you a lot for your support.

We hope more people join this project and help Iranians to access free internet

**Comment by Sn97sn** [comment]
Absolutely brilliant work
