### ISSUE TITLE
cdn iran

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#432]
اصلا با سی دی ان های داخلی ssl مشکل داره پنل نه خودش اس اس ال میگیره نه اس اس ال سی دی ان رو استفاده نمیکنه
 ابر اروان ، ابر دراک تست شدند و همین مسِله بوده

**Comment by ramtin18** [comment]
با کلود فلر اس اس ال بگیر بعد چنج کن رو ابر اروان cdn رو

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
