### ISSUE TITLE
برای جلوگیری از فیلترشدن آی پی چه کنیم؟

### ISSUE THREAD

**Issue by sajjadasg** [hiddify/hiddify-config#435]
باسلام خدمت همه دوستان چهت فیلتر نشدن ای پی چیکار کنیم
سی دی ان ابراروان استفاده میکنم.
پیشنهادتون برای سی دی ان کدامه.هم داخلی هم خارجی.
لطفا راهنمایی کنید 
ممنون

**Comment by ahaddiba** [comment]
سلام فقط کانفیگ های پشت cdn استفاده کنید ! بهترین cdn برای این سرویس با وجود محدودیت ها همون cloudflare

**Comment by sajjadasg** [comment]
سی دی ان برا ای پی ۴ یا ۶
و اینکه وقتی تو کلادفلیر میبرم سرعتش خیلی کم میشه شایدم کلا کار نکنه
راهکاری هست ک بتونیم از اون استفاده کنیم؟ممنون

**Comment by ahaddiba** [comment]
برای هر دو کار میکنه ! کار میکنه اما شما باید یا از IP تمیز استفاده کنید یا سایت هایی که از cloudflare استفاده میکنند ! مثل discord.com

**Comment by saeedbah** [comment]
من وقتی تیک پروکسی دامنه رو داخل کلوفلر میزنم به هیچ وجه با همراه اول کار نمی کنه. آی پی تمیز کلودفلر برای همراه اول اصلا نتونستم پیدا کنم. راه حلی هست به نظرتون؟
