### ISSUE TITLE
مشکل duplicate

### ISSUE THREAD

**Issue by AminB3DA** [hiddify/hiddify-config#438]
سلام. پروفایل هیدیفای رو ک وارد گوشی یا سیستم میکنم ارور proxy (xxxx) is duplicate name میده
جای xxxx اسم سرور مینویسه مثلا tls_h2_WS_direct_trojan
هربار هم خاموش میکنم از تو پروکسی اون موردا بازم ب یکی دیگش گیر میده و میگ دوپلیکیت شده

**Comment by neoshisystem** [comment]
منم همین مشکل رو دارم

**Comment by behiunforgiven** [comment]
منم همین مشکل رو دارم

**Comment by IR4N0nY** [comment]
این مشکل رو منم هم در اپ ویندوزی دارم

**Comment by mohammadrezakarimi78** [comment]
من هم این مشکل را دارم
proxy http_ws_direct_vless http only 80 is the duplicate name

**Comment by behiunforgiven** [comment]
> برای حل موقت در قسمت دومین ها بیشتر از دوتا دومین قرار ندید یکی فیک یکی اصلی پشت CDN
 به صورت پیش فرض خودش ۳ تا فیک گذاشته،‌ روی speedtest و soft98 و www.canva.com
 
 کدوم رو پاک کنم؟
