### ISSUE TITLE
Fake CDN concept clarification

### ISSUE THREAD

**Issue by smf8** [hiddify/hiddify-config#44]
Hi

In fake CDN documentation, you mentioned that it's mandatory to **disable** CDN proxying. By doing so, we're only using CF or Arvan as a simple DNS server and nothing more since its only job is to resolve `fake-cdn.domain.com` to `my ip`. I'm having trouble understanding the "fake CDN" concept here.

**Comment by hiddify** [comment]
Exactly this is the case,

However, we are trying to simulate other sites that are using cloud flare.
(it is not important to make it off or on) 
If cloudflare receive a request it will forward it to your server, no difference whether  it is on of off
