### ISSUE TITLE
کاسومایز کردن بخش دامین ها

### ISSUE THREAD

**Issue by xmohammad1** [hiddify/hiddify-config#440]
سلام من یه دوتا ایده دارم برای اپدیت بعدی اولی تغییر اسم کانفیگ ها برای هر دامنه جدا باشه  مهم هست که مثلا بنویسیم این کانفیگ با این دامنه چه مواقعی بهتر هست که استفاده بشه یا کاربردش چیه ، بعد این که یه قابلیت دیگم که خیلی خوبه اضافه بشه چون من از چندتا cdn  استفاده میکنم مثلا یک سری از کانفیگ ها ممکنه روی اون cdn جواب نده ، بشه انتخاب کرد که مثلا این دامنه که مال cdn فلان هست این مدل از کانفیگ ها روش فعال باشه و اون دامنه دیگه یه سری دیگه

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
