### ISSUE TITLE
تک کاربره!!!

### ISSUE THREAD

**Issue by amirmhs58** [hiddify/hiddify-config#443]
سلام

آیا هر یوزر که ساخته میشود تک کاربره است یا همزمان چندین کاربر از آن یوزر ساخته شده میتوانند استفاده کنند؟
من خیلی سرچ کردم در این مورد چیزی درون سوال و جواب ها و خود برنامه پیدا نکردم.

ممنون

**Comment by NikanMirH** [comment]
یه تاپیکی بود کامل توضیح دادن که چرا تک کاربره نمیشه، و خب در حال حاضر محدودیتی برای اتصال وجود نداره

**Comment by lymanjre** [comment]
تک کاربره کردن کانفیگها به دلیل اینکه همه از یک آیپی پشت cdn به سرور میان ممکن نیست
