### ISSUE TITLE
اشتباه املایی در فضای کاربری فارسی

### ISSUE THREAD

**Issue by kiavash599** [hiddify/hiddify-config#445]
برای سیستم عامل iOS اپلیکیشن Stash و **_شدولینک_** یک اپ بسیار عالی است اما غیر رایگان است؛ به نظر ما برای استفاده از پروکسی هوشمند ارزش خرید دارد.

که باید  به صورت زیر باشد

برای سیستم عامل iOS اپلیکیشن Stash و **_شدوراکت_** یک اپ بسیار عالی است اما غیر رایگان است؛ به نظر ما برای استفاده از پروکسی هوشمند ارزش خرید دارد.

**Comment by lymanjre** [comment]
انجام شده

**Comment by kiavash599** [comment]
انجام نشد همچنان ایراد پابرجاست
