### ISSUE TITLE
Waze not working when connected to clash or hiddify app

### ISSUE THREAD

**Issue by miladmeidanshahi** [hiddify/hiddify-config#446]
I don't know what happens when connecting to clash or hiddify app waze not connecting to the server.

**Comment by freeforlife-star** [comment]
سلام
آره منم این مشکل رو دارم
وقتی در‌نرم افزار Shadowrocket رو حالتی که سایت های غیر فیلتر به صورت مستقیم وصل بشن ، متصل میشم ، Waze دیگه کار‌نمیکنه و باید Local Rule رو از حالت lite.conf رو حالت normal.conf بزارم تا کار‌کنه
ممنون میشم چک بفرمایید 🙏🏻

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
