### ISSUE TITLE
باگ در ریست حجم

### ISSUE THREAD

**Issue by yakoza021** [hiddify/hiddify-config#447]
سلام یک اکانت به صورت ریست حجم روزانه ساختم برای تست و مقداری ازش استفاده کردم
وفردای ان روز باید دوباره حجم رو 0 میکرد ولی نکرد و از ادامه حجم قبلی اضافه کرد
به نظرم باگ داره این حالت و حجم رو 0 نمیکنه هروز

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
