### ISSUE TITLE
خطا در زمان ساخت پروفایل در کلش و برنامه هایدی فای پروکسی از طریق لینک

### ISSUE THREAD

**Issue by Sky13944** [hiddify/hiddify-config#448]
وقت بخیر من امروز  مجدد هایدی فای رو روی سرور نصب کردم. وقتی می خواهم کانکشن
![Screenshot_۲۰۲۳-۰۳-۱۴-۱۱-۰۱-۵۵-۱۰۸_com hiddify hiddifyproxy meta](https://user-images.githubusercontent.com/119528914/224930325-5250db21-72f5-48ac-b3a8-52d4cfbbbf2c.jpg)
 ها رو از طریق لینک سابسکرایب به برنامه کلش یا هایدی فای پروکسی منتقل کنم با خطا مواجه می شم. لطفا بررسی بفرماید

**Comment by IR4N0nY** [comment]
برای حل موقت در قسمت دومین ها بیشتر از دوتا دومین قرار ندید یکی فیک یکی اصلی پشت CDN

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
