### ISSUE TITLE
donation 

### ISSUE THREAD

**Issue by aliraza7926** [hiddify/hiddify-config#45]
if you can add Dogecoin it would be very nice

**Comment by hiddify** [comment]
Thank you for your support.
It is the Doge address: `DJy27pQKwnhaRxWDbU6dG7UdHHif6yp8Jb`
However, it is really hard to have many and many coins ;)

**Comment by aliraza7926** [comment]
I know but it's dogecoin and people like me who don't have money could show their appreciate
