### ISSUE TITLE
تشکر از فعالیت شما عزیزان

### ISSUE THREAD

**Issue by IR4N0nY** [hiddify/hiddify-config#450]
**تشکر**
با سلام خدمت شما عزیزان
صمیمانه از شما دوستان عزیز تشکر میکنم که با وجود کم توجهی به فعالیت شما واقعا دارید پیشرفت میکنن و درجهت دسترسی آزاد به اینترنت ملت ایران تلاش میکنید.

**پیشنهاد**
چند نکته بود که میخواستم باهاتون درمیون بذارم
1- اینکه سعی کنید به شکل برنامه ریزی شده و اولیت بندی کاراهارو پیش ببرید و سعی نکنید همه کارهارو با هم انجام بدید اولیت اول شما باید روی کار اصلی پروژه یعنی اصل فیلتر شکن باشه بعد در مرحله بعدی یوزر و کارهای جانبی. من با اینکه کل کارهارو به شکل درست انجام دادم و ای پی و دامین تمیز استفاده کردم ولی به شدت سرعت پایین هستش و قلبا از شما دوستان خیلی بیشتر از این ها انتظار دارم
2- من خودم از روش Reverse Proxy روی Nginx و با پنل Xray همراه با مدیریت کاربران استفاده میکنم و به شدت سرعت بالایی داره و مشکلی در اتصال کاربران نیست. خواستم اگر امکانش هست این مورد رو هم به قابلیت های **هیدی فای** اضافه کنید چون واقعا کاربردی هستش.
3- بازم تاکید میکنم که اولیت اصلی باید روی خود کار اصلی سیستم یعنی گذر از فیلتر باشه بعدش روی باقی موارد مانور بدید. تجربه خوبی داشتم با پنل ولی مشکلات کوچیک حل نشده توی هر قسمت کار رو برای من سخت میکنه ولی ناامید نیستم و منتظر آپدیت های بعدش ما در جهت بهبود کیفیت و ارتقاء اتصالات هستم.

موفق و پیروز باشید.

**Comment by mygit28** [comment]
سلام ضمن تشکر از تیم هیدیفای موردی که منم دوست داشتم کنار توضیحات دوستمون اضافه کنم این موضوع هست که به نظرم تیم بیش از اندازه به فکر اضافه کردن آپشن های بی استفاده یا کم استفاده مطابق نظر کاربرا هست و یک جورایی میخواد همه راضی باشن که غیر ممکن هست و باعث میشه که پروژه از هدف خودش دور بشه و وقت توسعه دهندگان گرفته بشه، به نظرم بیشتر روی همین امکانات فعلی و بهتر کردن یا رفع باگ همین موارد کار کنن تا اضافه کردن اپشن های زیاد و برای استفاده های خاص ...

**Comment by arman2012** [comment]
کاملا موافقم امکانات فعلا خوبه از بقیه هم بیشتره رفع باگ خیلی بهتر

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
