### ISSUE TITLE
آپدیت نشدن حجم مصرفی

### ISSUE THREAD

**Issue by arman2012** [hiddify/hiddify-config#454]
متاسفانه روی دو سروری که بنده دارم و تست شده کاربر ها حجم مصرفیشون اصلا آپدیت نمیشه حتی هر ده دقیقه بنده هر سه ساعت خودم باید بزنم آپدیت بشه که یه سری بیشتر از حد مجازی مصرف کردن.   و اینکه وقتی کسی بیشتر از حجم مجاز مصرف کنه اگر قطع نشه بازم میتونه مصرف کنه

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
