### ISSUE TITLE
وصل نشدن با دومین CDN

### ISSUE THREAD

**Issue by amirseifi** [hiddify/hiddify-config#455]
سلام
من دو تا  ساب دومین روی کلود فلیر ساختم یکی پروکسی و یکی هم بدون پروکسی

روی ساب دومین بدون پروکسی ( دایرکت  ) وصل میشم و مشکلی نداره و لی روی ساب دومین که پروکسی فعال  هست ( cdn)   وصل نمیشه
لطفا راهنمایی کنید
من راهنمای تنظیمات هم دیدم و عینا انجام دادم ولی نشد

**Comment by saeedbah** [comment]
من دقیقا همین مشکل رو روی همراه اول دارم.
ایرانسل هم برعکس، بدون cdn کار نمیکنه.
بقیه اپراتور ها اوکی تر هستن.
احتمالا همراه اول روی کلودفلر اختلال ایجاد کرده، چون هر رنج آی پی که اسکن کردم هم جواب نداد.

**Comment by maliohammad** [comment]
من ايرانسل و ايرانسل tdlte دارم و هردو مشكلی با cdn كلودفلر دارن

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
