### ISSUE TITLE
نحوه تغییر ip

### ISSUE THREAD

**Issue by vahidabbasi77** [hiddify/hiddify-config#458]
با سلام در صورت تغییر ip سرور به دلیل مسدود شدن یا دلایل دیگر با چه روشی میشه ip جدید رو اعمال کرد که اطلاعات کاربران حفظ بشه

**Comment by Ehsanshamsseir** [comment]
بهترین کار به نظرم اینه که شما در منوی پشتیبان گیری یه فایل بکاپ تهیه کنید بعد خیلی ساده رو سرور جدیدتون مجددا نصب انجام بدید بع توی همین منو فایل بکاپتونو انتخاب کنید و همه ی تسک های زیرشو بزنید اینجوری کاربر هایی که از dns استفاده میکردند بدون هیچ تغییری به سرور جدید متصل میشند

**Comment by lymanjre** [comment]
بکاپ بگیرید روی سرور جدید ریستورکنید. از بکاپهای خودکار سیستم هم میتونید استفاده کنید
