### ISSUE TITLE
بک اپ گیری از اطلاعات کاربران

### ISSUE THREAD

**Issue by vahidabbasi77** [hiddify/hiddify-config#459]
با سلام لطفا این امکان رو ایجاد کنید که بشه از اطلاعات کاربران بک اپ گرفت و قابلیت ریستور هم وجود داشته باشه که در صورت مشکل از یک سرور به سرور دیگر وارد بشه ولینک هایی که قبلا برای کاربران ارسال شده کار کنه همچنان

**Comment by Ehsanshamsseir** [comment]
این امکان همچنان وجود داره تو منای پشتیبان گیری

**Comment by Niutish** [comment]
سپاس از زحمات شما و خسته نباشید 
مشکل با بازگردانی کاربران دارم ورژن 7.1.3 
کاربرها موقع ری استور کردن بر نمیگردن و فقط بالای صفحه تعداد کار بران رو نکایش میده یک ماه پیش سرور رو انقال دادم بدون مشکل کار کرد ای مورد الان هر کاری میکنم نمیشه راهنمایی بفرمایید
