### ISSUE TITLE
ارور در کلش

### ISSUE THREAD

**Issue by mmpma** [hiddify/hiddify-config#460]
سلام و درود
کلش بنده کار نمیکند و همچنین اروری دارم.
haproxy                        active                         
hiddify-xray                   active                         
hiddify-nginx                  active                         
hiddify-panel                  active                         
ss-v2ray                       inactive                       
ss-faketls                     inactive                       
shadowtls                      active                         
clash-server                   failed                         
netdata                        active

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
