### ISSUE TITLE
تاخیر در اتصال یا دریافت ارور در ماتسوری

### ISSUE THREAD

**Issue by mmpma** [hiddify/hiddify-config#461]
سلام و درود
در اپ ماتسوری یا با تاخیر وصل می شود و تست کانکشن نمیدهد یا کلا وصل نمیشود.
در چند گوشی تست شده است

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره.  اگه ح نشد احتمالا مشکل از اپ کلاینت باشه
