### ISSUE TITLE
تکمیل صحیح تنظیمات مالتی سرور و تعیین پنل مادر

### ISSUE THREAD

**Issue by ifahmideh** [hiddify/hiddify-config#462]
سلام وقت بخیر.
در تنظیمات پنل، قسمت پیشرفته، فیلد مالتی سرور چطور باید تکمیل بشه؟

من آدرس پنل ادمینی که میخوام به عنوان پنل مادر باشه رو وارد می‌کنم اما خطای عدم اتصال به پنل مادر میده.

ممنون میشم راهنمایی کنید.

**Comment by lymanjre** [comment]
عزیز هنوز رییز نشده . بعد از رییز این قابلیت فعال میشه
