### ISSUE TITLE
مشکل در هنگام بازگرداندن بک آپ

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#464]
موقع بازگرداند بک اپ به سرور زمان تمام کاربران رو به 184 رو به صورت پیش فرض تغیر میدهد 
درحالیکه مثلا 1 کاربر 15 روز یکی 24 روز و ... زمان داشتند

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
