### ISSUE TITLE
اتوماتیک بک اپ

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#465]
و همچنین اضافه کردن قابلیت اتوبکاپ هر 24 ساعت ایده ی بدی فکر نمیکنم باشه 
مثلا هر x ساعت از پنل بک اپ بگیره و توی گوگل درایو یا پوشه ای تو سرور هر طور که ممکن باشه بک اپ بگیره از اطلاعات

**Comment by lymanjre** [comment]
انجام شده دست عزیز
