### ISSUE TITLE
پایداری

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#467]
پایداری پنل در نسخه پایدار مهم ترین نکته است 
از شما بابت توسعه این پنل متشکرم ، طبق تجربه چندین ماهه من مهم ترین نکته پایداری و محاسبات صحیح در پنل هست سپس اضافه کردن فیچر جدید
با تشکر

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
