### ISSUE TITLE
Reality protocol

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#468]
با عرض سلام و خسته نباشید لطفا در صورت امکان پروتکل reality را به نسخه ریلیز اضافه کنید تا تست بشه و به بهترین حالت ممکن ازش استفاده کنیم تا در صورت پایداری و رفع نقص و اضافه کردن فیچر ها به جهت به کمال رساندن ان ان را به نسخه پایدار در نهایت اضافه کنید 
سایه عالی مستدام

**Comment by lymanjre** [comment]
پس از ریلیز رسمی اضافه خواهد شد. فعلا این این کار را نمی کنیم.
