### ISSUE TITLE
جداسازی سرور در سه لایه Core و API و UI

### ISSUE THREAD

**Issue by mkvpn1001** [hiddify/hiddify-config#471]
سرور باید بصورت مجزا در سه لایه جدا از هم باشد :

Core : هسته اصلی که همون  ایکس ری و ملزوماتش هست که بصورت جداگانه نصب میشه و آپدیت میشه و عیب یابی میشه
API : واسطی که با هسته ارتباط برقرار میکنه
UI: رابط گرافیکی یا کامند لاین یا هر چیزی که بوسیله ای پی آی به هسته ارتباط برقرار میکنه

وقتی اینا بصورت مجزا باشند مثلا من میتونم خیلی راحت رابط گرافیکی خودمو بنویسم و شاید از رابط های گرافیکی غیره استفاده کنم 
همه چی مجزا نصب بشه - مجزا آپدیت بشه - مجزا عیب یابی بشه 
این جوری دست خیلی بازه

**Comment by hiddify1** [comment]
درست میفرماید و من خودم اون معماری را بیشتر می پسندم
اما یه مشکلی هم هست
ما سعی کردیم از کامپوننت های آماده استفاده  کنیم که سریع تر کار راه بیافته و اگه اینکارو بکنیم پیچیدگی کد بیشتر میشه
