### ISSUE TITLE
مصرف ترافیک

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#474]
در کنار نمودار مصرف حجم در لحظه ایده بدی نیست که حجم دانلود و اپلود مصرف شده در 24 ساعت اخیر
در یک ماه اخیر
از ابتدا تا به این لحظه 
این مصارف ترافیک هم اضافه بشه ، برای مدیریت ترافیک خیلی خوبه تا هزینه هارو بشه براورد کرد

**Comment by robin98** [comment]
متاسفانه netdata با اونهمه نمودار و مانیتورینگ از چنین قابلیت ساده ای بی بهره هست! در مورد پکیج nvstat سرچ کنید و روی سرور نصبش کنید تا به خواستتون برسید

**Comment by realartin** [comment]
x-ui 
که پیش پا افتاده ترین پنل هست دیفالت این رو داره

**Comment by hamed121221** [comment]
سلام . من یه مشکلی دارم .یه vps لینوکس گرفتم و روش x-ui رو نصب کردم . vpn سرور هم میسازم .جواب هم میده و کار میکنه اما خیلییییی حجم اینترنت رو مصرف میکنه .مثلا یه فایل 200 مگابایتی 2 گیگ با وی پی ان محاسبه میشه . مشکل چیه؟ سروری که گرفتم 500 مگ رم داره و یه سی پی یو 2.6Gh داره و 6 گیگ حافظه

**Comment by lymanjre** [comment]
در آپدیت جدید این داستان عوض شده. آپدیت جدید را چک کنید لطفا.
