### ISSUE TITLE
راهنمایی در خصوص کانفیگ برای ایرانسل

### ISSUE THREAD

**Issue by sohrab98** [hiddify/hiddify-config#475]
با سلام
دوستان من همه کانفیگ ها رو با پروتوکل های مختلف تست کردم رو همراه اول عالیه تا صد مگ هم کشیدم ازش اما ایرانسل افتضاح 
شما با چه پروتوکلی سرعت خوب گرفتید رو ایرانسل؟

**Comment by robin98** [comment]
مشکل از آی پی هست. از بخش disscusions آموزش پیدا کردن آی پی تمیز کلادفلر رو دنبال کنید و همون متد رو پیاده کنید.

**Comment by GameOver61** [comment]
حالا واسه من برعکسه.از پنجاه تا کانفیگ نود درصدشون روی ایرانسل جواب میده اما روی همراه اول  تنها دوسه تا از کانفیگا کارمیده اونم پینگش بالاست..روی ایرانسل vmess ws  و trojan grpc .این دوتا که صد درصدمطمعنم کارمیدن

**Comment by ashkanbagheri** [comment]
مشکل از تغییرات خودکار تنظیمات apn در داخل گوشی هست apn اصلی رو حذف کنید به صورت دستی apn جدید تعریف کنید اوکی میشه ولی بعد از چند ساعت دوباره اوپراتور به صورت خودکار تنظیمات apn رو عوض میکنه هنوز بررسی نکردم کدوم گزینه عوض میشه که کانفیگا از کار میوفته برای همراه اول apn رو بزنید mcinet و برای ایرانسل mtnirancell درست میشه لطفا بررسی کنید پس از چند ساعت کدوم گزینه تغییر پیدا میکنه که از کار میوفته

**Comment by maliohammad** [comment]
> حالا واسه من برعکسه.از پنجاه تا کانفیگ نود درصدشون روی ایرانسل جواب میده اما روی همراه اول تنها دوسه تا از کانفیگا کارمیده اونم پینگش بالاست..روی ایرانسل vmess ws و trojan grpc .این دوتا که صد درصدمطمعنم کارمیدن

من هيچ وقت Grpc كار نكرده برام نه با تروجان نه با vless

**Comment by maliohammad** [comment]
> مشکل از تغییرات خودکار تنظیمات apn در داخل گوشی هست apn اصلی رو حذف کنید به صورت دستی apn جدید تعریف کنید اوکی میشه ولی بعد از چند ساعت دوباره اوپراتور به صورت خودکار تنظیمات apn رو عوض میکنه هنوز بررسی نکردم کدوم گزینه عوض میشه که کانفیگا از کار میوفته برای همراه اول apn رو بزنید mcinet و برای ایرانسل mtnirancell درست میشه لطفا بررسی کنید پس از چند ساعت کدوم گزینه تغییر پیدا میکنه که از کار میوفته

تازه چک کردم mtnirancell هست شايد اين مشكل apn واسه همه نيست. من apn ام سالمه ولی بیشتر پروتوکولها وصل نمیشن

**Comment by ashkanbagheri** [comment]
Apn رو دوباره بساز ریست شه شما تغییرات قسمتهای پایین رو بررسی کن

**Comment by lymanjre** [comment]
عزیز از قابلیت autocdn استفاده کن یا آیپی تمیز و cdn
