### ISSUE TITLE
ای پی کثیف یا دامنه کثیف؟ 

### ISSUE THREAD

**Issue by AmuChangiz** [hiddify/hiddify-config#476]
سلام.
من در تست سرعت داخل پنل، سرعت خوبی میگیرم. در اینترنت های ثابت هم با تمامی کانکشن های دایرکت (نه سی دی ان کلو فلر) هیچ افت سرعتی ندارم. اما در اپراتور های همراه، تقریبا هیچ دیتایی رد و بدل نمیشه و فقط پینگ اتصال رو نمایش میده که اتصال رو تایید میکنه.
اما روی همون اپراتور ها با کانکشن ssh بدون افت سرعت به سرور متصل میشم
حالا سوالی که برام پیش اومده اینه که ممکنه اپراتور ها بتونن کانکشن های وی لس و تروجان رو ببندن که این مشکل پیش اومده؟ یا دامنه هم میتونه دچار محدودیت سرعت شده باشه؟ چون اگر ای پی در لیست کثیف isp قرار گرفته باشه من در اتصال ssh هم باید دچار مشکل میشدم و کندی سرعت داشتم.

**Comment by robin98** [comment]
برای منم دقیقا همین مشکل به همین شکل وجود داره. پیشنهاد می کنم که به هیچ وجه از ssh tunnel برای تونل کردن ترافیک استفاده نکنید و متد آی پی تمیز کلادفلر رو دنبال کنید. اگه داخل ایران متوجه تبادل ترافیک غیرعادی تحت عنوان بسته های ssh بشه کلا از بیخ سرور بلاک میشه اونوقت همین ssh ساده هم دیگه نمی تونید بزنید.

تنها راه حل فقط همون آی پی تمیز کلادفلر هستش. در ضمن اگه پروتکل های vless و trojan غیرقابل شناسایی بودن، پس چرا خیلی از دوستان چند هفته یکبار ساب دامینی که روی کانفیگ برای host یا SNI انداختن فیلتر میشه؟

**Comment by AmuChangiz** [comment]
> 
> تنها راه حل فقط همون آی پی تمیز کلادفلر هستش. در ضمن اگه پروتکل های vless و trojan غیرقابل شناسایی بودن، پس چرا خیلی از دوستان چند هفته یکبار ساب دامینی که روی کانفیگ برای host یا SNI انداختن فیلتر میشه؟

خیلی ممنون بابت راهنمایی اما من حتی کانفیگ های cdn هم برام کار نمیکنه و فقط پینگ میده و دیتا منتقل نمیشه. برای همین فکر میکنم Ip سالم هست اما دامنه یا پروتکل انگار محدود شده

**Comment by robin98** [comment]
از دامنه خودتون در کانفیگ که در قسمت host یا sni هست پینگ بگیرید تا ببینید آیا فیلتر شده یا خیر. اگه فیلتر بود جایگزینش کنید با یک ساب دامنه جدید.

**Comment by ashkanbagheri** [comment]
مشکل از تغییرات خودکار تنظیمات apn در داخل گوشی هست apn اصلی رو حذف کنید به صورت دستی apn جدید تعریف کنید اوکی میشه ولی بعد از چند ساعت دوباره اوپراتور به صورت خودکار تنظیمات apn رو عوض میکنه هنوز بررسی نکردم کدوم گزینه عوض میشه که  کانفیگا از کار میوفته برای همراه اول apn رو بزنید mcinet و برای ایرانسل mtnirancell درست میشه لطفا بررسی کنید پس از چند ساعت کدوم گزینه تغییر پیدا میکنه که از کار میوفته

**Comment by AmuChangiz** [comment]
متاسفانه نه تغییر دامنه نه ثبت دستی apn نتونست کمکی کنه. دو هفته هست به طور کل در اینترنت های همراه این سرویس ها به درستی کار نمیکنه. از فیلتر و محدود نشدن ip هم مطمعن هستم و حتی با cdn کلودفلر هم امکان اتصال نیست.

**Comment by ghermez** [comment]
> متاسفانه نه تغییر دامنه نه ثبت دستی apn نتونست کمکی کنه. دو هفته هست به طور کل در اینترنت های همراه این سرویس ها به درستی کار نمیکنه. از فیلتر و محدود نشدن ip هم مطمعن هستم و حتی با cdn کلودفلر هم امکان اتصال نیست.

دوست عزیز تقریبا با آی پی تمیز و درست و حسابی خیلی راحت همه داریم استفاده میکنیم
شما اگر از فیلتر نبودن ساب دومین و آی پی سرور مطمئن هستی، با یه آی پی تمیز مثل 45.142.120.110 کارتون راه میوفته!

**Comment by lymanjre** [comment]
عزیز مطلب پیکربندی را در ویکی مطالعه کن حتما
