### ISSUE TITLE
dns server by admin

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#477]
درود و عرض خسته نباشید ، لطفا در صورت امکان ، امکان اضافه کردن دی ان اس سرور اختصاصی بر اساس ورودی توسط مدیر را اضافه کنید تا تمام کانفیگ هایی که خروجی میشوند از ان دی ان اس سروری که ما تعین میکنیم گذر کند
ممنون

**Comment by robin98** [comment]
اینو مطالعه بفرمایید

https://github.com/hiddify/hiddify-config/issues/108
