### ISSUE TITLE
ارور 1034

### ISSUE THREAD

**Issue by sajadzi** [hiddify/hiddify-config#478]
پنل x-ui دارم هیچ مشکلی با دامنه نداره ولی با یه دامنه دیگه این پنل رو نصب کردم هر از گاهی موقع باز کردن پنل کاربر و ادمین کلاد فلر ارور 1034 میده پنل رو ری انستال میکنم چند ساعتی خوبه دوباره این ارور ظاهر میشه اینقد صفحرو باید رفرش کنم تا پنل باز بشه

متن ارور:

Error 1034 Ray ID: 7a90708ffe4c3631 • 2023-03-16 22:30:16 UTC
Edge IP Restricted
What happened?
You've requested a page on a website that is part of the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host (ha.tohidsazan.ga) resolved to an IP address that the owner of the website does not have access to.

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Check your DNS records to ensure they are pointed to the IP address(es) you were assigned at registration.

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
