### ISSUE TITLE
Trojan HTTP

### ISSUE THREAD

**Issue by mozilla-firefox** [hiddify/hiddify-config#479]
سلام
لطفا تروجان بدون tls هم اد کنید
در حال حاضر کانفیگ http فقط vless هست که رو خیلی از کلاینت ها ساپورت نمیشه و vmess که مشکلات امنیتی داره و قابل شناسایی هست
ممنون

**Comment by lymanjre** [comment]
تروجان هر دو مدل را داریم الان چک کنید
