### ISSUE TITLE
سرویسی که بشه روی mikrotik ران کرد؟

### ISSUE THREAD

**Issue by armandoarmani** [hiddify/hiddify-config#482]
سلام 
سرویسی هست که بشه روی میکروتیک ها فعال کرد ؟ 
اگر نه بعدا اضاقه خواهد شد ؟

**Comment by PatrickstarWritesCode** [comment]
روی میکروتیک نسخه‌های جدیدش می‌تونید docker ران کنید البته من تست نکردم برای hiddify

**Comment by baghiyat** [comment]
نمیشه sstp یا l2tp سرور بخوره سمت سرور هیدیفای بعد با client وصل شد بهش با میکروتیک که دیتا از هیدیفای رد شه؟

**Comment by PatrickstarWritesCode** [comment]
> نمیشه sstp یا l2tp سرور بخوره سمت سرور هیدیفای بعد با client وصل شد بهش با میکروتیک که دیتا از هیدیفای رد شه؟

اگر تانل بزنید دیگه چه نیازی به هیدیفای هست؟ نفهمیدم.

**Comment by baghiyat** [comment]
ما برای اینکه بتونیم از vmess یا  vless روی میکروتیک استفاده کنیم نیاز به یک vless client یا vmess روی میکروتیک داریم!
منظورم اینه که فعلا که همچین چیزی نداریم! چطوری میتونیم از این قابلیت ها استفاده کنیم روی میکروتیک

**Comment by armandoarmani** [comment]
> > > نمیشه sstp یا l2tp سرور بخوره سمت سرور هیدیفای بعد با client وصل شد بهش با میکروتیک که دیتا از هیدیفای رد شه؟
> 
> > 
> 
> > اگر تانل بزنید دیگه چه نیازی به هیدیفای هست؟ نفهمیدم.
> 
> 
> 
> ما برای اینکه بتونیم از vmess یا  vless روی میکروتیک استفاده کنیم نیاز به یک vless client یا vmess روی میکروتیک داریم!
> 
> منظورم اینه که فعلا که همچین چیزی نداریم! چطوری میتونیم از این قابلیت ها استفاده کنیم روی میکروتیک 
> 
> 

منم سوالم دقیقا همین 😃

**Comment by lymanjre** [comment]
روی دیوایس میکروتیک از openwrt استفاده کنید.

**Comment by mgmoghaddam** [comment]
> روی دیوایس میکروتیک از openwrt استفاده کنید.

چه کلاینتی پیشنهاد میکنید؟
