### ISSUE TITLE
xmplus  vs hiddify

### ISSUE THREAD

**Issue by AkramiPro** [hiddify/hiddify-config#484]
درود . ممنون از زحمات شما برای این برنامه
خواستم بدونم برنامه شما بهتر هست یا xmplus  ؟ البته میدونم که اون پولی هست ولی در کل میخوام بدونم

**Comment by GameOver61** [comment]
اون در اصل یک سایته فروش وی پی انه   این پنل فروشندست با این فرق داره که بخوای مقایسه کنی
