### ISSUE TITLE
لیست ترتیب بندی

### ISSUE THREAD

**Issue by sajadzi** [hiddify/hiddify-config#485]
لیست ترتیب بندی بر اساس روز باقی مانده به درستی مرتب نمیکند
لیست ترتیب بندی بر اساس نام  به درستی مرتب نمیکند در مرتب کردن اعداد در کنار حروف بهم میریزد

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
