### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by aag0116** [hiddify/hiddify-config#49]
My server became unavailable after last night's update and reinstallation did not solve it

**Comment by smf8** [comment]
@hiddify 

It's because of misconfiguration [here](https://github.com/hiddify/hiddify-config/blob/main/xray/configs/04_policy.json.template#L10). Please use release versioning for auto-update and apply changes in a staging branch.

**Comment by hiddify** [comment]
Fixed.
I agree with you.
