### ISSUE TITLE
نصب دکمه فعال وغیرفعال کردن هرکاربر

### ISSUE THREAD

**Issue by GameOver61** [hiddify/hiddify-config#491]
تشکرمیکنم بابت زحماتی که واسه این برنامه کشیدین پیشنهادم اینه که یه دکمه کنار اسم هر کاربری  تعبیه کنین که هر کاربری رو بشه بهاش فعال یا غیر فعال کرد یعنی دسترسیش رو قطع یا وصل کنیم.هرکی موافقه لایک کنه

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
