### ISSUE TITLE
ارور نصب بر روی Ubuntu 18

### ISSUE THREAD

**Issue by xxSaeidxx** [hiddify/hiddify-config#494]
سلام. هنگام نصب بر روی Ubuntu 18 با این پیغام رو به رو میشم.

wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
tar (child): hiddify-config-v.tar.gz: Cannot open: No such file
 or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove 'hiddify-config-v.tar.gz': No such file or di
rectory
bash: install.sh: No such file or directory
Press any key to go  to menu

می تونید کمکم کنید؟

**Comment by lymanjre** [comment]
عزیز از ابونتو ۲۰ یا ۲۲ استفاده کنید نوشتیم که پیش نیازها چیه
