### ISSUE TITLE
بات تلگرام لینک اشتباهی از صفحه کاربری در اختیار کاربران میگذارد

### ISSUE THREAD

**Issue by amin2plus** [hiddify/hiddify-config#496]
بات تلگرام لینک صفحه کاربری ای که میده صرفا لینک از اولین دامین توی صفحه دامین ها رو میده، 
![Screenshot_20230320-133120~3](https://user-images.githubusercontent.com/31206022/226311211-4e90425d-73fb-4d48-bb6e-7b9861d1e4a7.png)

در صورتی که ممکنه تمامی کانفیگ ها رو توی دامین دوم یا سوم مثلا یکی کرده باشین،
مشکل اینه که اگه کاربر روی اون لینک کلیک کنه خوب همه کانفیگ ها رو نمیبینه و دامینی که نمیخواهیم رو باز میکنه
![Screenshot_20230320-133226~2](https://user-images.githubusercontent.com/31206022/226309384-db00ec55-602d-49db-8dc4-5b6dd4cad557.png)
به طور مثال من تمامی کانفیگ ها رو توی دامین چهارمیم یکی کردم و اون لینک رو میدم به کاربرا،

راه حل پیشنهادیم اینه که گزینه بگذارید یکی از دامین ها رو انتخاب کنیم برای اینکه بات لینکشو بده 
یا گزینه سورت کردن دامین ها رو اضافه کنید که اصلیه رو بتونیم 
بیاریم بالا
نسخه پنلم ۲.۳.۱

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
