### ISSUE TITLE
نصب در ابونتو با استفاده از لینک

### ISSUE THREAD

**Issue by hmayondoci** [hiddify/hiddify-config#498]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9h8jla6_/msgpack/

من در حال نصب بروی اوبونتو هستم در ورژن های 18 تا 22 تست کردم همه همین ارور رو می ده سرور های من از هتزنر و لوکیشن آلمان است

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره

**Comment by ari18hmd** [comment]
من ارور no module named hiddifypanel رو میگیرم موقع نصب
