### ISSUE TITLE
Bash installer broken

### ISSUE THREAD

**Issue by iran-free-net** [hiddify/hiddify-config#500]
I just run bash command "download and install" aka ubuntu easy installation.
first time its run without any problems, but I had to restore my server so in second time I couldn't install it and installer was broken!
what I understood, there is no return to first stage (rollback) in first stage.
and better to describe it was occurred in environment setup!

![image](https://user-images.githubusercontent.com/128326573/226356815-88e8a453-1633-463a-b9b5-661cd7488cc9.png)

**Comment by iran-free-net** [comment]
Extra info: uWSGI killed!

![Uploading uWSGI-killed.PNG…]()

**Comment by lymanjre** [comment]
Please check latest update. It should be solved
