### ISSUE TITLE
GRPC problem, Nginx always disabled so is xray! 

### ISSUE THREAD

**Issue by essoojay** [hiddify/hiddify-config#504]
OS: ubuntu 20.04 (Vultr and Digitalocean)

All trojan, vmess, vless  WS+ TLS   = GOOD!

All trojan, vmess, vless grpc + tls  = NOT WORKING (NO INTERNET)

nginx and Xray disabled! when checked with systemctl

firewall enabled on ports 22, 80 and 443

GRPC enabled on cloudflare.

What could be wrong?

**Comment by hiddify1** [comment]
check hiddify-nginx hiddify-xray

Enable Full
![image](https://user-images.githubusercontent.com/114227601/227370469-9a5ed9e9-cfc1-4821-b14f-2c2c9b52b20b.png)
