### ISSUE TITLE
امکان bridge-portal-nginx-ws

### ISSUE THREAD

**Issue by TezaroS** [hiddify/hiddify-config#506]
لطفا امکان bridge کردن دو یا چند وی پی اس را با روش لینک زیر فراهم کنید. تشکر.

https://github.com/XTLS/Xray-examples/tree/main/ReverseProxy/VLESS-TCP-XTLS-WS

**Comment by hiddify1** [comment]
نیازی به اون روش نیست
https://github.com/hiddify/hiddify-config/discussions/493

**Comment by TezaroS** [comment]
لطفا در مورد اینکه هردو سرور یا چند سرور از v2ray , nginx  استفاده کنند راهنمایی بفرمایید. تشکر
