### ISSUE TITLE
Timeout Error during importing configs via Hiddify configs link

### ISSUE THREAD

**Issue by 0xNext** [hiddify/hiddify-config#507]
**Describe the bug**
Some users are getting Timeout error during verifying phase on import process.

**To Reproduce**
1. Be sure you are using the I.R internet!
2. Copy Hiddify configs Link.
3. Open HiddifyProxy app. 
4. Create new profile using copied link.
5. Wait to get the Timeout error on verifying phase.

**Additional context**
After some considerations, we found out, if 'skip-cert-verify: false' be changed to 'skip-cert-verify: true' the verify phase will bypass and the import process will complete without any problem.

I would suggest you add this as an option on server side configurations.

**Comment by lymanjre** [comment]
Please check latest update. It should be solved
