### ISSUE TITLE
UTLS configurations doesn't apply to v2RayNG configurations

### ISSUE THREAD

**Issue by 0xNext** [hiddify/hiddify-config#508]
**Describe the bug**
I was checking the server configurations out of I.R internet and I got the following errors in v2RayNG application:

![image](https://user-images.githubusercontent.com/127152835/227208027-59c8c882-f3d1-4e92-80d0-407725bf2ddc.png)

The error log was:
2023/03/23 13:48:06 [Warning] [3522921901] app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxxxx):  > malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x01\x00\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\x7f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"] > common/retry: all retry attempts failed
2023/03/23 13:48:06 [Info] [3522921901] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe

I check on those configurations and found out despite it is set on server the uTLS field is not initialized:

![image](https://user-images.githubusercontent.com/127152835/227210282-e32c6a7f-4634-4206-97aa-827591cd6812.png)

I changed the field to 'Randomized' and checked again:

![image](https://user-images.githubusercontent.com/127152835/227211094-ec8bcec7-a353-41b0-99fc-4fa47212c7bd.png)

The error not shown anymore.

**Comment by hiddify1** [comment]
update your v2ray
