### ISSUE TITLE
v2Ray configs are not created correctly.

### ISSUE THREAD

**Issue by 0xNext** [hiddify/hiddify-config#509]
**Describe the bug**
recently, I activated the V2ray config on my server. Configs are shown on the users pages, but they don't work.
It seems also there are some problems with their links on the user page, when I click on the QR code icon it showed but the copied link is:
'ss://proxy['
And v2rayn app could not import the config by QR code.

The configurations are exists in Hiddify and clash apps, But they could not work. 
Clash:
![image](https://user-images.githubusercontent.com/127152835/227216109-3d3e24d5-b5ea-4144-9580-d5f5741ebb69.png)

Hiddfy:
![image](https://user-images.githubusercontent.com/127152835/227216513-7e889ba3-64e2-4ee7-837f-b13bf47cb862.png)

Unfortunately, I couldn't find any detail on logs to understand the problem.

**Comment by lymanjre** [comment]
Please check latest update. Should be solved

**Comment by 0xNext** [comment]
I just checked. nothing changed about this protocol. it doesn't show up in V2rayNG and shows an error in HiddfyDesctop,
