### ISSUE TITLE
Could not switch to this profile error

### ISSUE THREAD

**Issue by FarshadGrayson** [hiddify/hiddify-config#512]
از وقتی آخرین آپدیت رو نصب کردم بعد از تنظیم کانفیگ و پنل مدیریت و لینک کردن ساب دامین ، ارور زیر رو داخل برنامه Clash تحویل میگیرم :
![image](https://user-images.githubusercontent.com/23382820/227691694-a9a71bee-de13-46f8-b827-93d280c3adb5.png)

کسی این مشکلو نداره ؟

**Comment by abmousavi** [comment]
سلام . یکی از راه حل ها اینه که در بخش دامنه ها ، دامین های اضافه رو حذف کنید .
