### ISSUE TITLE
Haproxy fail to start

### ISSUE THREAD

**Issue by ali-masoudi** [hiddify/hiddify-config#514]
**Describe the bug**
after sometimes haproxy fails to start or restart

detailed bug via running haproxy manually:
`# /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
[ALERT] 083/124408 (30991) : parsing [/etc/haproxy/haproxy.cfg:103] : 'server' expects <name> and <addr>[:<port>] as arguments.
[ALERT] 083/124408 (30991) : parsing [/etc/haproxy/haproxy.cfg:107] : 'server' expects <name> and <addr>[:<port>] as arguments.
[ALERT] 083/124408 (30991) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 083/124408 (30991) : Fatal errors found in configuration.
`

as it seems it founds problem in line 103 and 107 in haproxy config file
`
backend tgdecoy
    mode tcp
    server tgdecoy 

backend tgdecoy_http
    mode http
    server tgdecoy_http
`
disabling mtp proxy via panel didn't help,
so I commented them out and service restart suceeded.

can anyone plz explain haproxy structure used in hiddify?
it's to complicated, if somebody could explain it via e.g a diagram it would be very helpful

**Comment by ali-masoudi** [comment]
The problem will solve if I define "Telegram FakeDomain" in the panel.
but will cause issues if the field is empty even if telegram proxy is disabled.

**Comment by lymanjre** [comment]
Please check latest update. Should be solved
