### ISSUE TITLE
انسداد یا محدودیت اتصال کاربر به پورت های خاص

### ISSUE THREAD

**Issue by mozilla-firefox** [hiddify/hiddify-config#516]
سلام
لطفا قابلیت این رو اضافه کنید که بتونیم اتصال کاربر به یه سری پورت ها رو مسدود کنیم
و یا اتصال کاربر رو فقط به یه سری پورت های خاص محدود کنیم
با تشکر

**Comment by lymanjre** [comment]
چنین قابلیتی نه معقول هست و نه کارکرد یک سرور vpn است. اصولا تناسبی با کارگرد فیلترشکن نداره
