### ISSUE TITLE
مشکل UTLS

### ISSUE THREAD

**Issue by akv79** [hiddify/hiddify-config#517]
وقتی که توی تنظیمات پنل UTLS رو روی None میذاریم پارامتر fp توی لینک کانفیگ ها باید کامل حذف بشه چون وجودش باعث عدم عملکرد کانفیگ توی بعضی برنامه ها مثل V2rayNG روی اندروید میشه
trojan://bd8e50ef-600e-4470-s6g8-2f1719f8fe9a@domain.com:443?security=tls&sni=domain.com&type=grpc&alpn=h2&path=Klwh2R8jt3un1sLteRqwzk9y&host=domain.com&serviceName=Klwh2R8kd7th1sLteRqwzk9y&mode=multi&`fp=none`&headerType=None#GCT2

**Comment by lymanjre** [comment]
مشکل از باگ برنامه v2rayng هست و به پنل برنمیگرد. عملا این برنامه پارامتر none را نمیشناسه. امید که زود رفعش کنند
