### ISSUE TITLE
گزارش باگ در قسمت ربات

### ISSUE THREAD

**Issue by mahdish45** [hiddify/hiddify-config#519]
#گزارش_باگ
مورد اول: وقتی دامنه های فیک روی پنل فعال باشه به هیچ عنوان ربات تلگرام فعال نمیشه و استارت نمیخوره
مورد دوم: وقتی ربات تلگرام رو فعال میکنید و پکیج مورد نظر رو می‌سازید اون پکیج که از طریق ربات ساخته میشه کار نمیکنه

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
