### ISSUE TITLE
admin link not working after install

### ISSUE THREAD

**Issue by thawri1** [hiddify/hiddify-config#52]
after successful install admin links not working.
returning such errors:

This page isn’t working78.111.**.** didn’t send any data.
ERR_EMPTY_RESPONSE

or:

This site can’t be reached78.111.**.**.sslip.io refused to connect.

**Comment by hiddify** [comment]
normally sslip.io subdomain is blocked in Iran. you can remove sslip.io in the url and it will work.
You can also use http instead.
