### ISSUE TITLE
۲.۵ ورژن

### ISSUE THREAD

**Issue by bamdad23** [hiddify/hiddify-config#523]
کلا بعد از کلین اینستال. صفحه ادمین باز میشه تغیرات ایجاد شده رو سیو که میکنیم ارور میده بعد دیگه دسترسی نمیده . بعد هم که از نو اینستال کنیم میبره صفحه ادمین کاربر هم اد میکنیم اما بعدش رو کاربر کلیک میکنم همه چه کرش میکنه حتی صفحه ادمین هم استیتوس که میگیرم 
etdata                        active                         
clash-server                   active                         
shadowtls                      active                         
ss-faketls                     inactive                       
ss-v2ray                       inactive                       
hiddify-panel                  active                         
hiddify-nginx                  active                         
hiddify-xray                   failed                         
haproxy                        active   
اینو نشون میده گاهی هم hiddify-nginx رو میزنه failed.

**Comment by bamdad23** [comment]
فکر کنم باگ من مربوط به سرتیفیکیت اس اس ال باشه چون لینکه بدون https اوکی کار میکنه. کسی میتونه راهنمائی کنه؟

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
