### ISSUE TITLE
راه حل رفع مشکل ریکپچا گوگل

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#524]
درود ![Screenshot_2023-03-28-05-51-38-884_com.android.chrome.jpg](https://user-images.githubusercontent.com/52799129/228111738-71cf9880-1c84-4afa-bdbe-27d54390d543.jpg)

ما به این مشکل میخوریم 
برای راه حل هم از این اسکریپت
https://github.com/jinwyp/one_click_script
شماره ۱۲ استفاده میکردیم و همه چیز حل میشد

میخواستم پیشنهاد بدم در صورت امکان این اسکریپت رو مچ کنید با پنل تا مشکل ریکپچا عزیزان حل بشه ❤️🙏

**Comment by realartin** [comment]
> در حال حاضر با غیرفعال کردن IPv6 این مشکل حل میشه این روش رو هم تست نکردم اما اگر کار میکنه اینجا هم بزارش تا بقیه کاربر ها مطلع بشن : #486

نیاز داریم تا ipv6 روشن باشد ، کار میکند سوالم از تیم هیدیفای این هست که اگر ممکن باشه و تداخلی با پنل نداشته باشد این رو به پنل اضافه کنند

**Comment by hiddify1** [comment]
برش داشتیم وارپ را باگ ایجاد میگرد

**Comment by lymanjre** [comment]
فعلا وارپ مشکل داره. باید دنبا راه جایگزین بود. این درخواست انجام شدنی نیست فعلا
