### ISSUE TITLE
مشکل تغییر پورت

### ISSUE THREAD

**Issue by Amir6971** [hiddify/hiddify-config#525]
الان با این اپدیت جدید با پورت های مختلف هم که بهش دادم داخل تنظیمات (پورت های اکتیو کلودفلر) الان با همه اونا خودش میسازه یعنی برای هر مدل ۶ حالت ایجاد میکنه برام ! 
ولی فقط اونی که با پورت ۴۴۳ هست کار میکنه ! 

بقیه ارور ۵۰۳ میدن 
کسی ایده ای داره ؟

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
