### ISSUE TITLE
باگ در ورژن 2.6.0

### ISSUE THREAD

**Issue by TezaroS** [hiddify/hiddify-config#527]
کاربران جدید متصل نمی شوند. 

There is a big error in xray configuration.
	runtime/asm_amd64.s:349 +0x11c fp=0x7ffd58350088 sp=0x7ffd58350080 pc=0x46a63c
runtime.rt0_go()
	runtime/proc.go:712 +0x9a fp=0x7ffd58350080 sp=0x7ffd58350020 pc=0x43aa5a
runtime.schedinit()
	runtime/malloc.go:409 +0xb2 fp=0x7ffd58350020 sp=0x7ffd5834fff0 pc=0x40c7f2
runtime.mallocinit()
	runtime/mheap.go:772 +0x13f fp=0x7ffd5834fff0 sp=0x7ffd5834ffb8 pc=0x426d9f
runtime.(*mheap).init(0x1c4a200)
	runtime/mpagealloc.go:314 +0x70 fp=0x7ffd5834ffb8 sp=0x7ffd5834ff88 pc=0x429ad0
runtime.(*pageAlloc).init(0x1c4a208, 0x1c4a200, 0x0?)
	runtime/mpagealloc_64bit.go:82 +0x18d fp=0x7ffd5834ff88 sp=0x7ffd5834ff00 pc=0x42becd
runtime.(*pageAlloc).sysInit(0x1c4a208)
	runtime/panic.go:1047 +0x5d fp=0x7ffd5834ff00 sp=0x7ffd5834fed0 pc=0x436f5d
runtime.throw({0x12595bb?, 0x7ffd5834ff50?})
runtime stack:

fatal error: failed to reserve page summary memory
haproxy                        active                         
hiddify-xray                   active                         
hiddify-nginx                  active                         
hiddify-panel                  active                         
ss-v2ray                       inactive                       
ss-faketls                     inactive                       
shadowtls                      active                         
clash-server                   active                         
netdata                        active                         
Mar 28 11:51:16 TRZ haproxy[24264]: 162.158.87.99:64750 [28/Mar/2023:11:50:10.390] https-in xray/xray 1/0/66043 19247 -- 17/17/16/16/0 0/0
Mar 28 11:51:16 TRZ haproxy[24264]: 162.158.86.216:49614 [28/Mar/2023:11:50:10.394] https-in xray/xray 1/0/66031 5859 -- 18/18/17/17/0 0/0
Mar 28 11:51:16 TRZ haproxy[24264]: 162.158.87.106:21996 [28/Mar/2023:11:50:10.390] https-in xray/xray 1/0/66030 109340 -- 19/19/18/18/0 0/0
Mar 28 11:51:16 TRZ haproxy[24264]: 162.158.86.191:10332 [28/Mar/2023:11:50:10.388] https-in xray/xray 1/0/66027 6847 -- 20/20/19/19/0 0/0
Mar 28 11:51:15 TRZ haproxy[24264]: 162.158.87.2:16396 [28/Mar/2023:11:50:09.949] https-in xray/xray 1/0/66049 62970 -- 20/20/19/19/0 0/0
Mar 28 11:51:15 TRZ haproxy[24264]: 162.158.87.25:59308 [28/Mar/2023:11:50:09.953] https-in xray/xray 1/0/66039 91578 -- 21/21/20/20/0 0/0
Mar 28 11:51:15 TRZ haproxy[24264]: 162.158.87.190:38734 [28/Mar/2023:11:50:09.950] https-in xray/xray 1/0/66036 56330 -- 22/22/21/21/0 0/0
Mar 28 11:51:15 TRZ haproxy[24264]: 162.158.87.199:19782 [28/Mar/2023:11:50:09.946] https-in xray/xray 1/0/66035 91947 -- 23/23/22/22/0 0/0
Mar 28 11:51:15 TRZ haproxy[24264]: 162.158.87.112:39320 [28/Mar/2023:11:50:09.946] https-in xray/xray 1/0/66030 23712 -- 24/24/23/23/0 0/0
Mar 28 11:51:15 TRZ haproxy[24264]: 162.158.110.159:26716 [28/Mar/2023:11:51:11.987] https-in xray/xray 1/0/3239 4729 CD 25/25/24/24/0 0/0

             └─24264 /usr/sbin/haproxy -sf 756 -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
             ├─  713 /usr/sbin/haproxy -sf 756 -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
     CGroup: /system.slice/haproxy.service
        CPU: 1.750s
     Memory: 74.6M
      Tasks: 2 (limit: 2257)
   Main PID: 713 (haproxy)
             file:/usr/share/doc/haproxy/configuration.txt.gz
       Docs: man:haproxy(1)
     Active: active (running) since Tue 2023-03-28 11:40:46 +0330; 10min ago
     Loaded: loaded (/lib/systemd/system/haproxy.service; enabled; vendor preset: enabled)
● haproxy.service - HAProxy Load Balancer

Mar 28 11:43:05 TRZ systemd[1]: Started Xray Service.
Mar 28 11:43:05 TRZ systemd[1]: Starting Xray Service...

             └─24858 /usr/local/bin/xray run -confdir /opt/hiddify-config/xray/configs/
     CGroup: /system.slice/hiddify-xray.service
        CPU: 4.035s
     Memory: 25.0M
      Tasks: 8 (limit: 2257)
   Main PID: 24858 (xray)
       Docs: https://github.com/xtls
     Active: active (running) since Tue 2023-03-28 11:43:05 +0330; 8min ago
     Loaded: loaded (/etc/systemd/system/hiddify-xray.service; enabled; vendor preset: enabled)
● hiddify-xray.service - Xray Service

Mar 28 11:42:59 TRZ systemd[1]: Started hiddify-nginx - high performance web server.
Mar 28 11:42:59 TRZ systemd[1]: hiddify-nginx.service: Failed to parse PID from file /run/hiddify-nginx.pid: Invalid argument
Mar 28 11:42:59 TRZ systemd[1]: Starting hiddify-nginx - high performance web server...

             └─24238 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─24237 "nginx: master process /usr/sbin/nginx -c /opt/hiddify-config/nginx/nginx.conf"
     CGroup: /system.slice/hiddify-nginx.service
        CPU: 474ms
     Memory: 4.0M
      Tasks: 2 (limit: 2257)
   Main PID: 24237 (nginx)
       Docs: https://nginx.org/en/docs/
     Active: active (running) since Tue 2023-03-28 11:42:59 +0330; 8min ago
     Loaded: loaded (/etc/systemd/system/hiddify-nginx.service; enabled; vendor preset: enabled)
● hiddify-nginx.service - hiddify-nginx - high performance web server

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
