### ISSUE TITLE
غیر فعال کردن tun 

### ISSUE THREAD

**Issue by Mahdi7b** [hiddify/hiddify-config#532]
در پنل امکانی اضاف کنین که بشه tun رو در کانفیگ کلش فعال یا غیر فعال کرد

![tun](https://user-images.githubusercontent.com/35459108/228356788-5cf1ffc8-8240-4ef8-9749-6e4b8a8116b7.jpg)

**Comment by lymanjre** [comment]
دکمه TUN در اپ کلش متا و هیدیفای باگ داره که به کلش برمیگرده. متاسفانه این امکان فراهم نیست و اپ را عوض کردیم. به زودی اپ جدید را منتشر می کنیم
