### ISSUE TITLE
auto cdn shatel simcard

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-config#534]
شاتل سیم کارت اتو سی دی ان دیتکت نمیکنه ولی بعد چند بار اپدیت ساب ، خروجی ایپی اش خیلی خوب کار میکند
![photo_2023-03-29_14-03-46](https://user-images.githubusercontent.com/52799129/228507509-a91ba6ee-ce4c-4880-a5ae-cf0795c6896d.jpg)

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
