### ISSUE TITLE
نمایش ستون نام نمایشی

### ISSUE THREAD

**Issue by zoobin65** [hiddify/hiddify-config#536]
![B4837613-6182-4F5E-94BA-61CF9207B4FC](https://user-images.githubusercontent.com/72542476/228763238-c0695e14-f7dc-496b-8eb1-4e60e0aa3318.jpeg)

سلام خسته نباشید
اگر امکان دارد ستون نام نمایشی برای کاربر نمایش داده شود تا بتواند کانفیگ مورد نظر خودش را دریافت کند
مثلا نام همراه اول یا ایرانسل را ببیند و آن کانفیگ را کپی کند
با تشکر

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
