### ISSUE TITLE
لینک subscription کاربران در صفحه اصلی ادمین

### ISSUE THREAD

**Issue by amirooo70** [hiddify/hiddify-config#539]
درود. به نظرم اگه تو جدول لینک‌های کاربر توی پنل ادمین، لینک subscription هر کاربر هم بود که همونجا میشد کپی کرد کارآمد میشد.
در حال حاضر ادمین باید به صفحه کاربر مراجعه کنه و لینک subscription رو کپی کنه. در حالت پیشنهادی ادمین می‌تونه از صفحه کاربران، لینک subscription رو مستقیما دریافت کنه.

**Comment by lymanjre** [comment]
چنین امکانی در صفحه یوزرها تناسبی ندارد و فضای زیادی میگیرد
