### ISSUE TITLE
How to use multiuser?

### ISSUE THREAD

**Issue by ali101224** [hiddify/hiddify-config#54]
پارسی:
وقت بخیر 
پنل رو از طریق نصب سریع نصب کردم
برای استفاده از قابلیت چندکاربره سکرت کد رو مشابه گفته خودتون در بخش تنظیمات بصورت تعریف میکنم:
b3fbb9b35e1052f713f36c303ac02ffd;b3fbb9b35e1052f713f36c303ac02ffe
مثلا برای دو UUID 
اما با اخطار زیر مواجه میشم.
Secret for USER_SECRET=b3fbb9b35e1052f713f36c303ac02ffd;b3fbb9b35e1052f713f36c303ac02ffe is incorrect. It should be 32 char hex values. Click back and fix it

ممنون میشم بطور کلی نحوه استفاده از قابلیت مولتی یوزر رو توضیح دهید.

English:
HI dude
I installed the panel through quick installation
To use the multi-user feature, I define the secret code as you said in the settings section:
b3fbb9b35e1052f713f36c303ac02ffd; b3fbb9b35e1052f713f36c303ac02ffe
For example, for two UUIDs
But I get the following warning.
Secret for USER_SECRET=b3fbb9b35e1052f713f36c303ac02ffd;b3fbb9b35e1052f713f36c303ac02ffe is incorrect. It should be 32 char hex values. Click back and fix it

Please explaining how to use the multi-user function.

**Comment by hiddify** [comment]
> پارسی: وقت بخیر پنل رو از طریق نصب سریع نصب کردم برای استفاده از قابلیت چندکاربره سکرت کد رو مشابه گفته خودتون در بخش تنظیمات بصورت تعریف میکنم: b3fbb9b35e1052f713f36c303ac02ffd;b3fbb9b35e1052f713f36c303ac02ffe مثلا برای دو UUID اما با اخطار زیر مواجه میشم. Secret for USER_SECRET=b3fbb9b35e1052f713f36c303ac02ffd;b3fbb9b35e1052f713f36c303ac02ffe is incorrect. It should be 32 char hex values. Click back and fix it
> 
> ممنون میشم بطور کلی نحوه استفاده از قابلیت مولتی یوزر رو توضیح دهید.
> 
> English: HI dude I installed the panel through quick installation To use the multi-user feature, I define the secret code as you said in the settings section: b3fbb9b35e1052f713f36c303ac02ffd; b3fbb9b35e1052f713f36c303ac02ffe For example, for two UUIDs But I get the following warning. Secret for USER_SECRET=b3fbb9b35e1052f713f36c303ac02ffd;b3fbb9b35e1052f713f36c303ac02ffe is incorrect. It should be 32 char hex values. Click back and fix it
> 
> Please explaining how to use the multi-user function.

Currently it is not possible via ui you should edit config.env file directly

In the next version, you can add multiple user with usage limits 😉
