### ISSUE TITLE
مشکل در هیدیفای دسکتاپ

### ISSUE THREAD

**Issue by randomguy-on-internet** [hiddify/hiddify-config#542]
نمیتونم هیچ لینک پروفایلی رو اضافه کنم این ارور رو میده
[ارور](https://s2.uupload.ir/files/screenshot_1_hrcl.png)
کلش ورج هم امتحان کردم، کار نکرد ولی لینک کلش داخل کلش راحت بالا اومد
دی ان اس هم عوض کردم اونم کار نکرد، دامنه هم فیلتر نیست بدون پروکسی باز میشه.

windows 11 22h2 ( Os build 22621. 1483 )

**Comment by vipeyley** [comment]
منم این باگ رو دارم ولی بعد از چند بار که همون لینکو ادد میکنم بالاخره کار میکنه

**Comment by randomguy-on-internet** [comment]
از دیروز 100 بار امتحان کردم، کار نمیکنه

**Comment by randomguy-on-internet** [comment]
وقتی با دامین های دیگه امتحان کردم کار کرد، مشکل از تنظیمات کلودفلر بود (Minimum TLS Version).

اگر مثل من چندتا دامین دارید و یک دامین رو فقط برای پنل ست کردین و ازش برای پروکسی استفاده نمیکنید، میتونید اینو روی حالت اول بزارید.

![منبع ارور](https://user-images.githubusercontent.com/79375739/229030856-52a5c9a9-5350-4cb1-a730-a5deb25aea6e.png)

Cloudflare dashboard - > select you domain -> SSL/TSL -> Edge Certificates -> Minimum TLS Version -> TLS 1.0

اگر روی ورژن بالا تنظیم کنید، توی گوشی های قدیمی ارور TLS HANDSHAKE میده و نمیشه از لینک سابسکریپشن استفاده کرد.

**Comment by vipeyley** [comment]
دقیقا مشکل همین بود هم داخل آروان هم کلودفلیر.
ممنون

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
