### ISSUE TITLE
ارتباط با دیتابیس

### ISSUE THREAD

**Issue by huuthangntk** [hiddify/hiddify-config#546]
سلام, چجوری من میتونم با دیتابیس هیدیفای نصب شده روی سرورم ارتباط برقرار کنم؟ دوست دارم که خودم کاربر بهش اضافه کنم با دستورات SQL. تا جایی که یادمه SQL بود دیتابیس هیدیفای. 

مکان دیتابیس دقیقا کجاست؟

**Comment by lymanjre** [comment]
بله از پوشه hiddify-config
