### ISSUE TITLE
ایراد در حالت auto cdn

### ISSUE THREAD

**Issue by jaber-raoufi** [hiddify/hiddify-config#548]
چرا وقتی رو حالت auto cdn هستم وارد سایت‌هایی مثل my ip address میشم ip اصلی سرور من رو نشان میده؟! یا وقتی وارد سایت pingtools میشم باز هم ip سرور رو نشان میده!

**Comment by realartin** [comment]
> چرا وقتی رو حالت auto cdn هستم وارد سایت‌هایی مثل my ip address میشم ip اصلی سرور من رو نشان میده؟! یا وقتی وارد سایت pingtools میشم باز هم ip سرور رو نشان میده!

چون در هر صورت وقتی وقتی به وی پی ان وصل باشید ، ایپی میانی هرچه باشد در نهایت ایپی سرور شما در سطح اینترنت به نمایش در می اید
