### ISSUE TITLE
Google 403. That’s an error.

### ISSUE THREAD

**Issue by Vahid-n** [hiddify/hiddify-config#551]
مشاهده خطای 403 برای جستجوی گوگل در تمام سیستم های اندروید و ویندوز با تمامی مرورگرها به شرح زیر:
403. That’s an error.

Your client does not have permission to get URL /m?q=my+shatel&client=ms-opera-mobile&channel=new&espv=1 from this server. That’s all we know.

با موتور جستجوی بینگ مشکلی نیست و سایر سرویس های گوگل مانند Google play نیز مشکلی ندارند

**Comment by Vahid-n** [comment]
خیلی ممنون
الان کاری میتونم بکنم؟ چون آپدیت هم کردم ولی باز هم همون خطا رو میگیرم

On Sun, Apr 2, 2023 at 3:15 PM
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Zo0oX** [comment]
من هم همین مشکل رو دارم، آپدیت هم کردم ولی باز این ارور میاد، چطور میتونم درستش کنم ؟

**Comment by mgh9** [comment]
check this out:
[https://github.com/hiddify/Hiddify-Server/issues/943](url)
