### ISSUE TITLE
restful api 

### ISSUE THREAD

**Issue by alix1383** [hiddify/hiddify-config#553]
سلام خسته نباشید 
جناپ اگه امکانش هست میخواستم درخواست اضافه کردن restful api  به پنل بدم

**Comment by kurdev2020** [comment]
سلام خسته نباشید بنده هم با دوستمون موافقم خیلی خوب میشد اگه restful api داشت

**Comment by herotux** [comment]
بسیار پیشنهاد خوبیه حتما بهش فکر کنید
