### ISSUE TITLE
suggestion for warp,hide server ip, google recaptcha and dynamic domain for users

### ISSUE THREAD

**Issue by trding4all** [hiddify/hiddify-config#554]
Hi 
I have 2 suggestion for hiddify team.
First one add this script as an option to solve google recaptcha and hidding orginal server ip. [this script](  wget -N --no-check-certificate https://gitlab.com/rwkgyg/CFwarp/raw/main/CFwarp.sh && bash CFwarp.sh    )
It is avoid google recaptcha and server  ip leak using a CloudFlare ip . i tested this script with ur panel but it has some conflicts. but it is works with x-ui(Also x-ui is very simple, ur panel is better)

Second one is about domains, i explain it with an example, for example i have domain with example.com and I set it in Cloudflare CDN. I set this domain for my panel too and use CDN mode.
I need an option to refer subdomain based on username to my clients. my domain was example.com , and i have user1 and user2 determined in Clients area.
I want an automation system to assign  user1.example.com and user2.example.com automatically to users configs to avoid SNI filter. I know that it is needed to right config in Cloudflare, assume that it is done in CDN panel.
 
Best Regards

**Comment by hiddify1** [comment]
we have tried it but it was not effecient so we have removed it.

some users after several hours encountered with dns failed problem
