### ISSUE TITLE
مشکل حذف کاربر

### ISSUE THREAD

**Issue by etraeel** [hiddify/hiddify-config#557]
با درود خدمت تیم فوق العاده هیدیفای

حذف کاربر به درستی کار نمیکنه با زدن بر روی گزینه حذف و چند دقیقه زمان پنل از کار میوفته.
از هر 10 بار تلاش یک بار موفق به حذف کاربر میشه

**Comment by lymanjre** [comment]
اپدیت کنید به اخرین ورژن حل شده

**Comment by etraeel** [comment]
با سلام و خسته نباشید 
پنل به آخرین ورژن بروزرسانی شده ولی همچنان مشکل حذف کاربر وجود دارد .
خطای nginx میدهد 

و یک سوال دیگه اینکه بعد از چند روز پس از اتمام اعتبار کاربر  ، اکانت حذف میگردد ؟
