### ISSUE TITLE
پیشنهاد 

### ISSUE THREAD

**Issue by Ali7268** [hiddify/hiddify-config#561]
سلام و وقتتون بخیر سه تا موضوع اگه بشه یه صفحه لاگین بذارید برای امنیت بیشتر و موضوع دوم قسمت صفحه کاربر  دامین غیر قابل دیدن باشه مثلا با همون کد تنها ببینه و مورد سوم ایا میشه اسم های سابسکرایب عوض کرد که هربار که اپدیت می کنه کاربر همون اسم بمونه

**Comment by lymanjre** [comment]
بینک سابسکریپشن که میتونید همیشه ثابت از یه لینک استفاده کنید
لاگین به نرم افزار همین الانم هست ولی شما درگیرش نمیشید. لینکی که باز میکنید شامل رمز ادمینه. میتونید تغییرش بدین. این روش سادگی و راحتی بیشتری داره در کنارش امنیت هم داره. رمز ادمین شاید سالها سول بکشه حدس زدنش پس نگران نباشید. 

برای کاربر وقتی شما کانفیگ بهش میدین درنهایت دامین را می بینه فرقی نمیکنه
