### ISSUE TITLE
alpn تغییر مقدار پیش فرض

### ISSUE THREAD

**Issue by arsaces7** [hiddify/hiddify-config#564]
کانفیگ هایی که پنل میده مقداره alpn یا روی h2 هست یا http/1.1 در صورتی که من فقط وقتی میتونم وصل بشم که این مقدار خالی باشه! توی تنظیمات جایی برای تغییرش پیدا نکردم

**Comment by lymanjre** [comment]
خب alpn همین دوتاس دیگه. چیز دیگه ای نداریم. میتونید در ورژن ۳ کانفیگ دستی بسازید
