### ISSUE TITLE
روش ایجاد سریع کاربران با خط فرمان

### ISSUE THREAD

**Issue by cypress5211** [hiddify/hiddify-config#568]
### Discussed in https://github.com/hiddify/hiddify-config/discussions/567

<div type='discussions-op-text'>

<sup>Originally posted by **cypress5211** April  3, 2023</sup>
ایا روشی برای ساخت کاربر جدید با اجرای یک دستور تو سرور هست؟</div>

**Comment by lymanjre** [comment]
خیر نیست ولی با بات تلگرام میشه
