### ISSUE TITLE
api

### ISSUE THREAD

**Issue by aminsg** [hiddify/hiddify-config#569]
سلام 
در صورت امکان دستورات مستقیم برای اضافه کردن ، ویرایش بر اساس uuid ، دریافت لیست کامل کاربران ، آپدیت مصرف و حذف مستقیم هم ایجاد کنید تا امکان استفاده به صورت api در برنامه های مختلف مثل c# فراهم بشه

**Comment by ParsaHarooni** [comment]
+

**Comment by lymanjre** [comment]
در حال حاضر امکان پذری نیست
