### ISSUE TITLE
اجبار استفاده دامنه در کانفیگ

### ISSUE THREAD

**Issue by GameOver61** [hiddify/hiddify-config#570]
باسلام.باتشکر از برنامه خوبتون ، گزینه اجبار استفاده از دامنه در کانفیگ های cdn  کارنمیکنه .دامنه ای که میزاری تو کانفیگ استفاده نمیشه.

**Comment by aminsarani62** [comment]
سلام وقت بخیر. مشکل منم همینه

**Comment by lymanjre** [comment]
اپدیت کنید به ورژن ۳ اوکی هست
