### ISSUE TITLE
استفاده از نام دلخواه برای کانفیگ ها 

### ISSUE THREAD

**Issue by ZakariaRasoli** [hiddify/hiddify-config#571]
استفاده از نام دلخواه برای کانفیگ ها 
افزودن دامنه سابسکرایب برای جلوگیری از فیلترشدن دامنه ساب

**Comment by nafiswal2** [comment]
قبلا میشد نام رو تغییر داد ولی تو آپدیت جدید حذف شده

**Comment by ZakariaRasoli** [comment]
مگه مشکلی داشت اسم دلخواه که حذف شده ؟
راحت میتونن یه باگاشو بگیرن url parse میخواد فک کنم

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
