### ISSUE TITLE
مرتب سازی بر اساس روزهای باقی مانده و حجم استفاده شده

### ISSUE THREAD

**Issue by R30na** [hiddify/hiddify-config#574]
مرتب سازی بر اساس روزهای باقی مانده مشکل داره. نه صعودی مرتب میشه نه نزولی
در ضمن بهتره مرتب سازی بر اساس حجم مصرفی به گونه ای عمل کنه که نسبت استفاده به حجم کل در نظر گرفته بشه: 
برای مثال اگه نزولی مرتب کنیم حجم کسی که از ۲ گیگ ۱.۵ گیگ استفاده کرده باید بالاتر از کسی باشه که از ۵ گیگ ۳ گیگ استفاده کرده. الان ولی فقط حجم مصرفی بدون در نظر گرفتن حجم کل مرتب میشه.

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
