### ISSUE TITLE
باز نشدن لینک های کاربران و وصل نشدن فیلتر شکن ها

### ISSUE THREAD

**Issue by Sinahb3** [hiddify/hiddify-config#576]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mamixgodx** [comment]
سلام. وقتتون به خیر. من وقتی لینک اکانت رو با wifi td-lte ایرانسل میزنم برام اون صفحه کامل باز میشه و راحت تونستم سابسکریپشن هامو آپدیت و وصل بشم به پروکسی. ولی وقتی با نت همراه اول(هات اسپات نت گوشی و اتصال با لپ تاب) میخوام لینک رو بیارم بالا نمیاره. میخواستم بپرسم اگه میشه راهنماییم کنین:
OS:windows
Browser:Chrome latest version

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
