### ISSUE TITLE
محدودیت روزانه ترافیک به غیر از  محدودیت کلی اکانت 

### ISSUE THREAD

**Issue by Mohammadnyc** [hiddify/hiddify-config#577]
سلام و عرض ادب و خسته نباشید به تیم خفن هیدیفای
اگر بشه قابلیتی توی ساخت اکانت کاربر اضافه کنید که علاوه بر گذاشتن محدودیت حجم مثلا ۳۰۰گیگ ، بشه روزانه هم محدودیت گذاشت مثلا ۱۰گیگ
که مصرف کاربر متعال باشه یهو فشار نیاد یا دامنه فیلتر نشه
ممنون از شما🙏

**Comment by hiddify1** [comment]
بزنید حجم کاربر روزانه 10 گیگ باشه و ریست باشه روزانه
