### ISSUE TITLE
جایگذاری چند ایپی در بخش اجبار به استفاده...

### ISSUE THREAD

**Issue by Mohammadnyc** [hiddify/hiddify-config#578]
اگه تو یه دامنه حالت cdn چند تا ایپی توی جای «اجبار به استفاده‌ از آی پی‌های زیر در کانفیگ‌ CDN» بزارم چه اتفاقی میوفته ؟ یعنی با چه الگوریتمی ایپی میده به کاربر؟

**Comment by lymanjre** [comment]
ویکی را مطالعه کنید
