### ISSUE TITLE
ایده در نام کانفیگ ها 

### ISSUE THREAD

**Issue by sirvan1133** [hiddify/hiddify-config#579]
نمایش نام دلخواه روی کانفیگ ها 
یا نمایش میزارن ترافیک روی کانفیگ ها زمان بر هست ؟ 
اگر اظافه شود مشکلش چی هست ؟ 
روی هر کانفیگ نامش اختصاصی باشد 
مثلا یه کانفیگ بنویسیم همراه 
روی یکی دیکه بنویسیم  ایرانسل ، همزمان با اسم ها میزان ترافیک هم با اپدیت اظافه بشه 
نمیشه ؟!
ایطوری مثلا 
irancell 50GB/USED 3.56GB
Hamrah 50GB/USED 3.56GB
یعنی نام
irancell 
Hamrah
خودمون بنویسیم 
و ترافیک هم به صورت کاستوم در تنظیمات اظافه بشه

**Comment by hiddify1** [comment]
هم اکتون وجود داره
با اپ اختصاصی هیدیفای مشکل نمایش حل میشه
