### ISSUE TITLE
remove vultr due to sanctions against iran

### ISSUE THREAD

**Issue by Ehsan3500** [hiddify/hiddify-config#58]
Vultr removed my access to panle due to sanctions against iran (connecting via iran Ip address)
Please remove it from your manual guide

[Ticket:] Re:Possible International Trade Restriction Inquiry

Due to recent activity on your account from a sanctioned country - Iran, Islamic Republic of, our ToS department is requesting additional information to validate your identity

**Comment by hiddify** [comment]
!!!!
I will add this notice to the account.
however tell them in the support ticket about your situation
