### ISSUE TITLE
اضافه کردن دامنه برای subscription ها

### ISSUE THREAD

**Issue by hiradsajde** [hiddify/hiddify-config#580]
سلام.
به نظرم وجود بخش مدیریت subscription link ها توی پنل خیلی کاربردیه
بتونم انتخاب کنیم یک inbound لینک اش توی subscription باشه یا نه، شاید بخوایم نباشه ولی کار کنه. 
و بتونیم دامین subscription ها رو تغییر بدیم. طوری که روی اون دامنه VPNنباشه. تا فیلتر نشه. اگر سرور اصلی فیلتر شد یوزر بتونه لینک های جدید رو بگیره.

**Comment by hiddify1** [comment]
الان اینجوری هست دیگه
تو لینک ساب مخفیش کنید از قسمت پروکسی
یا دامنه را بزنید فقط دامنه های یک دامنه خاص نمایش داده بشه
