### ISSUE TITLE
تکمیل API برای توسعه پروژه های مکمل

### ISSUE THREAD

**Issue by hiradsajde** [hiddify/hiddify-config#582]
سلام. API توکن واقعاً می‌تونه سرعت توسعه پروژه رو زیاد کنه. به نظرم بجای اینکه hiddify بخواد تمرکز اش رو روی social های مختلف مثل توسعه ربات تلگرامی بزاره، با توسعه API می تونه این کارو به تیم های دیگه واگذار کنه. 
مثلا میشه خیلی راحت یک ربات ساز تلگرامی ساخت ، یوزر آدرس پنل و API توکن اش (یا لینک اتصال به API) اش رو می فرسته. و یک توکن ربات میده. یک ربات تلگرامی براش ران میشه که کل ویژگی های پنل رو پشتیبانی میکنه. حتی پنل فروش و... هم میشه بهش اضافه کرد. و hiddify کل تمرکز اش سمت توسعه VPN میره.

**Comment by lymanjre** [comment]
مشکل اینجاست که فرهنگ سیستم اپن سورس در این کشور وجود نداره. محصول اپن سورس را استفاده میکنن تجاریش میکنن میفروشنش. تا زمانیکه راه حلی براش پیدا نکنیم این کار را نمی کنیم
