### ISSUE TITLE
اپلود بکاپ ها 

### ISSUE THREAD

**Issue by alix1383** [hiddify/hiddify-config#583]
اکه امکانش هست یک قابلیت اد کنید که بکاپ ها هر 6 ساعت ار طریق ftp به هاست دیگه اپلود شن + امکان تست برقرای ارتباط با هاست بکاپ

**Comment by randomguy-on-internet** [comment]
salam
ye rah sade tar ine ke file backup ro be soorate **private be pastebin** upload koni.
inam codesh:

```Python
#!/usr/bin/env python3

import json
from pbwrap import Pastebin
import glob

api_dev_key = "your_Key" # get your api_dev_key from https://pastebin.com/doc_api#1 after registering in Pastebin.com
username = "your_username" # Your Registeration username
password = "your_password" # Your Registeration username
pastebin = Pastebin(api_dev_key)
user_id = pastebin.authenticate(username, password)

Backed_up_files = list()
for file in glob.glob("./backup/*.json"):
    Backed_up_files.append(file.replace("\\", "/"))

with open(Backed_up_files[-1]) as file:
    f = json.load(file)

Pasting = pastebin.create_paste(json.dumps(f), api_paste_private=2, api_paste_name=Backed_up_files[-1],
                                api_paste_expire_date="N", api_paste_format="json")
print(Pasting)
```

hala age khasti, mitooni in kararo anjam bedi ke harvaght hiddify backup gereft, be pastebin ham ye noskhe ezafe kone:

```
python3 -m pip install pbwrap
```

aval in code ro bar asas moshakhastet Edit mikoni, baad pastesh mikoni dakhele hamin file `Backup_pastebin`
```Bash
nano /opt/hiddify-config/hiddify-panel/Backup_pastebin.py
```

save mikoni va baad in file ro virayesh mikoni va 
`python3 Backup.py`
in khat ro ezafe kon zire `python3 -m hiddifypanel backup`:

```
nano /opt/hiddify-config/hiddify-panel/backup.sh
```


```Bash
#!/bin/bash

cd $( dirname -- "$0"; )
function main(){
    python3 -m hiddifypanel backup
    python3 Backup.py
}
main |& tee -a ../log/system/backup.log
```

tamam, hala harvaght backup begire, upload mikone be pastebin, linke pastebin ham dakhele backup.log panel admin hast.

![Screenshot_2](https://user-images.githubusercontent.com/79375739/230028692-7ed4b06e-fb6a-4e71-ba37-66b48383bd68.png)

**Comment by alix1383** [comment]
@randomguy-on-internet
ی دنیا ممنون جناب ♥
