### ISSUE TITLE
باگ در قسمت دامنه ها

### ISSUE THREAD

**Issue by amirakrami852** [hiddify/hiddify-config#587]
یه باگی هست تو پنل که وقتی تو قسمت دامنه ها اون قصکتی که دامنه هایی رو که انتخاب میکنیم تا کانفیگ ها رو به یوزر نشون بده وقتی انتخابی نکرده باشیم همه کانفیگ ها روی همه دامنه ها نشون میده به یوزر در 
صورتی که مباید چیزی بیاره تو لینک کاربری
خوب میدونم تا وقتی از اون دامنه لینک ندیم استفاده نمیشه ولی بهتره نیست وقتی انتخابی نداریم روی دامنه اصلا چیزی نشون نده تا اگه اشتباها لینک اشتباه هم دادی کاربر در اصل چیزی نبینه هیچ کانفیگی رو

**Comment by lymanjre** [comment]
عزیز این با نیست. دیفالت همه کانفیگهاست
