### ISSUE TITLE
ثبت پیام برای کاربران یا لینک کانال تلگرامی

### ISSUE THREAD

**Issue by aminkhorsand** [hiddify/hiddify-config#588]
لطفا قسمتی رو سایت در نظر بگیرید تا اگر پیامی برای کاربرها داریم بتونیم قثبت کنیم تا همه پیام رو داخل سایت ببینند 
یا از اون بهتر قسمتی باشه تا لینک  کانال تلگرامی خودمون رو ثبت کنیم تا اطلاع رسانی هایی که لازم هست از طریق کانال اطلاع رسانی کنیم
با تشکر

**Comment by hiddify1** [comment]
اضافه شده
