### ISSUE TITLE
مشکل در نصب مستقیم در ubuntu

### ISSUE THREAD

**Issue by kavkav123** [hiddify/hiddify-config#590]
در انتهای  نصب اسکر‍‍‍یپت اول شروع به سعی در دانلود از YOUTUBE می کند و موفق نمیشود و از نصب خارج می شود.
لینکهای یوزر و ادمین کار نمیکند. 
و سیستم در این وضعیت گیر میکند. 
      Tasks: 2 (limit: 2234)
     Memory: 74.5M
        CPU: 847ms
     CGroup: /system.slice/haproxy.service
             ├─  770 /usr/sbin/haproxy -sf 10871 -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
             └─16746 /usr/sbin/haproxy -sf 10871 -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock

Apr 06 03:51:23 irvm-516561 haproxy[10871]: [WARNING]  (10871) : Stopping backend shadowtls in 0 ms.
Apr 06 03:51:23 irvm-516561 haproxy[10871]: [WARNING]  (10871) : Stopping backend shadowtls_decoy_http in 0 ms.
Apr 06 03:51:23 irvm-516561 haproxy[10871]: [WARNING]  (10871) : Stopping backend shadowtls_decoy in 0 ms.
Apr 06 03:51:23 irvm-516561 haproxy[10871]: [WARNING]  (10871) : Stopping frontend GLOBAL in 0 ms.
Apr 06 03:51:23 irvm-516561 haproxy[10871]: Stopping backend shadowtls in 0 ms.
Apr 06 03:51:23 irvm-516561 haproxy[10871]: Stopping backend shadowtls_decoy_http in 0 ms.
Apr 06 03:51:23 irvm-516561 haproxy[10871]: Stopping backend shadowtls_decoy in 0 ms.
Apr 06 03:51:23 irvm-516561 haproxy[770]: [NOTICE]   (770) : New worker #1 (16746) forked
Apr 06 03:51:23 irvm-516561 systemd[1]: Reloaded HAProxy Load Balancer.
Apr 06 03:51:23 irvm-516561 haproxy[770]: [WARNING]  (770) : Former worker #1 (10871) exited with code 0 (Exit)
netdata                        active
clash-server                   active
shadowtls                      active
ss-faketls                     inactive
ss-v2ray                       inactive
hiddify-panel                  active
hiddify-nginx                  activating
hiddify-xray                   active
haproxy                        active
ignoring xray test

چگونه باید نصب را ادامه داد؟

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره

**Comment by kavkav123** [comment]
Ok . ممنون
