### ISSUE TITLE
مشکلات رایج

### ISSUE THREAD

**Issue by ali1565** [hiddify/hiddify-config#591]
در نرم افزار fair vpn موقع وارد کردن subscription ارور میدهد.
در مدل های پایین تر گوشی هایی مثل سامسونگ نرم افزار hiddify در قسمت import configuration موقع وارد کردن config برنامه stop می شود و بیرون می اندازد
در نرم افزار v2ray هم مشکل subscription وجود دارد
در نرم  افزار hiddify امکان استفاده از barcode scanner وجود ندارد
برای فرستادن لینک برای کلاینت ها هم مشکل وجود دارد

**Comment by lymanjre** [comment]
عزیز از کاراکترهای استاندارد در نام نمایشی استفاده کنید. همچنین سرور را آپدیت کنید

**Comment by ali1565** [comment]
با نشکر فراوان از پاسخگوییتان 
منظور از کارکتر های استاندارد فارسی هست ؟؟
