### ISSUE TITLE
پیدا کردن آیپی تمیز کلودفلر به طور خودکار

### ISSUE THREAD

**Issue by Hamed-Deve** [hiddify/hiddify-config#592]
سلام
یه پیشنهاد دارم واسه پنل
اگه میشه یه صفحه مثل این https://ircfspace.github.io/scanner
به پنل کاربر اضافه کنید که کاربر بتونه با اینترنت خودش آیپی های کلودفلر رو تست کنه و آیپی های سالم خودکار به کانفیگا اعمال بشه
اینجوری احتمال قطع شدن کاربر خیلی کمتره و هر وقت مشکلی پیش بیاد می‌تونه وارد این صفحه بشه و آیپی تمیز رو بگیره

**Comment by lymanjre** [comment]
در پروژه اعلام آیپی در ircf مشارکت کنید. خروجی آن به پنل می اید

**Comment by J6star-personal** [comment]
این رو هم تست کنید :
https://yadbegiresh.ir/google-drive/
