### ISSUE TITLE
قابلیت تعیین دستی پورت اتصال به پنل از محیط ترمینال

### ISSUE THREAD

**Issue by MehdiBnp** [hiddify/hiddify-config#595]
کاش مثل پنل x-ui از محیط داخل ترمینال پورت اتصال به پنل را بتوان تغییر داد.
اینجوری کسایی ک محدودیت پورت دارن هنگام تنظیم اولیه‌ دامنه پنل به مشکل نمیخورن. (کسایی ک از nat vps استفاده میکنند)
یا اگر این امکان وجود نداره کاش بتوان از محیط ترمینال ، دامنه خودمون رو تنظیم کنیم تا مشکل پورت نداشته باشیم.
مثل پنل مرزبان

درخواست دیگه ام اینه که لینک اتصال به پنل فقط دامنه خودمون باشه و محیط لاگین برای ادمین وجود داشته باشه

**Comment by hiddify1** [comment]
روی natvps با رم 256 اصن نمیشه همچین پنلی را بالا آورد

**Comment by MehdiBnp** [comment]
نه رم من بالاست، بعدشم این قابلیت واقعا کاربردی هست و پنل شمارو یه پنل کامل میکنه ، مثلا شما تنظیمات پنل رو همشو در داخل ترمینال هم قابل تغییر قرار بدی. این قابلیت ها بهتر از تغییر مخیط گرافیکی و ... هست. خواهش میکنم یه کاری برای ما انجام بدین

**Comment by esamani77** [comment]
سلام
شما تونستی روی natvps بیاری بالا؟
من مشکل همین پورت رو دارم در حال حاضر

**Comment by MehdiBnp** [comment]
سلام
اره خیلی راحت
تو آموزش سگارو میگه کلودفلر رو فقط روی https بزار

اون تیک رو از تنظیمات کلودفلر خاموش کن
اونوقت میتونی لینکی که برای بار اول هیدیفای بهت میده رو باز کنی.

قبلشم برای نصب هیدیفای باید آپاچی رو استاپ کنی چون رو پورت ۸۰ هست.
دستورش تو اینترنت هست

تو پنل نت وی پی اس هم باید ریورس پراکسی هارو بزنی دیگ تا بتونی بعد ک رفتی
داخل پنل هیدیفای ثبتش کنی و بهت سرتیفیکیت بده.

حتما از لینک هایی ک بعد نصب هیدیفای بهت میده از لینک هایی که انتهاش sllip
io داره استفادع کن

تمام نکاتی ک باید رعایت میکردی


اما در اخر بگم اگه نت وی پی اس۲۵۶ رم گرفتی اصن به خودت زحمت نده چون هیدیفای
خیلی سنگینه و رو اون اصن بالا نمیاد و همش هنگه
۵۱۲ شاید یکم بهتر باشه

ولی درستش اینه که رم ۱ گیگ داشته باشی حداقل
