### ISSUE TITLE
[Bug] Sort by Usage/Expire-Days

### ISSUE THREAD

**Issue by mozilla-firefox** [hiddify/hiddify-config#597]
سلام
در حال حاضر وقتی یوزر ها رو بر اساس روزهای باقی مانده یا حجم به ترتیب میکنم، به اشتباه این کار انجام میشه

درضمن چیزی که برای ما لازم هست، اینه که بتونیم بدونیم کدوم کاربر ها روز ها یا حجم کمتری براشون باقی مونده، اگر بشه وقتی سورت میکنیم بر این اساس سورت بشه خیلی بهتره

با تشکر

**Comment by Obeid1375** [comment]
بله منم چندین بار گزارش باگ کردم. روی نام کاربری هم مشکل داره . روی حجم هم مشکل داره.

**Comment by hiddify1** [comment]
fixed
