### ISSUE TITLE
توروخدا هرکس میدونه کمک کنه درمورد cdn

### ISSUE THREAD

**Issue by sajjadasg** [hiddify/hiddify-config#598]
باسلام من از سی دی ان ابراروان استفاده میکردم چن روزیه ای پی فیلتر میکنند.
به نظرتون کجا خوبه؟
سایت کلادفلیر تست کردم و ای پی تمیزم دادم منتهی سرعتش کمه
هرکی میدونه کمکم کنه ممنون میشم با تشکر

**Comment by trytopassgfw** [comment]
جز دو راهی که گفتی میمونه تانل کردن و یا دایرکت بزنی به سرور

**Comment by lymanjre** [comment]
از autocdn استفاده کنید
