### ISSUE TITLE
باگ در آپدیت Subscription 

### ISSUE THREAD

**Issue by mdseven** [hiddify/hiddify-config#599]
سلام خسته نباشید
بعد از غیر فعال کردن Utls در تنظیمات و آپدیت ساب روی v2ray کانکشن های آپدیت شده متصل نمیشن و ارور Start Failure میدن
یکبار دکمه ادیت رو باید زد و مجدد سیو کرد تا مشکل حل شه
ولی اگر utls روی گزینه های دیگه ای باشه چنین مشکلی نیست

**Comment by Obeid1375** [comment]
بله همچین مشکلی هست. من دستی بکاپ میگیرم از پنل و توی فایل json بکاپ uTLS که نوشته کروم کلا پاک میکنم و جاشو خالی میزارم.
یا بعد از اضافه کردن کانفیگ توی برنامه uTLS رو یبار دیگه روی هیچی میزارم.

این باگ هم به ادمین شخصا گزارش دادم.

و دستشون درد نکنه گفتن برطرف میشه تو این آپدیت جدید.

**Comment by mdseven** [comment]
بله یه مشکلیه یکم اذیت کنندس چون رو حالتای دیگه سرعت خوبی نمیده مخصوصا روی همراه اول
پس رفع میکنن
دستشون درد نکنه واقعا کار بزرگیه این پنل

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
