### ISSUE TITLE
Not working on a fresh install of ubuntu 20.04

### ISSUE THREAD

**Issue by just1random** [hiddify/hiddify-config#6]
throws `please enter valid domain name to use`

**Comment by hiddify** [comment]
It is fixed. Please check it and let me know

**Comment by hiddify** [comment]
Additionally, i have added zero config mode. If you use a hosting that supports cloud-config you can use it ;-)

Please checkout very very quick setup :D

**Comment by just1random** [comment]
Great work! Yes the problem is fixed.
