### ISSUE TITLE
auto cdn

### ISSUE THREAD

**Issue by amirakrami852** [hiddify/hiddify-config#600]
سلام
میخاستم اگه امکانش هست این auto cdn رو یه قسمتی باشه که به جای اینکه از آیپی های ircf.space استفاده کنه از دامین هایی که خودمون میدیم به همین مدل auto cdn استفاده کنه یعنی نسبت به اپراتور دامین مورد نظر یا آی پی مورد نظرمون رو انتخاب کنه اینجوری در صورتی که نخایم از ircf.space در auto cdn استفاده کنیم میتونیم از دامین و آی پی خودمون استفاده کنیم چون یه مشکلی که ircf داره اینه که خیلی عمومی هستش و زود آی پی هاش زده میشه ولی شاید خودمون آی پی تمیز پیدا کنیم احتمال اینکه بیشتر زمانی جواب بده هستش البته میشه با تعریف چند دامین این کار رو با cdn کرد ولی خوب تعداد کانفیگ بالا میره ولی تو حالت auto cdn این مشکل حل شده

**Comment by Obeid1375** [comment]
مشکلی نداره میتونید روی auto cdn بزارید و دامنه های خودتون مانند زیر بزارید توی قسمت cdn اجباری. و اگه میخواید جای آیپی دامنه برگرده توی حالت CDN میتونید همین کارو کنید.

sub.domain.com MCI

**Comment by lymanjre** [comment]
مقاله ویکی را بخونید گفتیم چطور
