### ISSUE TITLE
باز نشدن پنل ادمین بعد از اضافه کردن یوزر جدید

### ISSUE THREAD

**Issue by mahdian888** [hiddify/hiddify-config#602]
سلام. زمانی که از طریق پنل ادمین یه یوزر جدید ایجاد می کنم و ثبت می کنم، بلافاصله بعد از فشردن دکمه ثبت دیگه کلا پنل ادمین باز نمیشه و تغییرات هم اعمال نمیشه و مجبور میشم از طریق ssh تنظیمات جدید رو اعمال کنم و بعدش پنل لود میشه.

**Comment by mahdian888** [comment]
آپدیت: فکر می کنم مشکل مربوط به خود سرور بود چون الان مشکلی نداره

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
