### ISSUE TITLE
ارور قسمت کاربران پنل ادمین در مود دولوپر

### ISSUE THREAD

**Issue by vafaaee** [hiddify/hiddify-config#605]
پس از آپدیت به نسخه 3.0.0dev64
لینک users ادمین با ارور 502 bad gateway مواجه شد، بقیه قسمت های پنل ادمین اوکی بودن
و مجبور شدم به نسخه ریلیز برگردم

**Comment by amin30000** [comment]
برای من روی حالت پایدار هم به همین صورت هست

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
