### ISSUE TITLE
پینگ نداشتن همراه اول

### ISSUE THREAD

**Issue by ffm32206600** [hiddify/hiddify-config#606]
سلام
روی نت همراه اول اپدیت سابسکریپشن رو که میزنم آیپی آپدیت میشه و چنتا آیپی میاره ولی وقتی real delay all configration رو میزنم پینگ -1ms میاد برای همهی کانفیگها...

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
