### ISSUE TITLE
configs for added CDN domain won't work in Hiddify 2.9.0

### ISSUE THREAD

**Issue by jjtestorderplus1** [hiddify/hiddify-config#607]
بعد از اضافه کردن دامینی که روی cdn کلادفلر هست. کانکشن‌های اون دامنه کار نمی‌کنند. در هر دو حالت cdn و auto cdn.

**Comment by jjtestorderplus1** [comment]
تصحیح می‌کنم. این کانکشن‌ها کار نمی‌کنن و در دو اپراتور متفاوت هم نتیجه یکسان بود:
tls_h2_grpc_CDN_vless
tls_h2_grpc_CDN_trojan
tls_grpc_CDN_vless
tls_grpc_CDN_trojan

**Comment by randomguy-on-internet** [comment]
تنظیمات grpc کلود فلر رو فعال کردی؟ تا فعال نکنی کار نمیکنه.

**Comment by jjtestorderplus1** [comment]
بله. هم grpc و هم h2 یا http2 و 3

**Comment by hiddify1** [comment]
تا الان کسی روی نسخه 3 همچین چیزی را نگفته
