### ISSUE TITLE
وقتی با پورت باز میشه پنل، لینک سابز بدون پورت لینک میشه و این مشکله سازه

### ISSUE THREAD

**Issue by hntcair** [hiddify/hiddify-config#608]
پنل با هر پورتی که باز میشه بهتره تمام لینک ها مخصوصا سابز با همان پورت باز بشه

پورتی که روی tls هم تعریف شده و ...

**Comment by hiddify1** [comment]
توی تنظیمات هر پورتی ست کنید برای اون پورت ها فقط نمایش داده میشه

**Comment by hntcair** [comment]
بله اون پورت برای CONFIGها نمایش داده میشه

اما وقتی با پورت خاص غیر از 443 پنل را باز می‌کنید باید لینک‌ها از جمله لینک ورود به پنل کاربر هم با همون پورت باشه.

ولی از اون مهم‌تر وقتی پنل رو در بخش کاربری با پورت خاص باز می‌کنید و پورت هم تنها پورت تعریف‌شده در TLS باشه، لینکی که می‌سازد برای SUBSCRIPTION بدون لحاظ کردن این پورت است و خوب باید دستی انجام داد

اگه می‌خواید دقیق روی یکی از پنل‌هایی که ایجاد کردم با پورت خاص بهتون دسترسی بدم که ببینید.
