### ISSUE TITLE
SubDomain blocked

### ISSUE THREAD

**Issue by Argo160** [hiddify/hiddify-config#61]
Hi there,
Just did set it up 2 days ago, and it was only me using it.
surprisingly my sub domain got blocked!!
i never visited Iranian websites. and i used the fakecdn links.
my subdomain never got blocked since past 3 months.
wondering what did go wrong!

**Comment by hiddify** [comment]
Did you use fakecdn with HTTP?

**Comment by Argo160** [comment]
FakeCDN Vless ws port80
this one i used the most

**Comment by hiddify** [comment]
This is the reason :-)

**Comment by Argo160** [comment]
So you mean the ones which used the http we gotta avoid?
isn't it better these risky ones not being generated by the script in the first place?

**Comment by hiddify** [comment]
I think you have enabled allow http however, i will take it into
consideration in the next version

**Comment by Argo160** [comment]
Thank.
yes my bad.
everything is allowed in my side.
