### ISSUE TITLE
ارور Deceptive site ahead

### ISSUE THREAD

**Issue by mohsenfff** [hiddify/hiddify-config#613]
سلام و تشکر بابت برنامه خوبتان
من بعد از رجیستر کردن دامنه و قبل از رفتن به کنترل پنل خطای زیر رو میگیرم ، چطور میشه درستش کرد 
![hidify error](https://user-images.githubusercontent.com/39452845/230799001-15f3ad16-2bce-4fe0-b83a-5a92f5c430d1.jpg)

**Comment by hiddify1** [comment]
https://developers.google.com/search/docs/monitor-debug/security/social-engineering#:~:text=If%20Google%20detects%20that%20your,visiting%20the%20Security%20Issues%20report.
