### ISSUE TITLE
چند پیشنهاد لازم و ضروری

### ISSUE THREAD

**Issue by ZakariaRasoli** [hiddify/hiddify-config#614]
اضافه کردن دامین برای لینک های ساب
پشتیبانی از ipv6
پشتیبانی از کانفیگ tcp + http و دامین درقسمت host

**Comment by hiddify1** [comment]
الان هم هست
1- کافیه نمایش کانفیگ های دامنه همه را بزنید به جز دامنه فعلی
2- ساپورت میشه
3- دامنه فیک بذارید
