### ISSUE TITLE
کارنکردن برخی کانفیگ ها

### ISSUE THREAD

**Issue by onyxtm** [hiddify/hiddify-config#616]
بعد از آپدیت پنل به نسخه ۳.۰.۸ بعضی کانفیگ ها که یک مسیر جداگانه داشتند با تغییر اون مسیر و اپدیت پنل دیگه کار نمیکنن، مشکل از چی میتونه باشه؟

**Comment by lymanjre** [comment]
مسیر که نباید تغییر کرده باشه غیر از اینکه تغییرشون داده باشین

**Comment by lymanjre** [comment]
یه آپدیت بزنید به سرور اه مشکلی بود اعلام کنید.
ایشو را من فعلا می بندم. اگه نیاز بود بازش کتنید
