### ISSUE TITLE
Reality protocol

### ISSUE THREAD

**Issue by foroudia** [hiddify/hiddify-config#618]
باسلام
پروتکل جدیدی با نام Reality عرضه شده که به خوبی روی اینترنت های مختلف جوابگو هست.
به عنوان مثال پنل FranzKafkaYu این قابلیت را اضافه کرده و این مورد نیازمنده ورژن 1.8.0 XrayCore می باشد.

**Comment by lymanjre** [comment]
در صورت معرفی نسخه رسمی اضافه میشه
