### ISSUE TITLE
Nginx failed

### ISSUE THREAD

**Issue by onyxtm** [hiddify/hiddify-config#620]
موقع نصب nginx failed میشه. و هیچی لود نمیشه

**Comment by esmaeilifardi** [comment]
در اولین ورود به پانل وقتی درخواست تنظیمات میده و دامنه که وارد میکنین خطایی رخ میده و مجبور میشی با لینک غیر امن وارد پانل ادمین بشی که دیگه بعد اون اشتراک گذاری برای کاربران روی autocdn خطا در هنگام بازگردن لینک اشتراک کاربر مشاهده میشه که مربوطه به همون nginx هستش
Invalid SSL certificate Error code 526
همچنین در کلودفلر دکمه ssl هم فعاله

**Comment by lymanjre** [comment]
تنظیمات سرتیفیکت را در لافلر روی فول بذارید. استریکت نباشه. آپدیت جدید را چک کنید لطفا. مشکی نداره
