### ISSUE TITLE
اضافه کردن تعداد کاربر برای هر پروفایل

### ISSUE THREAD

**Issue by seyedmohamadhadihoseini** [hiddify/hiddify-config#622]
با سلام خدمت شما
و با تشکر از شما برای توسعه این پروژه

لطفا این قابلیت رو هم اضافه کنید که بشه حداکثرتعداد کاربران رو هنگام تعریف کاربر مشخص کرد

**Comment by trytopassgfw** [comment]
این امکان اضافه نمیشه.
