### ISSUE TITLE
nginx خطای

### ISSUE THREAD

**Issue by esmaeilifardi** [hiddify/hiddify-config#624]
در اولین ورود به پانل وقتی درخواست تنظیمات میده و دامنه که وارد میکنین خطایی رخ میده  و مجبور میشی با لینک غیر امن وارد پانل ادمین بشی که دیگه بعد اون اشتراک گذاری برای کاربران روی autocdn خطا در هنگام بازگردن لینک اشتراک کاربر مشاهده میشه که مربوطه به همون nginx هستش
Invalid SSL certificate Error code 526
همچنین در کلودفلر دکمه ssl هم فعاله

**Comment by lymanjre** [comment]
تنظیمات سرتیفیکت را روی فول بذارید. نه فول استریکت
آپدیت جدید را چک کنید نباید مشکلی داشته باشه.
این ایشو را من می بندم . ار مشکل پابرجا بود با ذکر توضیح بیشتر بازش کنید
