### ISSUE TITLE
ایراد هنگام استفاده از apache

### ISSUE THREAD

**Issue by javidizadi** [hiddify/hiddify-config#625]
وقتی پنل شما رو نصب کردم و وب سرور apache رو روی یه ساب دامین کانفیگ کردم پس از چند ساعت ناخودآگاه apache بسته میشه

**Comment by lymanjre** [comment]
عزیز آپاچی احتمالا تداخل پورت با این برنامه داره. بهتر هست برنامه دیگه ای نصب نباشه

**Comment by javidizadi** [comment]
> عزیز آپاچی احتمالا تداخل پورت با این برنامه داره. بهتر هست برنامه دیگه ای نصب نباشه

رو پورت ۵۰۵۰ استفاده ای نبود روی اون گذاشتم بازم همین اتفاق میفتاد
