### ISSUE TITLE
اضافه کردن نام خاص ابتدای هر پروفایل به یک‌باره با یک فیلد در تنظیمات

### ISSUE THREAD

**Issue by hntcair** [hiddify/hiddify-config#627]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lymanjre** [comment]
از گزینه ویرایش کانفیگها استفاده کنید

**Comment by hntcair** [comment]
منظور به یک باره بود نه به صورت تک تک
