### ISSUE TITLE
config issuse

### ISSUE THREAD

**Issue by Cjxer** [hiddify/hiddify-config#63]
سلام
من توی اوراکل اکانت ساختم و طبق ویدیو و آموزش کار هارو انجام دادم
اما وقتی آیپی و کد رو از قسمت Application information کپی کردم و وارد مرورگر کردم ، هیچ اتفاقی نیفتاد و چیزی باز نشد که بقیه کانفیگ ها رو انجام بدم 
منظورم این آدرسه :
http://140.***.***.***/ef********703315******f6dd8ff7c66d076/config

هیچی باز نشد
انگار از سمت خود اوراکل بسته شده
ممنون میشم اگر راه حلی داره بفرمایید

**Comment by absoonoo** [comment]
این موردی نیست که بشود به همین راحتی در‌موردش راه حل نشان داد ، ما باید پینگ ای پی را در شبکه اینترنت خود بگیرید و سپس تنظیمات شبکه و اسکریپت را بررسی کنید. در وب جستجو کنید.

**Comment by hiddify** [comment]
کمی باید صبر کنید تو اوراکل حدود ۱۰ دقیقه
ضمنا ممکنه ای پی فیلتر باشه پس با فیلترشکن هم تست کنید

**Comment by Cjxer** [comment]
سلام ممنون بابت پاسخ

یکم صبر کردم نشد ، مجدد دارم تست میکنم
اما من روی سرور های اوراکل ، اسکریپت x-ui هم نصب کردم ، اما صفحه لاگینش باز نمیشد ( پورت هارو هم باز کردم )
مثل اینکه محدودیتی اعمال شده
ممکنه چنین چیزی ؟
ممنون از زحماتتون
