### ISSUE TITLE
add bot.sudoer.net

### ISSUE THREAD

**Issue by old-joker** [hiddify/hiddify-config#64]
Hi 
please add this http://bot.sudoer.net/best.cf.iran
to find best ip for different network like mci , irancell ... and generate specific configs 

https://github.com/MortezaBashsiz/CFScanner

https://twitter.com/MortezaBashsiz/status/1618572804076736515

**Comment by hiddify** [comment]
من کار این دوستان را میشناسم ولی میترسم اضافه کنم به سیستم کارشون فیلتر بشه
قبلا یه دامنه عام منظوره را اضافه کردیم فیلترش کردند
احتمالا به هایدیفای کلاینت اضافه اش کنیم
