### ISSUE TITLE
باگ بات تلگرام در بخش کاربر ها

### ISSUE THREAD

**Issue by xmohammad1** [hiddify/hiddify-config#640]
وقتی خودم یا کاربرا وارد لینک سایتشون میشن روی مشاهده در تلگرام میزنن لینک میشن به ربات ولی روی استارت که میزنن ربات پاسخ نمیده من از داخل پنل ادمین روی ربات ادمین که میزنم مشکلی نداره فقط بخش کاربرا از کار افتاده.
این مشکلم از دیروز به وجود اومد که یه کاربرو ساختم بعد قبلیو پاک کردم

**Comment by hiddify1** [comment]
رفع شد
