### ISSUE TITLE
مشکل عدم نمایش درست تعداد کاربران آنلاین در باکس استفاده دیروز (نسخه 3 پنل هیدیفای)

### ISSUE THREAD

**Issue by stanesti** [hiddify/hiddify-config#643]
**Describe the bug**
در نسخه جدید پنل هیدیفای (v3.1.4) در صفحه داشبورد مدیریت و در باکس استفاده دیروز، در حالی که چند نفر دیروز آنلاین بوده و از سیستم استفاده کرده‌اند و حتی حجم مصرفی دیروز نیر در باکس نمایش داده شده است، تعداد کاربران آنلاین در این باکس 0 است.

**To Reproduce**
1. Go to 'Hiddify Admin Panel > Dashboard'
2. See error

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Browser Firefox
 - Version 111.0.1 (64-bit)

**Comment by hiddify1** [comment]
آپدیت شد
