### ISSUE TITLE
error 520 cloudflare

### ISSUE THREAD

**Issue by meghyas** [hiddify/hiddify-config#65]
ممنون از پروژه خیلی عالی شما
بعد از یک روز کارکردن صفحه ادمین وارد نمیشود ارور 520 کلودفلر میدهد و کلش کار نمیکند لطفا راهنمایی بفرمایید

**Comment by absoonoo** [comment]
سعی کنید از دامنه رایگان استفاده نکنید . ssl را در کلود فلر روی فول بگذارید . از دی ان اس آروان یا پارس پک یا [میزبان کلود](https://mizbancloud.com/) که سرویس های پر سرعتی داره استفاده کنید .

**Comment by meghyas** [comment]
ممنون از پاسختون ولی:
1.دامنه رایگان نیست
2.روی فول تنظیم هست
3. تا دیروز کار میکرد! به نظر اتفاقی برای تنظیمات افتاده است. جالب این هست که روی دوتا سرور همزمان این اتفاق افتاده! کشی چیزی نداره پاک کنم ببینم درست میشه؟!
4. دی ان اس ایرانی باعث فیلتر شدن دامنه نمیشود؟
5.

**Comment by hiddify** [comment]
سلام
لطفا به ورژن جدید به روز رسانی کنید و نتیجه را اعلام کنید
با سپاس
