### ISSUE TITLE
SNI Random

### ISSUE THREAD

**Issue by randomguy-on-internet** [hiddify/hiddify-config#655]
سلام، من 4 خط کد نوشتم واسه عوض کردن sni توی کانفیگ های CDN که فکر میکنم واسه همه مفید باشه. اگر دوست داشتین با اعمال تغییرات برای انواع دامنه به پنل اضافه کنید. [بر اساس این توییت](https://twitter.com/safasafari3/status/1645275463735033858)

با فرض اینکه دامنه بصورت TLD هست (دامنه هایی مثل *.domain.eu.org رو تست نکردم) یعنی
# *.domain.com
و ساب دامنه بصورت sub.domain.com هست خروجی SNI بصورت
# random.domain.com 
میشه

target module: `link_maker.py`

```python

def random_sni(domain: str):
    import string,random
    characters = string.ascii_letters + string.digits
    rand_sub = ''.join(random.choice(characters) for i in range(12))
    sni = f"{rand_sub}.{domain.split('.')[-2]}.{domain.split('.')[-1]}"
    return sni
#فقط خطی که تغییر دادم رو نوشتم
def make_proxy():
base = {
        'sni': random_sni(domain) if is_cdn and proxy.transport != "grpc" else domain,
}
```

داخل چندتا نت و گوشی تست کردم و مشکلی نداره
هیدیفای دسکتاپ و گوشی هم تست کردم

**Comment by randomguy-on-internet** [comment]
> ممنون از پیشنهادتون همین الان هم تو پنل هست آموزشش ساخته نشده کافیه دامنه را با * ثبت کنید

فکر نمیکنم به اینصورت باشه:
![Screenshot_1](https://user-images.githubusercontent.com/79375739/231503209-82b049cd-2ab1-4c19-ad42-9b21f11285fd.png)

اگر هست بگید چجوری باید از * استفاده کرد که فقط SNI رندوم بشه و نه host.

**Comment by hiddify1** [comment]
هاست و  sni باید یکی باشه وگرنه کلودفلر خطا میده

**Comment by randomguy-on-internet** [comment]
> 

نه لزوما نیاز نیست کاملا یکی باشه، فک کنم کلا نخوندی بالا چی نوشتم چه برسه به کدش، فقط دیدی یه * داره و پیچوندی 😁

فقط باید دامنه ی هاست و sni یکی باشه ولی ساب دامین میتونه متفاوت باشه مثال:

# کانفیگ فعلی شما:
sni : fixedSUB.domain.com
host: fixedSUB.domain.com

`vless://db7ba30e-8888-407e-bbe6-14c5555a7e57@mci.ircf.space:443?security=tls&sni=fixedSUB.domain.com&type=ws&alpn=h2&path=/NZZ7krEdkEPcyfyZt1DbWNTeSa&host=fixedSUB.domain.com&encryption=none&fp=chrome&headerType=None#tls_h2_WS_CDN_vless
`
# کانفیگی که با اون کد میسازه:
(aw4ci0Yp رندومه)
sni : aw4ci0Yp.domain.com 
host: fixedSUB.domain.com

`vless://db7ba30e-8888-407e-bbe6-14c5555a7e57@mci.ircf.space:443?security=tls&sni=aw4ci0Yp.domain.com&type=ws&alpn=h2&path=/NZZ7krEdkEPcyfyZt1DbWNTeSa&host=fixedSUB.domain.com&encryption=none&fp=chrome&headerType=None#tls_h2_WS_CDN_vless`

**Comment by CIAHAT** [comment]
> هاست و sni باید یکی باشه وگرنه کلودفلر خطا میده

برای پروتکل WS، شما میتونید SNI با دامنه اصلی و ساب دامنه رندوم الکی بذارید و بجاش فقط host روی ساب‌دامنه پشت پروکسی کلودفلیر باشه. اینطوری فیلترچی فقط به SNI که رندوم هست دسترسی داره و میتونه فیلترش بکنه و هیچوقت به ساب‌دامنه اصلی دسترسی نداره.
این قابلیت خیلی مهمیه حتما روش کار کنید برای پروتکل ws بشه ازش استفاده کرد.

**Comment by randomguy-on-internet** [comment]
> 



> > هاست و sni باید یکی باشه وگرنه کلودفلر خطا میده
> 
> برای پروتکل WS، شما میتونید SNI با دامنه اصلی و ساب دامنه رندوم الکی بذارید و بجاش فقط host روی ساب‌دامنه پشت پروکسی کلودفلیر باشه. اینطوری فیلترچی فقط به SNI که رندوم هست دسترسی داره و میتونه فیلترش بکنه و هیچوقت به ساب‌دامنه اصلی دسترسی نداره. این قابلیت خیلی مهمیه حتما روش کار کنید برای پروتکل ws بشه ازش استفاده کرد.

به غیر از gRPC روی همه پروتکل های CDN جواب میده.
خوبی پروژه اپن سورس اینه که میتونید تغییرات مورد نظر بسته به نیازتون رو خودتون اعمال کنید.
**اگر دانش کافی دارید (اگر نه که خرابش میکنید و مجبورید از اول نصب کنید)**، میتونید از اینجا اقدام به ایجاد تغییرات مورد نظر که بالا نوشتم بکنید:
```bash
nano /usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/link_maker.py
```
#ایده_کاربر

**Comment by danialkeimasi** [comment]
من همیشه خارج از این پنل از این استفاده می‌کردم. خیلی فیچر مهمیه.

**Comment by amirpr8** [comment]
سلام مهندس خوبی 
الان تونستی از این قابلیت که ذکر کردی کار کنی باهاش؟
میشه تلگرام پیام بدی بهم به این ایدی
@silvervpns

میخام نصب کنم نیاز دارم به راهنمایی 
ممنون 
@randomguy-on-internet

**Comment by randomguy-on-internet** [comment]
> سلام مهندس خوبی الان تونستی از این قابلیت که ذکر کردی کار کنی باهاش؟ میشه تلگرام پیام بدی بهم به این ایدی @silvervpns
> 
> میخام نصب کنم نیاز دارم به راهنمایی ممنون @randomguy-on-internet

سلام متاسفانه دیگه نمیشه اینو از پنل پیاده سازی کرد، سورس پنل رو انکریپت کردن و دیگه اوپن سورس نیست.
میتونید یه api بنویسید که لینکهایی که از لینک سابسکرایب پنل میگیره رو تغییر بده و یه لینک جدید بسازه با کانفیگ های تغییر داده شده و اونو به کاربر بدید.

**Comment by randomguy-on-internet** [comment]
https://github.com/hiddify/hiddify-config/discussions/1007
