### ISSUE TITLE
Low speed and high ping

### ISSUE THREAD

**Issue by mesmaili151** [hiddify/hiddify-config#66]
Hi guys,
first of all thanks for this script.
I installed that yesterday on 2 different servers which were located in different countries.

but the speed was really bad!

first I tried without CDN and then I used CDN (from Arvancloud) but the results don't change as much as I expected.
also, the ping of the telegram proxy was more than 1200ms!

any helo would be great from you.

**Comment by mesmaili151** [comment]
Any idea guys?

**Comment by Sn97sn** [comment]
Did you try all the different configs via different clients ? 
as for me right now none of the configs work at all, except "FakeCDN vless ws" on Nekoray client and its amazing 
try Enabling "Enhanced domain name resolution" in Routing settings for Nekoray, was helpful for me

**Comment by mesmaili151** [comment]
yes, I sent that to my friends also to test that.
I'm not living in Iran but even for me the ping of telegram was about 1300ms!

**Comment by hiddify** [comment]
سلام
لطفا به ورژن جدید به روز رسانی کنید و نتیجه را اعلام کنید
با سپاس
