### ISSUE TITLE
کلش ویندوز

### ISSUE THREAD

**Issue by Amir2241** [hiddify/hiddify-config#67]
سلام تشکر میکنم از زحماتتون

برای من روی گوشی خیلی خوب کار میکنه ولی برای ویندوز 7 بعد از نصب کلش و فعال کردن پروکسی و انتخاب یکی از تنظیمات   هیچ پروکسی در قسمت PROXIES نمیاد و فقط نشون میده کانکت هست ولی هیچ ارتباطی برقرار نیست

ممنون میشم راهنمایی کنید

**Comment by hiddify** [comment]
سلام
لطفا به ورژن جدید به روز رسانی کنید و نتیجه را اعلام کنید
با سپاس

**Comment by Amir2241** [comment]
.سلام بله حتما متشکرم
