### ISSUE TITLE
باز نشدن آی پی

### ISSUE THREAD

**Issue by IranDotCom** [hiddify/hiddify-config#71]
سلام وقتتون بخیر.سپاس از اینکه زحمت میکشید و آموزش قرار میدید.
یه مشکلی که هست اونجا که سرور میسازیم و بعد گفتید http://ip رو بزنیم با اینکه حتی آی پی و سرور جدید هست بدون فیلترشکن باز نمیشه !
حتی بعد از باز کردن و اتمام مراحل و دریافت کانفینگها فقط روی خطوط موبایل اوکی هست و روی پی سی کار نمیکنه از دیروز

**Comment by amin30000** [comment]
دقیقا برای من هم همین مشکل رخ داده 
دیتاسنتر های هتزنر

**Comment by hiddify** [comment]
سلام
لطفا به ورژن جدید به روز رسانی کنید و نتیجه را اعلام کنید
با سپاس

**Comment by IranDotCom** [comment]
اوکی شد ممنون
