### ISSUE TITLE
Reality

### ISSUE THREAD

**Issue by Abbas-Firouzi** [hiddify/hiddify-config#721]
سلام
من کور رو به 9
پنل رو به 4.0.4
آپدیت کردم . سرویس Reality  هم اضافه شد ولی باز برای اوپراتورهای همراه تغییری حاصل نشد
من سرور ریلی ایران هم امروز گرفتم و کانفیگ کردم و تمام پروتکل tcp / udp رو فروارد میکنه سمت سرور خارج ولی باز برای اوپراتورهای همراه هیچ تغییری حاصل نشد .
لطفا راه حلی کمکی همفکری اگه ممکنه بکنید . سپاس

**Comment by vafaaee** [comment]
مشکلی در reality پنل وجود داره
با هر دامینی تست کردم روی هیچ اپراتوری کانکت نمیشه
ضمنا روی پنل چینی با تنظیمات مشابه جواب گرفتم 🤷‍♂️

**Comment by S0R0SH** [comment]
تشکر میکنم که reality روهم اضافه کردید. اما همینطور که دوستان گفتن روی هیچ اپراتوی جواب نگرفتم. بنظرم این چندوقت لطف کردید و آپدیت های زیادی انجام دادید و وقتشه آموزش های نصب و پیکربندی روهم تغییر بدید. مثلا این تیک اضاف شده مشخصه برای چی هست اما بعد از فعال شدن دقیقا کارشو چطوری انجام میده رو متوجه نشدم. این تیک جدید در دامین ها: 
`فقط برای لینک کانفیگ ها (سابسکریپشن)؟  `
تشکر بابت زحماتتون. 🙏🙏🙏
@hiddify1 @hiddify

**Comment by liMilCo** [comment]
بعد از نسب 4.0.5 کانفیگ ریلیتی فقط برای دامنه های مستقیم اضافه شده و بر روی cdn اضافه نشده و دستی هم دامنه میدم کار نمیکنه اما تعداد 2 کانفیگ پیش فرضی که نسب کرده با سرعت خیلی خوبی کار میکنه ...
