### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by Dariushg75** [hiddify/hiddify-config#75]
سلام.

داخل بخش دامنه، دامنه اضافه میکنیم و رول هم روی CDN، اما هیجی کار نمیکنه، و حتی توی بخش کاربران، کانفیگ با CDN ساخته نمیشه و همشون فقط با رول Direct ساخته میشه.

**Comment by mehr30na** [comment]
دقیقا من هم همین مشکل رو دارم ولی برای من ساخته میشه ولی نمیتونم با دامنه cdn لینک رو باز کنم

**Comment by hiddify** [comment]
تنظیمات cdn درست تعریف شده؟ ذکر کرده اید با https وصل بشه؟

**Comment by Dariushg75** [comment]
> تنظیمات cdn درست تعریف شده؟ ذکر کرده اید با https وصل بشه؟

بله تنظیمات درست هست و همچنان مشکل پا برجا

**Comment by mehr30na** [comment]
بله من هم از سی دی ان آروان استفاده میکنم و https فعال هست

**Comment by mehr30na** [comment]
من CDN  رو به کلودفلر تغییر دادم کاملا درست کار میکنه هم پنل بالا میاد هم اتصال برقرار میشه

**Comment by AmirBahmanzadegan** [comment]
من CDN روی کلودفلیر تنظیم میکنم اما همچنان روی CDN کار نمیکنه، صفحه پنل هم تنها یکبار باز میکنه و دیه باز نمیشه !

**Comment by lumanjre** [comment]
لطفا مطلب آیپی تمیز سرور و کلادفلر را در ویکی بخونید
