### ISSUE TITLE
gate way error 502

### ISSUE THREAD

**Issue by pouya8228** [hiddify/hiddify-config#76]
سلام ، بعد از یک بار تغییر زبان پنل به فارسی ، cpu usage  رفت بالا و بعد از تغییر دوباره به زبان انگلیسی . دیگه پنل باز نمیشه وخطای 502 میده .
سرور رو یکبار ریست کردم اما درست نشد .
کسی راه حلی داره؟

**Comment by hiddify** [comment]
please send the content of /opt/hiddify-config/log/system/0-install.log

**Comment by pouya8228** [comment]
This file contains IP and secrets, should I delete them? Or send it to you privately?

**Comment by shahabbasian** [comment]
یک بار توی سرور این دستور رو بزن تا اپدیت کنه و تنظیم مجدد

```
cd /opt/hiddify-config
sudo bash update.sh
```

**Comment by pouya8228** [comment]
خیلی ممنون . حل شد مشکلم

**Comment by shahabbasian** [comment]
> please send the content of /opt/hiddify-config/log/system/0-install.log

وقتی توی پنل ادمین در اقدامات اعمال تغییرات رو میزنیم این مشکل پیش بیاد بعضی وقت‌ها

**Comment by lumanjre** [comment]
plz update to latest version. tnx
