### ISSUE TITLE
Get Error 500 4.2.6

### ISSUE THREAD

**Issue by AliGh1** [hiddify/hiddify-config#778]
**Describe the bug**
بعد از آپدیت به ورژن 2.4.6
 خطای
 500
 میده و نه بکاپ کار میکنه نه با 
ssh
 درست میشه

**Screenshots**
![image](https://user-images.githubusercontent.com/60067642/233616632-2b9b0a71-cb1e-41d7-9594-6b1f73b21dae.png)

**Comment by ali1565** [comment]
با درود 
یکبار پنل را دوباره install بفرمایید.

**Comment by AliGh1** [comment]
در آپدیت بعدی درست شد
