### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by nnotecode** [hiddify/hiddify-config#78]
لینک کاربران چه با فعال بودن cdn و چه با غیرفعال بودنش لود نمیشه! 
و کلاً همش با آی پی وارد پنل میشم و با دامینی که انتخاب شده برای cdn این امکان وجود نداره

**Comment by ipod2010** [comment]
سلام متاسفانه لینک کاربرا رو برام نفرستاد و مراحل رو همه با دقت رو به جلو رفتم

**Comment by nnotecode** [comment]
وقتی رفتم تنظیمات https‌ رو فعال کردم، صفحه‌های کاربران رو تونستم باز کنم و از کانفینگ‌ها تست بگیرم. ( تا اینجا همه‌چیز عالیه )
فقط مشکل اینجاست که توی این آپدیت هایدیفای یک کانفیگ نیست که تنها کانفیگی بود که روی همراه اول میشد استفاده کرد.
این کانفینگ‌هایی هم که اضافه شدن فعلاً هیچکدوم کار نمی‌کنن( ایرانسل-همراه اول-رایتل-مبین نت تست شدن )

![image](https://user-images.githubusercontent.com/31673794/217239808-03445b74-318f-4f7e-9311-0243ebd020c5.jpeg)

این تنها کانفینگی بود که وصل میشد روی پنل قبلی.
در کل بابت آپدیت ممنون هایدیفای عزیز و خوشحالتر میشیم که توی این آپدیت این کانفینگ رو هم اضافه کنید

**Comment by botgame96** [comment]
سلام 
بعد از اینکه QR code رو میگیرم برای کپی لینک در کلش ارور های متعددی میاد و در ضمن انگار یک باگی داره که بعد از ساخت چندین یوزر IP سیستمی بن میشه !!!!!!!! واقعا باگ عجیبیه تو بعضی از گوشی ها کار میکنه ولی بعضی ها دیگه نه یک چیز دیگه که خیلی رو مخم رفته گرفتن کانفیگ هستش از QR code واقعا مشکل داره چون همش میگه نمی تونم دانلود کنم پروفایل رو  :|

**Comment by lumanjre** [comment]
plz update to latest version. it s solved
