### ISSUE TITLE
مشکل اضافه کردن دامنه در نسخه 4.3.1

### ISSUE THREAD

**Issue by randomguy-on-internet** [hiddify/hiddify-config#786]
در نسخه جدید نمیشه دامنه اضافه کرد، ارور 502 میاد با پروکسی و بدون پروکسی تست کردم کار نکرد.

**Comment by ea1234567** [comment]
بله دقیقا
من تا ورژن قبلی هیچ مشکلی نداشتم
ولی ورژن جدید پنل رو که از اول نصب میکنم
همون اول کار که وارد پنل میشم میگه یه دامین وارد کن،دامین رو که میزنم دیگه برای دامین ssl دریافت نمیکنه
