### ISSUE TITLE
Getting an error when changing the setting

### ISSUE THREAD

**Issue by Ahed1980** [hiddify/hiddify-config#79]
سلام
هر تغییر که در ستینگ داده میشه پیغام میده که یکی از فیلدها دچار مشکل هست و تغییرات با خطا همراه هست. تمام تنظیمات رو غیرفعال کردم اما باز هم خطا میداد.
یوزری هم نتونستم درست کنم یعنی در قسمت پراکسی نتونستم کانفیگی بسازم.
پنل رو ریست کردم و الان دیگه دسترسی به پنل هم ندارم هیچکدوم از لینکها کار نمیکنه.
(منو روی فارسی بود)

**Comment by amin30000** [comment]
دقیقا برای من هم همین مشکل ایجاد شد و جالب اینجاس که با ریست کردن پاک کردن سرور و دوباره نصب کردن هم دیگه به پنل دسترسی ندارم

**Comment by hmdrza01** [comment]
من این دستور رو هم تست کردم ولی باز هم همین خطا رو داد.

**Comment by hiddify** [comment]
fixed

**Comment by amin30000** [comment]
من نصب کردم در بخش تنظیمات رفتم فارسی کردم دوباره همه چی دان شد
