### ISSUE TITLE
مشکل certificate

### ISSUE THREAD

**Issue by VPN-AZADI** [hiddify/hiddify-config#81]
هنگام import کردن کانفیگ به صورت مستقیم با لینک آپدیت ارور certificate ایجاد میشه و اجازه افزودن سرور ها رو به کلاینت ها ، چه clash چه hiddify و حتی v2rayNG رو نمیده

**Comment by hiddify** [comment]
مستقیم خطای سرتیفیکیت میده؟

**Comment by VPN-AZADI** [comment]
لینک های subscription خطای certificate میده

**Comment by hiddify** [comment]
منظورم اینه خود صفحه کاربران درست باز میشه؟
لینک تو ایمیل بفرستید برام

**Comment by swifast** [comment]
درود بر شما خسته نباشید،‌کلا گویا ‌acme درست مراحل گرفتن certificate رو انجام نمیده چون پیام میده که فایل .crt رو پیدا نمیکنه

**Comment by archiveha** [comment]
سلام و خسته نباشید
واقعا سرویسی که درست کردید خیلی عالیه.
وقت تو آپدیت جدید وقتی میخوای کانفیگ موبایل رو انجام بدی ارور x509 certificate signed by unknown authority میده ولی ویندوز به درست کار میکنه. 
ممنون میشم راه حلی ارائه بدید.

**Comment by swifast** [comment]
درود مجدد، مشکل certificate دامین من با تغییر سرور acme از letsencrypt به zerossl و تغییر ایمیل پیشفرض حل شد، امیدوارم که تونسته باشم کمک کوچیکی بکنم. موفق باشید دمتون گرم

**Comment by archiveha** [comment]
> درود مجدد، مشکل certificate دامین من با تغییر سرور acme از letsencrypt به zerossl و تغییر ایمیل پیشفرض حل شد، امیدوارم که تونسته باشم کمک کوچیکی بکنم. موفق باشید دمتون گرم

لطفا لینک راهنمایی دارید به اشتراک بزارید.

**Comment by archiveha** [comment]
> > درود مجدد، مشکل certificate دامین من با تغییر سرور acme از letsencrypt به zerossl و تغییر ایمیل پیشفرض حل شد، امیدوارم که تونسته باشم کمک کوچیکی بکنم. موفق باشید دمتون گرم
> 
> لطفا لینک راهنمایی دارید به اشتراک بزارید.

کسی نیست راهنمایی کنه مشکل ssl در گوشی ها رو چجوری حل کنم ؟

**Comment by hiddify** [comment]
موضوع حل شد
وقتی از برنامه آپدیت میشد مسیر سرتیفیکیت ها تغییر میکرد
ممنون از اطلاع
