### ISSUE TITLE
Finding Netdata in the new version

### ISSUE THREAD

**Issue by robin98** [hiddify/hiddify-config#82]
Hello hiddify team and thank you for this incredible and job.
In the last version we can access the Netdata panel from our admin page. I noticed that in the new version we still have the option for the Netdata App, but I can't find the panel anywhere!

**Comment by hiddify** [comment]
just add netdata at the end of the path 
link https://domain.com/secret/secret/admin/netdata/

I do not know how to put it in the panel in a good way
