### ISSUE TITLE
کار نکردن mtproto 

### ISSUE THREAD

**Issue by Ehsan2206** [hiddify/hiddify-config#84]
سلام من روی چند تا ای پی با سرور اوبونتو نصب کردم ولی قسمت mtproto یا همون پراکسی تلگرامش کار نمیکنه،و اینکه یه قسمت توی تنظیمات اضافه کنید که بشه نوع head پروتکل را نوشت مثل اسم سایت ها.
با تشکر

**Comment by hiddify** [comment]
واضح تر بگید در مورد پیشنهاد آخرتون لطفا

**Comment by Ehsan2206** [comment]
![Screenshot_20230208_112213](https://user-images.githubusercontent.com/62577213/217467807-e88a5a24-ce51-40a1-b46d-744e1feabe68.jpg)
منظورم اینه که این قسمت example.ir را داخل تنظیمات اضافه کنید ،با تغییر این قسمت گذاشتن دامنه های ایرانی پینگ و سرعت بیشتری میشه دریافت کرد

**Comment by hiddify** [comment]
پروکسی تلگرام هم به نظر حل شد لطفا تست کنید

**Comment by Ehsan2206** [comment]
تست کردم متاسفانه کار نمیده هنوز

**Comment by hiddify** [comment]
روی مود پایتون؟

**Comment by Ehsan2206** [comment]
بله روی تمام مود ها

**Comment by Zed-Max-Wolf** [comment]
منم همین مشکل رو دارم

**Comment by Ehsan2206** [comment]
به این نتیجه رسیدم که در صورتی پروکسی تلگرام کار میکنه که روی پایتون باشه و همچنین دارای تبلیغات نباشه و اینکه دامین فرانتیگ فعال نکرده باشید ، حالا تقاضا مندم در صورت امکان این باگ را بر طرف کنید و همچنین اون گزینه ای که در بالا گفتم را فعال کنید

**Comment by hiddify** [comment]
تست شد پروکسی گو و پایتون کار میکند
پروکسی گو تگ تبلیغاتی ساپورت نمیکنه
