### ISSUE TITLE
نصب ssl

### ISSUE THREAD

**Issue by mlm1102003** [hiddify/hiddify-config#86]
سلام
تو تنظیمات جایی برای وارد کردن ssl  سرت برای دامنه ای که وارد می کنم ندیدم 
وقتی دامنه وارد می کنم و می خوام وارد بشم میزنه ssl نداره

**Comment by hiddify** [comment]
اتوماتیک خودش میگیره دیگه متوجه نمیشم

**Comment by mlm1102003** [comment]
من دامنه خریدم 
تو کلودفلر زیر دامنه ثبت کردم

تو اوبونتو پروکسی رو نصب کردم 

وارد تنظیمات اولیه با ای پی شدم

زیر دامنه رو تو تنظیمات زدم 
حالا لینک ادمین با این زیر دامنه بم داده 
وقتی می خوام با زیر دامنه وارد بشم سایت باز نمیشه و میزنه cert نداره

**Comment by mlm1102003** [comment]
وقتی با https:// 
وارد ادمین می خوام بشم

An error occurred during a connection to ....... SSL peer has no certificate for the requested DNS name.

Error code: SSL_ERROR_UNRECOGNIZED_NAME_ALERT

**Comment by lymanjre** [comment]
آپیدت کنید به آخرین ورژن مشکلی نداریم
