### ISSUE TITLE
مشکلات اپدیت جدید

### ISSUE THREAD

**Issue by amin30000** [hiddify/hiddify-config#87]
سلام 
در آپدیت جدید  به هیچ کدوم از کانکشن ها نصب نمیتونم بشم

**Comment by ezrbidoky** [comment]
دقیقا منم همین مشکلو دارم
نت ایرانسل و همراه اول هیچ کدوم جواب نمیده
ورژن قبلی روی ایرانسل خیلی خوب بود

**Comment by mohsen-shobeyri** [comment]
من هم همین مشکل رو دارم
یکی دوتا از پروتکل ها تو ورژن قبلی با نت همراه اول، ایرانسل و وای فای  تست کردم خیلی خوب و با سرعت کار میکرد اما متاسفانه تو ورژن جدید اون پروتکل ها نیستند و بقیه پروتکل ها هم کار نمیکنه

**Comment by Zed-Max-Wolf** [comment]
منم همین مشکل رو دارم

**Comment by nimadev98** [comment]
I have the same problem
Only mtproto working for me
Tested on MCI and Irancell

**Comment by mohsen-shobeyri** [comment]
دوستان من مشکلم برطرف شد
یه راهنمای کامل مینویسم امیدوارم مشکل شما هم حل بشه

من از CDN کلودفلر و دیتاسنتر هتزنر استفاده میکنم که تو کلود فلر هر دوتا IP ورژن 4 و 6 رو ثبت کردم
این مهمه که حتما پروکسی رو برای IP هاتون روشن کنید تا بعدا بتونید تو پنل هایدیفای CDN دامنه رو فعال کنید

برای اولین بار که وارد پنل شدید دامنه‌ای که تو کلود فلر ثبت کردید رو وارد کنید و تو بخش ریدایرکت هم یه سایت ترجیحا خارجی اضاف کنید

بعدش که پنل کامل فعال شد وارد بخش دامنه بشید و حالت دامنه رو از Direct به CDN تغییر بدید و تغییرات کانفیگ رو اعمال کنید

بعد وارد تنظیمات بشید و مطمئن بشید Domain Fronting برای https فعال باشه و یه سایت مثلا ایرانی که از CDN کلود فلر استفاده میکنه رو هم بهش معرفی کنید (لینک سایت ها رو خود هایدیفای هم تو گیت هاب گذاشته)
میتونید تنظیمات V2Ray رو هم فعال کنید
ترجیحا Vmess رو غیر فعال کنید بهتره
برای امنیت بیشتر میتونید تنظیمات http رو غیر فعال کنید
من بلاک سایت های ایران رو غیر فعال کردم تا راحت تر بتونم به پنل متصل بشم شما میتونید فعال بذارید

بعد وارد پروکسی ها بشید و مطمئن بشید TLS domain fronting فعال باشه و کانکشن های http رو غیر فعال کنید
با تست هایی که انجام دادم کانکشن های زیر کار نمیکنه که میتونید تو پنل غیر فعالشون کنید تا نرم افزارتون الکی شلوغ نشه
tls WS direct trojan
tls tcp direct trojan
tls WS Fake trojan
بقیه کانکشن ها رو فعال بذارید من با نت همراه اول و وای فای تست کردم جواب میده سرعتشون عالی هست
حتما یادتون باشه بعد از انجام کارها تغییرات کانفیگ ها رو تو پنلتون اعمال کنید

در آخر هم از هایدیفای عزیز بخاطر ارائه و پشتیبانی این سرویس‌ها تشکر میکنم - واقعا دمتون گرم ما هم ازتون حمایت میکنیم

**Comment by amin30000** [comment]
> دوستان من مشکلم برطرف شد یه راهنمای کامل مینویسم امیدوارم مشکل شما هم حل بشه
> 
> من از CDN کلودفلر و دیتاسنتر هتزنر استفاده میکنم که تو کلود فلر هر دوتا IP ورژن 4 و 6 رو ثبت کردم این مهمه که حتما پروکسی رو برای IP هاتون روشن کنید تا بعدا بتونید تو پنل هایدیفای CDN دامنه رو فعال کنید
> 
> برای اولین بار که وارد پنل شدید دامنه‌ای که تو کلود فلر ثبت کردید رو وارد کنید و تو بخش ریدایرکت هم یه سایت ترجیحا خارجی اضاف کنید
> 
> بعدش که پنل کامل فعال شد وارد بخش دامنه بشید و حالت دامنه رو از Direct به CDN تغییر بدید و تغییرات کانفیگ رو اعمال کنید
> 
> بعد وارد تنظیمات بشید و مطمئن بشید Domain Fronting برای https فعال باشه و یه سایت مثلا ایرانی که از CDN کلود فلر استفاده میکنه رو هم بهش معرفی کنید (لینک سایت ها رو خود هایدیفای هم تو گیت هاب گذاشته) میتونید تنظیمات V2Ray رو هم فعال کنید ترجیحا Vmess رو غیر فعال کنید بهتره برای امنیت بیشتر میتونید تنظیمات http رو غیر فعال کنید من بلاک سایت های ایران رو غیر فعال کردم تا راحت تر بتونم به پنل متصل بشم شما میتونید فعال بذارید
> 
> بعد وارد پروکسی ها بشید و مطمئن بشید TLS domain fronting فعال باشه و کانکشن های http رو غیر فعال کنید با تست هایی که انجام دادم کانکشن های زیر کار نمیکنه که میتونید تو پنل غیر فعالشون کنید تا نرم افزارتون الکی شلوغ نشه tls WS direct trojan tls tcp direct trojan tls WS Fake trojan بقیه کانکشن ها رو فعال بذارید من با نت همراه اول و وای فای تست کردم جواب میده سرعتشون عالی هست حتما یادتون باشه بعد از انجام کارها تغییرات کانفیگ ها رو تو پنلتون اعمال کنید
> 
> در آخر هم از هایدیفای عزیز بخاطر ارائه و پشتیبانی این سرویس‌ها تشکر میکنم - واقعا دمتون گرم ما هم ازتون حمایت میکنیم

اقا دمت گرم تمام نکاتی که گفتی رو رعایت کردم و داره روی نت من که فک میکنم از سخت ترین فیلتر ها رو داره کار کرد ولی همون های که گفتی کار نمیکنه

**Comment by amin30000** [comment]
در پنل کاربری نمایش جزئیات استفاده رو که میزنیم چیزی باز نمیشه

**Comment by SirShateri** [comment]
سلام. در آپدیت جدید صفحه Users و پنل‌‌ با دامین اصلا باز نمیشه. کلا گویا با HTTPS مشکل پیدا کرده. چکار میشه کرد؟

**Comment by saadiparsia** [comment]
سلام دوستان شما با هیچ روشی تونستید با ایرانسل کانکت بشید ؟؟؟

> دوستان من مشکلم برطرف شد یه راهنمای کامل مینویسم امیدوارم مشکل شما هم حل بشه
> 
> من از CDN کلودفلر و دیتاسنتر هتزنر استفاده میکنم که تو کلود فلر هر دوتا IP ورژن 4 و 6 رو ثبت کردم این مهمه که حتما پروکسی رو برای IP هاتون روشن کنید تا بعدا بتونید تو پنل هایدیفای CDN دامنه رو فعال کنید
> 
> برای اولین بار که وارد پنل شدید دامنه‌ای که تو کلود فلر ثبت کردید رو وارد کنید و تو بخش ریدایرکت هم یه سایت ترجیحا خارجی اضاف کنید
> 
> بعدش که پنل کامل فعال شد وارد بخش دامنه بشید و حالت دامنه رو از Direct به CDN تغییر بدید و تغییرات کانفیگ رو اعمال کنید
> 
> بعد وارد تنظیمات بشید و مطمئن بشید Domain Fronting برای https فعال باشه و یه سایت مثلا ایرانی که از CDN کلود فلر استفاده میکنه رو هم بهش معرفی کنید (لینک سایت ها رو خود هایدیفای هم تو گیت هاب گذاشته) میتونید تنظیمات V2Ray رو هم فعال کنید ترجیحا Vmess رو غیر فعال کنید بهتره برای امنیت بیشتر میتونید تنظیمات http رو غیر فعال کنید من بلاک سایت های ایران رو غیر فعال کردم تا راحت تر بتونم به پنل متصل بشم شما میتونید فعال بذارید
> 
> بعد وارد پروکسی ها بشید و مطمئن بشید TLS domain fronting فعال باشه و کانکشن های http رو غیر فعال کنید با تست هایی که انجام دادم کانکشن های زیر کار نمیکنه که میتونید تو پنل غیر فعالشون کنید تا نرم افزارتون الکی شلوغ نشه tls WS direct trojan tls tcp direct trojan tls WS Fake trojan بقیه کانکشن ها رو فعال بذارید من با نت همراه اول و وای فای تست کردم جواب میده سرعتشون عالی هست حتما یادتون باشه بعد از انجام کارها تغییرات کانفیگ ها رو تو پنلتون اعمال کنید
> 
> در آخر هم از هایدیفای عزیز بخاطر ارائه و پشتیبانی این سرویس‌ها تشکر میکنم - واقعا دمتون گرم ما هم ازتون حمایت میکنیم

دوست عزیز من تو کلودفلر وقتی پروکسی رو فعال میکنم و میخوام ساب دامین اضافه کنم هایدیفای خطا میاره و میگه آدرس دامین شما با آدرس دامین کلادفلر یکی نیست

**Comment by hiddify** [comment]
خطا را بفرست مطمئنم درست نمیگی

**Comment by saadiparsia** [comment]
خب متاسفانه الان پشت سیستم نیستم که براتون خطا رو بفرستم اما یا من اشتباه متوجه شدم یا توضیح مشکل داره . این دوستمون فرمودند حتما باید پروکسی کلادفلر روشن باشه تا CDN هایدیفای کار کنه من پروکسی رو فعال کردم و زمانی که می‌خوام هایدیفای رو کانفیگ کنم میگه داکین کلادفلر با دامین هایدیفای که ست شده یکی نیست که باید بخاطر پروکسی فعال باشه . بعد اگر بخوام بعد CDN رو فعال کنم  و پروکسی رو فعال کنم باز هم هیچ تفاوتی نمیکنه و ایرانسل رو هیچ کانفیگی‌جواب نمیده من صرفا می‌خوام ایرانسل با یک کانفیگ به هر شکلی که شده جواب بده تو v2ray رو بعضی کانفیگا جواب میده اما موقتی

**Comment by emadtoranji** [comment]
سلام عزیز. وقتت بخیر
یکی از باگ ها این هستش که User usage بصورت خودکار هر ۶ دقیقه آپدیت نمیشه و حتما باید بصورت دستی اینکار انجام بشه.
ممنون از شما

**Comment by saadiparsia** [comment]
> سلام عزیز. وقتت بخیر یکی از باگ ها این هستش که User usage بصورت خودکار هر ۶ دقیقه آپدیت نمیشه و حتما باید بصورت دستی اینکار انجام بشه. ممنون از شما

دوست عزریز امکانش هست از طریق تلگرام راهنماییم کنید ؟؟ خیلی ممنون میشم @slink0101

**Comment by emadtoranji** [comment]
> > سلام عزیز. وقتت بخیر یکی از باگ ها این هستش که User usage بصورت خودکار هر ۶ دقیقه آپدیت نمیشه و حتما باید بصورت دستی اینکار انجام بشه. ممنون از شما
> 
> دوست عزریز امکانش هست از طریق تلگرام راهنماییم کنید ؟؟ خیلی ممنون میشم @slink0101

عزیز من جز طراح های این اسکریپت نیستم، فقط یکی از باگ هارو گزارش کردم

**Comment by saadiparsia** [comment]
> > > سلام عزیز. وقتت بخیر یکی از باگ ها این هستش که User usage بصورت خودکار هر ۶ دقیقه آپدیت نمیشه و حتما باید بصورت دستی اینکار انجام بشه. ممنون از شما
> > 
> > 
> > دوست عزریز امکانش هست از طریق تلگرام راهنماییم کنید ؟؟ خیلی ممنون میشم @slink0101
> 
> عزیز من جز طراح های این اسکریپت نیستم، فقط یکی از باگ هارو گزارش کردم

شما تونستید همراه اول و ایرانسل رو حل کنید مشکلش رو ؟؟؟

**Comment by emadtoranji** [comment]
برای روی همش متصل میشه اما یهو سرعت به شدت کاهش پیدا میکنه یا کلا قطع میشه. که اینم به نظرم میتونه اختلال هایی باشه که روی آیپی های پروکسی کلودفلر میندازن باشه. فعلا راه حلی برای ثابت بودن کیفیت پیدا نکردم

**Comment by emadtoranji** [comment]
> > > > سلام عزیز. وقتت بخیر یکی از باگ ها این هستش که User usage بصورت خودکار هر ۶ دقیقه آپدیت نمیشه و حتما باید بصورت دستی اینکار انجام بشه. ممنون از شما
> > > 
> > > 
> > > دوست عزریز امکانش هست از طریق تلگرام راهنماییم کنید ؟؟ خیلی ممنون میشم @slink0101
> > 
> > 
> > عزیز من جز طراح های این اسکریپت نیستم، فقط یکی از باگ هارو گزارش کردم
> 
> شما تونستید همراه اول و ایرانسل رو حل کنید مشکلش رو ؟؟؟


برای من روی همش متصل میشه اما یهو سرعت به شدت کاهش پیدا میکنه یا کلا قطع میشه. که اینم به نظرم میتونه اختلال هایی باشه که روی آیپی های پروکسی کلودفلر میندازن باشه. فعلا راه حلی برای ثابت بودن کیفیت پیدا نکردم

**Comment by mmdjvdad** [comment]
> سلام دوستان شما با هیچ روشی تونستید با ایرانسل کانکت بشید ؟؟؟
> 
> > دوستان من مشکلم برطرف شد یه راهنمای کامل مینویسم امیدوارم مشکل شما هم حل بشه
> > من از CDN کلودفلر و دیتاسنتر هتزنر استفاده میکنم که تو کلود فلر هر دوتا IP ورژن 4 و 6 رو ثبت کردم این مهمه که حتما پروکسی رو برای IP هاتون روشن کنید تا بعدا بتونید تو پنل هایدیفای CDN دامنه رو فعال کنید
> > برای اولین بار که وارد پنل شدید دامنه‌ای که تو کلود فلر ثبت کردید رو وارد کنید و تو بخش ریدایرکت هم یه سایت ترجیحا خارجی اضاف کنید
> > بعدش که پنل کامل فعال شد وارد بخش دامنه بشید و حالت دامنه رو از Direct به CDN تغییر بدید و تغییرات کانفیگ رو اعمال کنید
> > بعد وارد تنظیمات بشید و مطمئن بشید Domain Fronting برای https فعال باشه و یه سایت مثلا ایرانی که از CDN کلود فلر استفاده میکنه رو هم بهش معرفی کنید (لینک سایت ها رو خود هایدیفای هم تو گیت هاب گذاشته) میتونید تنظیمات V2Ray رو هم فعال کنید ترجیحا Vmess رو غیر فعال کنید بهتره برای امنیت بیشتر میتونید تنظیمات http رو غیر فعال کنید من بلاک سایت های ایران رو غیر فعال کردم تا راحت تر بتونم به پنل متصل بشم شما میتونید فعال بذارید
> > بعد وارد پروکسی ها بشید و مطمئن بشید TLS domain fronting فعال باشه و کانکشن های http رو غیر فعال کنید با تست هایی که انجام دادم کانکشن های زیر کار نمیکنه که میتونید تو پنل غیر فعالشون کنید تا نرم افزارتون الکی شلوغ نشه tls WS direct trojan tls tcp direct trojan tls WS Fake trojan بقیه کانکشن ها رو فعال بذارید من با نت همراه اول و وای فای تست کردم جواب میده سرعتشون عالی هست حتما یادتون باشه بعد از انجام کارها تغییرات کانفیگ ها رو تو پنلتون اعمال کنید
> > در آخر هم از هایدیفای عزیز بخاطر ارائه و پشتیبانی این سرویس‌ها تشکر میکنم - واقعا دمتون گرم ما هم ازتون حمایت میکنیم
> 
> دوست عزیز من تو کلودفلر وقتی پروکسی رو فعال میکنم و میخوام ساب دامین اضافه کنم هایدیفای خطا میاره و میگه آدرس دامین شما با آدرس دامین کلادفلر یکی نیست

وقتی دامنه رو میخوای داخل هیدیفای بزاری نوعشو نزار روی Direct بزار روی CDN
