### ISSUE TITLE
مشکل دانلود و پخش ویدیو در یوتیوب

### ISSUE THREAD

**Issue by Zed-Max-Wolf** [hiddify/hiddify-config#88]
سلام، ممنون بابت زحماتتون
بعد از روشن کردن پروکسی توی بعضی از سایت ها فایل هایی که برای دانلود گذاشتند دانلود نمیشه مثلاً لینک ها داخل سایت : https://sourceforge.net

مشکل بعدی پخش نشدن ویدیو های یوتیوب هست، با گوشی و کامپیوتر تست کردم تو یوتیوب ویدیو ها تو لودینگ گیر میکنه و نمایش نمیده.

بعد از آپدیت پروکسی تلگرام هم کار نمیکنه

**Comment by hiddify** [comment]
میشه بیشتر توضیح بدید از چه برنامه ای استفاده کردید کدوم پروتوکل و اینکه پروتوکل های دیگه جواب نمیدادن ؟

**Comment by Zed-Max-Wolf** [comment]
https://user-images.githubusercontent.com/124817540/217872436-a01a97b2-de3e-4f5b-9eb5-cd06059ce958.mp4

مشکل پخش نشدن ویدیو های یوتیوب رو 1 فیلم گرفتم که ببینید متوجه منظورم میشید.

مشکل پروکسی تلگرام هم اوکی شده ممنون

**Comment by hiddify** [comment]
روی کدوم مود تست کردید

**Comment by Zed-Max-Wolf** [comment]
اگر منظور از مد همون فقط برای سایت‌های فیلتر شده یا پروکسی سایت‌های خارجی هست که از مد پیشنهادی : فقط برای سایت‌های فیلتر شده استفاده کردم 

اما اگر منظورتون مورد دیگری هستید بفرمایید که متوجه بشم.

سپاس از پیگیریتون

**Comment by hiddify** [comment]
مود همه سایت ها یوتیوب را خوب نشون میده؟

**Comment by Zed-Max-Wolf** [comment]
بله مود همه سایت ها بدون مشکل کار میکنه

**Comment by hiddify** [comment]
اگه دانش فنی دارید از inspect element بگید چه سایتیه که مشکل داره رفع کنم

**Comment by hiddify** [comment]
آپدیت کنید باید حل شده باشه
