### ISSUE TITLE
امکان استفاده از ssl Cloudflare

### ISSUE THREAD

**Issue by Glimpser-zz** [hiddify/hiddify-config#89]
*********************************************888

**Comment by mehr30na** [comment]
من از cdn کلودفلر استفاده کردم پنل بالا میاد ولی کاربرا نمیتونن وصل شن احتمالا آیپی های کلودفلر بلاک شده. از سی دی ان های ایرانی استفاده کنین جواب میده

**Comment by Glimpser-zz** [comment]
من با x-ui از cdn کلود فلر روی همراه اول استفاده کردم و بلاک نیستند  ممنون میشم اگر راهی برای حل موضوع پیشنهاد کنید

**Comment by mohsen-shobeyri** [comment]
> من با x-ui از cdn کلود فلر روی همراه اول استفاده کردم و بلاک نیستند ممنون میشم اگر راهی برای حل موضوع پیشنهاد کنید

من همین مشکل رو داشتم که برطرف شد
یه راهنمای کامل مینویسم امیدوارم مشکل شما هم حل بشه

من از CDN کلودفلر و دیتاسنتر هتزنر استفاده میکنم که تو کلود فلر هر دوتا IP ورژن 4 و 6 رو ثبت کردم
این مهمه که حتما پروکسی رو برای IP هاتون روشن کنید تا بعدا بتونید تو پنل هایدیفای CDN دامنه رو فعال کنید

برای اولین بار که وارد پنل شدید دامنه‌ای که تو کلود فلر ثبت کردید رو وارد کنید و تو بخش ریدایرکت هم یه سایت ترجیحا خارجی اضاف کنید

بعدش که پنل کامل فعال شد وارد بخش دامنه بشید و حالت دامنه رو از Direct به CDN تغییر بدید و تغییرات کانفیگ رو اعمال کنید

بعد وارد تنظیمات بشید و مطمئن بشید Domain Fronting برای https فعال باشه و یه سایت مثلا ایرانی که از CDN کلود فلر استفاده میکنه رو هم بهش معرفی کنید (لینک سایت ها رو خود هایدیفای هم تو گیت هاب گذاشته)
میتونید تنظیمات V2Ray رو هم فعال کنید
ترجیحا Vmess رو غیر فعال کنید بهتره
برای امنیت بیشتر میتونید تنظیمات http رو غیر فعال کنید
من بلاک سایت های ایران رو غیر فعال کردم تا خودم و یوزرها راحت تر بتونیم به پنل متصل بشم شما میتونید فعال بذارید

بعد وارد پروکسی ها بشید و مطمئن بشید TLS domain fronting فعال باشه و کانکشن های http رو غیر فعال کنید
با تست هایی که انجام دادم کانکشن های زیر کار نمیکنه که میتونید تو پنل غیر فعالشون کنید تا نرم افزارتون الکی شلوغ نشه
tls WS direct trojan
tls tcp direct trojan
tls WS Fake trojan
بقیه کانکشن ها رو فعال بذارید من با نت همراه اول و وای فای تست کردم جواب میده سرعتشون عالی هست
حتما یادتون باشه بعد از انجام کارها تغییرات کانفیگ ها رو تو پنلتون اعمال کنید

**Comment by lymanjre** [comment]
به زودی کلادفلر هم اتوماتیک میشه دیگه نیاز به این کار نیست
