### ISSUE TITLE
مشکل در ریالیتی ها بعد از آپدیت به نسخه 6.0.1

### ISSUE THREAD

**Issue by GetPHP-IR** [hiddify/hiddify-config#893]
بعد از آپدیت پنل به نسخه 6.0.1 ریالیتی ها از کار افتادن و در تنظیمات قسمت ویرایش پروکسی غیرفعال شدن خودبه خود.
هنگام استفاده از ریالیتی در سمت کاربر هم این خطا رو میده:
`2023/05/01 23:21:09 [Warning] [4204099541] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: x509: certificate is valid for mydomain.com, not www.fdn.sharezilla.ir"] > common/retry: all retry attempts failed`

**Comment by robin98** [comment]
تایید می کنم، منم از امروز متوجه شدم که احتمالا بخاطر آپدیت مشکلاتی توی ریالیتی بوجود اومده. با ایرانسل اوکیه ولی روی مخابرات مشکلات عجیبی داره (تلگرامو‌ باز‌ میکنه ولی مرورگر هیچ سایتیو نمیتونه لود کنه) که اینم‌ از عجایب روزگاره.
روی همین سرور به صورت دستی روی یه پورت دیگه خودم ریالیتی رو آوردم بالا و با همون دامنه فیک کانفیگش کردم، هیچ مشکلی وجود نداشت.
احتمال بالای 90 درصد مشکل از طرف آپدیت جدید هیدیفای هست.

**Comment by GetPHP-IR** [comment]
مشکل حل شد، خطا در دامنه ای بود که می دادم
