### ISSUE TITLE
uinstall installed packages 

### ISSUE THREAD

**Issue by miladj3** [hiddify/hiddify-config#9]
how can uninstall al packages installed via this script?

**Comment by hiddify** [comment]
I did not prepare such script.
You can look for apt install in the script and change them to apt remove

**Comment by myhidhacker** [comment]
There should be such a script.
The installation interferes with other installed x2ray packages.

**Comment by hiddify** [comment]
سلام
لطفا به ورژن جدید به روز رسانی کنید و نتیجه را اعلام کنید
با سپاس
