### ISSUE TITLE
بن شدن آی پی سرور خیلی زود

### ISSUE THREAD

**Issue by pouya8228** [hiddify/hiddify-config#91]
متاسفانه با اینکه فقط با یک یوز استافده میکردم و پروتکل v2ray , torjan کمتر از 24 ساعت سرور بن شد. پروتکل های دیگه رو هم توی پنل پیشنهاد داده شده بود که استفاده نکنیم چون زود سرور بلاک میشن .

**Comment by pouya8228** [comment]
آیا استفاده از آروان کلود با توجه به اینکه احراز هویت با موبایل و مشخصات داره برای این کار مناسب هست؟

**Comment by mohsen-shobeyri** [comment]
> متاسفانه با اینکه فقط با یک یوز استافده میکردم و پروتکل v2ray , torjan کمتر از 24 ساعت سرور بن شد. پروتکل های دیگه رو هم توی پنل پیشنهاد داده شده بود که استفاده نکنیم چون زود سرور بلاک میشن .

به احتمال زیاد پروتکل های http تون تو پنل فعال بوده و با اونا وصل میشدید که زود بن شده
حتما CDN رو فعال کنید و از پروتکل های https استفاده کنید و تمام گزینه هایی که تو پنل مربوط به http هست رو غیر فعال کنید اینجوری احتمال بن شدن IP خیلی خیلی کم میشه

**Comment by hiddify** [comment]
سلام 
گویا xtls معمولی مشکلاتی داشته و کلا از سیستم حذف شد.

در حالت فعلی برای مقابله با فیلترینگ باید fingerprint=chrome ست بشه سمت کلاینت

متاسفانه link نمیشه داد برای ست کردن فینگرپرینت

**Comment by pouya8228** [comment]
لطفا راهنمایی کنید چطوری میتونیم فینگر پرینت رو ست کنیم ، نمیخوام لینک بدم ، چون فقط خودم میخوام استفاده کنم
