### ISSUE TITLE
مشکل عجیب با گوگل 

### ISSUE THREAD

**Issue by sitsaz** [hiddify/hiddify-config#914]
با سلام و احترام 

من از روز گذشته در پنل 6.0.0dev3 با مشکل لود نشدن وبسایت گوگل و زیرمجموعه های ان مواجه هستم ، مشکل جایی عجیب می شود که وقتی این مشکل بر روی گوشی و با کلاینت های مختلف وجود دارد ، در ویندوز این مشکل وجود ندارد ، همچنین در برخی زمان ها در هردو گوشی و ویندوز نیز این مشکل وجود دارد ، در حال حاضر در گوشی اندرویدی یوتیوب به خوبی اجرا میشود اما جستجوی گوگل نتایجی نشان نمیدهد ( کلا کانکشن دراپ می شود ، مانند حالتی که وبسایت ایرانی باشد و ما آیپی های ایران را بلاک کرده باشیم ) در عین حال در ویندوز بدون هیچ مشکلی گوگل و یوتیوب اجرا می شود در حالی که دیشب در گوشی و ویندوز امکان استفاده از گوگل وجود نداشت

**Comment by sitsaz** [comment]
مشکل پس از استفاده از این روش 
https://github.com/Musixal/Marzban-Tools/tree/main/WARP
و انتخاب گزینه نصب 2 و سپس دستور warp-go g حل شد

**Comment by peymandelir** [comment]
وارپ نصب نمیشه. گزینه 3 فری اکانت رو که میزنم failed میاره. مشکلش چیه؟
