### ISSUE TITLE
Services "clash-server" & "hiddify-xray" failed

### ISSUE THREAD

**Issue by pouyavafi** [hiddify/hiddify-config#92]
سلام وقتتون بخیر، ممنون بابت پروژه ی زیباتون من همون طور که قبلا اعلام کردم اماده ی کمک برای محتواسازی درباره ی این پروژه هستم و منتظرم سرتون خلوت تر بشه و راهنماییم کنید چه کار کنم.
من سروری رو از (هاست ایران) خریداری کردم (2هسته4گیگ رم فالکنشتین) که ظاهرا خودشون از هتزنر میگیرند. روی ابرآروان تنظیم شد و سرویس کاملا عالی داشت کار می کرد تا صبح که یهو همه چیز قطع شد و دسترسی های ادمین و کاربرا بالا نمیاد (هیچ اتفاقی از سمت من نیفتاد و چیزی دستکاری نشد). سعی کردم سیستم رو دوباره نصب کنم با دستورات توی فولدر opt/hiddify-config اما چه قبل و چه بعد از تلاش بیهوده ی من (:دی!) وضعیت سرویس هام به این شکل دراومده:
![error](https://user-images.githubusercontent.com/121950872/217825039-8b81d47a-4b05-4e5b-a5bc-a5ef1081d7a2.JPG)
فایل لاگ یا ... وجود داره که بشه بررسی کرد کجا خطا داده؟ اصلا کار من هست و من میتونم بررسیش کنم؟

**Comment by pouyavafi** [comment]
> infra/conf: Shadowsocks password is not specified.

@hichkak ممنون از توجه شما ... متوجه نشدم ... ممکته بیشتر توضیح بدید

**Comment by hichkak** [comment]
This is the error you are looking for

**Comment by pouyavafi** [comment]
متشکرم. ببخشید که انقدر متوجه نمیشم! راهکاری داره؟ یه عنوان هم بهم بدید خودم میرم دنبالش ...

**Comment by hichkak** [comment]
دنبال حلش نبودم اما دوستان خودشون رفع میکنن

**Comment by pouyavafi** [comment]
خیلی ممنونم. پس صرفا منتظر باشیم و سرور رو دستی اپدیت کنیم ...
مرسی از وقتی که برای پاسخگویی به سایرین میزارید

**Comment by hiddify** [comment]
همیشه قبل از انجام عملیات مهم لینک اضطراری را کپی کنید
Hiddify-xray
