### ISSUE TITLE
باگ ورژن 6.1.3  از کار افتادن لینک های سابسکرایب

### ISSUE THREAD

**Issue by oxnetwork** [hiddify/hiddify-config#921]
درود و وقت بخیر در ورژن 6.1.3

تمامی لینک های سابسکرایب به مشکل برخورده

**Comment by FarshadFaramarzlou** [comment]
سلام منم این مشکلو دارم بعد از آپدیت لینک های سابسکریپشن به مشکل خوردن

**Comment by randomguy-on-internet** [comment]
منم این مشکلو دارم، فقط لینک های زیر از کار افتادن:
![Screenshot_1](https://user-images.githubusercontent.com/79375739/236023853-3af39349-3be0-4bbb-b6d1-dbe3835bc189.png)

**Comment by sepahdalton** [comment]
> درود و وقت بخیر در ورژن 6.1.3
> 
> تمامی لینک های سابسکرایب به مشکل برخورده

مدرکت چیه برا این حرفت ؟
بنده ۳تا پنل دارم و کلی یوزر و اپدیت نسخه اخر این مشکلو نداشتم
شما یکبار رییوت کن سرور رو و بعدش اپلی کانفینگ بزن
قبلش چک کن ایپی سرورت فیلتر نشده باشه و سابسکرایب هارو بصورت دایرکت ست کن یعنی مستقیم به ایپی سرور وصل باشه بدون cdn یا تونل

**Comment by randomguy-on-internet** [comment]
> > درود و وقت بخیر در ورژن 6.1.3
> > تمامی لینک های سابسکرایب به مشکل برخورده
> 
> مدرکت چیه برا این حرفت ؟ بنده ۳تا پنل دارم و کلی یوزر و اپدیت نسخه اخر این مشکلو نداشتم شما یکبار رییوت کن سرور رو و بعدش اپلی کانفینگ بزن قبلش چک کن ایپی سرورت فیلتر نشده باشه و سابسکرایب هارو بصورت دایرکت ست کن یعنی مستقیم به ایپی سرور وصل باشه بدون cdn یا تونل

داداش همیشه اینو در نظر داشته باش که اگه شما توی چیزی به مشکل نخوردی دلیل بر این نیست که مشکلی وجود نداره!
مشکل ماله این بود که اگر نام نمایشی دامنه ی سابسکرایب فارسی بود، لینک باز نمیشد.

**با هم دیگه درست رفتار کتیم!**

**Comment by oxnetwork** [comment]
> > درود و وقت بخیر در ورژن 6.1.3
> > تمامی لینک های سابسکرایب به مشکل برخورده
> 
> مدرکت چیه برا این حرفت ؟ بنده ۳تا پنل دارم و کلی یوزر و اپدیت نسخه اخر این مشکلو نداشتم شما یکبار رییوت کن سرور رو و بعدش اپلی کانفینگ بزن قبلش چک کن ایپی سرورت فیلتر نشده باشه و سابسکرایب هارو بصورت دایرکت ست کن یعنی مستقیم به ایپی سرور وصل باشه بدون cdn یا تونل


عزیز خود نویسنده هیدیفای دیشب توی گپ تلگرام اعلام کردن که فعلا مشکل داره !
میتونید برید چک کنید !!!! چند نفر هم همینجا اعلام کردن که مشکل داشتن دیشبم ابدیت 6.1.5 منشتر شد که باگ رفع شد
