### ISSUE TITLE
nginx.service: Failed with result 'exit-code'

### ISSUE THREAD

**Issue by pouyavafi** [hiddify/hiddify-config#94]
سلام خسته نباشید.
من روی یک سرور ابری از کشور ترکیه (اوبونتو 20 خام) سیستم رو نصب کردم بعد از نصب نتونستم به آی پی مراجعه کنم. از کنسول وضعیت انجین ایکس رو گرفتم و با این پیغام مواجه شدم :
![turkey-error](https://user-images.githubusercontent.com/121950872/217824901-607fe3d0-9f14-4bba-bbfb-4a40fab6972b.JPG)

**Comment by hiddify** [comment]
Fixed
