### ISSUE TITLE
مشکل عجیب

### ISSUE THREAD

**Issue by kaamyaab** [hiddify/hiddify-config#95]
با عرض سلام وقت بخیر خدمت شما و ممنون بابت پروژه ی خوب و کارآمدتون 

مشکلی داشتم خواستم با شما و دوستان درمیون بزارم اونم اینه که من 5 تا یوزر تعریف کردم وقتی از طریق یوزر #1 که برای خودم هست از کانفیگ های v2ray استفاده می کنم به خوبی کار میکنند اما وقتی بقیه یوزرها میخوان از کانفیگ v2ray  خودشون استفاده کنن نمیتونن و بهشون خطا میده.. مشکل چیه؟؟؟ لطفا اگه میشه برطرفش کنید <3

**Comment by hiddify** [comment]
اعمال تغییرات را بزنید
