### ISSUE TITLE
درخواست رفع باگ

### ISSUE THREAD

**Issue by kaamyaab** [hiddify/hiddify-config#97]
سلام. خسته نباشید. 
طبق بررسی هایی که خودم داشتم و در نظرات بقیه دوستان دیدم کانفیگ های v2ray با نام های tls_WS_Fake_vless_domain.com و tls_WS_Fake_trojan_domain.com برای هیچکدوم از کاربرها کار نمیکنه. اما من تونستم با یک تغییر جزئی مشکل را حل کنم. 
اون هم به این صورت که:
1- در قسمت Address باید یک ای پی از رنج آی پی های کلادفلر استفده کنیم (best.cf.iran.all)(مرتضی باشسیز)
یا از دامنه ی یکی از سایت هایی از کلادفلر استفاده می کنند برای مثال من از arzdigital.com استفاده کردم.
2- در قسمت camouflaged domain host باید نام دامنه ی خود را وارد کنیم
3- در قسمت SNI نیز مجددا نام دامنه ی خود را وارد کنیم.

تست کردم پینگ خیلی خوبی هم بهم داد. خواستم تجربه ام رو با شما درمیون بزارم تا باگ این قسمت از پروژتون رفع بشه و دوستان بتونن از کانفیگ fake tls هم استفاده کنند.

سپاس از توجه و همراهیتون.

**Comment by hiddify** [comment]
سلام
این اونوقت دامین فرانتینگ نمیشه
میتونید تو قسمت تعریف دامنه برای دامنه cdn یه ای پی تعریف کنید
