### ISSUE TITLE
اضافه کردن هسته Sing-Box و ECH

### ISSUE THREAD

**Issue by Gharib110** [hiddify/hiddify-config#975]
سلام لطفا پشتیبانی از هسته Sing-Box راهم اضافه کنید چون از ECH(Encrypted Client Hello) پشتیبانی میکنه و من خودم روش کارکردم اما نتونستم کنفیگ اش رو تنظیم کنم. شاید برای رمزنگاری sni روی بعضی از ISP ها موثر واقع بشه.

**Comment by essoojay** [comment]
+ Me, Supported!!

**Comment by Gharib110** [comment]
You have a panel that support sing-box ?
