### ISSUE TITLE
مشکل مهم و فوری

### ISSUE THREAD

**Issue by xzbnm** [hiddify/hiddify-config#98]
سلام وقت بخیر 
طبق آموزش ما جلو رفتم و یک subdomin از اون سایتی که معرفی کردین و یک دامنه از خودم روی سرور کانفیگ کردم
همه چی اکی بود که امروز پشتیبانی سرور به من ۳ پیام داد
` ابیوزی مبنی بر حملات بروت فورس از جانب سرورتان دریافت کرده‌ایم`
`ابیوزی مبنی بر عملیات نت اسکن در رابطه با سرورتان دریافت کرده‌ایم`
`ابیوزی مبنی بر ایمیل‌های اسپم در رابطه با سرورتان دریافت کرده‌ایم`

سرور مجازی کلاود Hetzner

**Comment by hiddify** [comment]
سلام لطفا ایمیل را بفرستید تا بتونیم بررسی کنیم
***@***.***
و همینطور دسترسی به سرور هم لطف کنید
ممنون
