### ISSUE TITLE
رفتن به صفحه ویزارد کانفیگ اولیه

### ISSUE THREAD

**Issue by amirmhs58** [hiddify/hiddify-config#99]
> **سلام
> 
> بعد از نصب سرور ipv6 اضافه کردیم به سرور
> ولی تشخیص نمیده.از کجا درستش کنیم؟
> 
> با تشکر**

**Comment by hiddify** [comment]
توی صفحه تنظیمات سیستم، تنظیمات پروکسی وجود داره
